{{- if and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llamenos.fullname" . }}
  labels:
    {{- include "llamenos.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "llamenos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
