{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llamenos.fullname" . }}-secrets
  labels:
    {{- include "llamenos.labels" . | nindent 4 }}
type: Opaque
data:
  admin-pubkey: {{ .Values.secrets.adminPubkey | b64enc | quote }}
  twilio-account-sid: {{ .Values.secrets.twilioAccountSid | default "" | b64enc | quote }}
  twilio-auth-token: {{ .Values.secrets.twilioAuthToken | default "" | b64enc | quote }}
  twilio-phone-number: {{ .Values.secrets.twilioPhoneNumber | default "" | b64enc | quote }}
{{- end }}
