{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llamenos.fullname" . }}
  labels:
    {{- include "llamenos.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "llamenos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- if .Values.metrics.scrapeTokenSecret }}
      bearerTokenSecret:
        name: {{ .Values.metrics.scrapeTokenSecret }}
        key: metrics-scrape-token
      {{- end }}
{{- end }}
