#!/usr/bin/env bun
/**
 * Protocol codegen tool.
 *
 * Generates Swift structs and Kotlin data classes from Zod schemas
 * (via toJSONSchema()) defined in packages/protocol/schemas/.
 * Also generates crypto label constants.
 *
 * Usage:
 *   bun run codegen           # Generate all platform types
 */

import {
  quicktype,
  InputData,
  JSONSchemaInput,
  JSONSchemaStore,
  type LanguageName,
} from 'quicktype-core'
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { getSchemaRegistry } from './schema-registry'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const GENERATED_DIR = resolve(__dirname, '../generated')
const CRYPTO_LABELS_FILE = resolve(__dirname, '../crypto-labels.json')

/**
 * Schema store backed by the full registry. Resolves $ref addresses by name
 * so that any future schema using $defs or z.lazy() resolves correctly.
 */
class FlatSchemaStore extends JSONSchemaStore {
  private readonly schemaMap: Map<string, object>

  constructor(schemas: Array<{ name: string; schema: string }>) {
    super()
    this.schemaMap = new Map(schemas.map(({ name, schema }) => [name, JSON.parse(schema)]))
  }

  async fetch(address: string): Promise<object | undefined> {
    return this.schemaMap.get(address)
  }
}

/**
 * Recursively remove "additionalProperties" from a JSON Schema object.
 * z.looseObject() emits additionalProperties: {} which causes quicktype to add
 * open-map index signatures to generated types. Strip it before passing to quicktype.
 */
function stripAdditionalProperties(schema: object): object {
  const s = JSON.parse(JSON.stringify(schema)) as Record<string, unknown>
  // Only strip unconstrained additionalProperties (empty object {} or true from z.looseObject).
  // Keep typed additionalProperties like { type: "number" } from z.record(z.string(), z.number()).
  const ap = s['additionalProperties']
  if (ap === true || (typeof ap === 'object' && ap !== null && Object.keys(ap).length === 0)) {
    delete s['additionalProperties']
  }
  if (s['properties'] && typeof s['properties'] === 'object') {
    for (const key of Object.keys(s['properties'] as object)) {
      const prop = (s['properties'] as Record<string, object>)[key]
      if (prop && typeof prop === 'object') {
        (s['properties'] as Record<string, object>)[key] = stripAdditionalProperties(prop) as object
      }
    }
  }
  if (Array.isArray(s['items'])) {
    s['items'] = (s['items'] as object[]).map(stripAdditionalProperties)
  } else if (s['items'] && typeof s['items'] === 'object') {
    s['items'] = stripAdditionalProperties(s['items'] as object)
  }
  return s
}

// Generate types for a target language from all schemas
async function generateForLanguage(
  language: LanguageName,
  schemas: Array<{ name: string; schema: string }>,
  rendererOptions: Record<string, string> = {},
): Promise<string[]> {
  const store = new FlatSchemaStore(schemas)
  const schemaInput = new JSONSchemaInput(store)

  for (const { name, schema } of schemas) {
    await schemaInput.addSource({ name, schema })
  }

  const inputData = new InputData()
  inputData.addInput(schemaInput)

  const result = await quicktype({
    inputData,
    lang: language,
    rendererOptions,
  })

  return result.lines
}

// Generate Swift crypto labels
function generateSwiftCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'import Foundation',
    '',
    '/// Cryptographic domain separation labels for all llamenos crypto operations.',
    '/// Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    '/// uses a unique context string from this enum.',
    'enum CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    static let ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

// Generate Kotlin crypto labels
function generateKotlinCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'package org.llamenos.protocol',
    '',
    '/**',
    ' * Cryptographic domain separation labels for all llamenos crypto operations.',
    ' * Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    ' * uses a unique context string from this object.',
    ' */',
    'object CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    const val ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

/**
 * Strip quicktype convenience initializer extensions from Swift output,
 * keeping only struct/enum/class/typealias definitions with CodingKeys.
 * Also adds Sendable conformance alongside Codable.
 */
function stripSwiftConvenienceExtensions(lines: string[]): string {
  const result: string[] = []
  let skipDepth = 0  // brace depth when skipping a block
  let isSkipping = false

  for (const line of lines) {
    // Detect start of blocks to skip:
    // 1. extension blocks (convenience initializers)
    // 2. func newJSONDecoder/newJSONEncoder
    if (!isSkipping) {
      if (/^extension\b/.test(line) && /\{/.test(line)) {
        isSkipping = true
        skipDepth = 0
        for (const ch of line) {
          if (ch === '{') skipDepth++
          if (ch === '}') skipDepth--
        }
        if (skipDepth <= 0) isSkipping = false
        continue
      }
      if (/^func newJSON/.test(line) || /^\s+func newJSON/.test(line)) {
        isSkipping = true
        skipDepth = 0
        for (const ch of line) {
          if (ch === '{') skipDepth++
          if (ch === '}') skipDepth--
        }
        if (skipDepth <= 0) isSkipping = false
        continue
      }
    }

    // Track braces inside skipped blocks
    if (isSkipping) {
      for (const ch of line) {
        if (ch === '{') skipDepth++
        if (ch === '}') skipDepth--
      }
      if (skipDepth <= 0) isSkipping = false
      continue
    }

    // Skip standalone "// MARK: ... convenience initializers" comments
    if (/convenience initializers/.test(line)) continue
    // Skip "// MARK: - Helper functions for creating encoders and decoders"
    if (/Helper functions for creating/.test(line)) continue
    // Skip "// MARK: - Encode/decode helpers"
    if (/Encode\/decode helpers/.test(line)) continue
    // Skip orphaned decoder/encoder body lines (from stripped func declarations)
    if (/^\s+let (decoder|encoder) = JSON(De|En)coder\(\)/.test(line)) continue
    if (/^\s+if #available/.test(line) && /(dateDecod|dateEncod)/.test(line)) continue
    if (/^\s+(decoder|encoder)\.(date(De|En)codingStrategy)/.test(line)) continue
    if (/^\s+return (decoder|encoder)/.test(line)) continue

    result.push(line)
  }

  // Add Sendable to Codable structs and enums
  let output = result.join('\n')
  output = output.replace(/^(struct \w+): Codable \{/gm, '$1: Codable, Sendable {')
  output = output.replace(/^(enum \w+: String), Codable \{/gm, '$1, Codable, Sendable {')

  // Rename generated types that shadow Swift built-ins, SwiftUI types, or UniFFI types.
  // Each rename must cover the type declaration, MARK comment, and all property type references.

  // `Error` shadows Swift's Error protocol — rename to InviteError.
  output = output.replace(/^enum Error: String/gm, 'enum InviteError: String')
  output = output.replace(/\blet error: Error\?/g, 'let error: InviteError?')

  // `KeyEnvelope` conflicts with UniFFI's KeyEnvelope — rename to ProtocolKeyEnvelope.
  output = output.replace(/\bKeyEnvelope\b/g, 'ProtocolKeyEnvelope')

  // `Group` shadows SwiftUI's Group view — rename to AffinityGroupElement.
  output = output.replace(/^(struct |\/\/ MARK: - )Group\b/gm, '$1AffinityGroupElement')
  output = output.replace(/\blet groups: \[Group\]/g, 'let groups: [AffinityGroupElement]')

  // `Event` is too generic and shadows NSEvent — rename to ProtocolEvent.
  output = output.replace(/^(struct |\/\/ MARK: - )Event:/gm, '$1ProtocolEvent:')
  output = output.replace(/^(struct |\/\/ MARK: - )Event\b(?! *[A-Z])/gm, '$1ProtocolEvent')

  // `Record` is too generic (CoreData, etc.) — rename to CaseLinkRecord.
  // Only rename standalone `Record` type, not types that start with Record (e.g., RecordNotesEnvelope).
  output = output.replace(/^(struct |\/\/ MARK: - )Record:/gm, '$1CaseLinkRecord:')
  output = output.replace(/^(struct |\/\/ MARK: - )Record\b(?! *[A-Z])/gm, '$1CaseLinkRecord')
  output = output.replace(/\blet records: \[Record\]/g, 'let records: [CaseLinkRecord]')

  // `Report` is too generic — rename to CaseLinkReport (used in report-case link context).
  // Only rename standalone `Report` type, not types that start with Report (e.g., ReportResponse).
  output = output.replace(/^(struct |\/\/ MARK: - )Report:/gm, '$1CaseLinkReport:')
  output = output.replace(/^(struct |\/\/ MARK: - )Report\b(?! *[A-Z])/gm, '$1CaseLinkReport')
  output = output.replace(/\blet reports: \[Report\]/g, 'let reports: [CaseLinkReport]')

  // `Location` shadows CoreLocation types — rename to EventLocation.
  output = output.replace(/^(struct |\/\/ MARK: - )Location:/gm, '$1EventLocation:')
  output = output.replace(/^(struct |\/\/ MARK: - )Location\b(?! *[A-Z])/gm, '$1EventLocation')
  output = output.replace(/\blet location: Location\?/g, 'let location: EventLocation?')

  // `Value` shadows Swift generic Value type parameter — rename to FieldValue.
  output = output.replace(/^(enum |\/\/ MARK: - )Value:/gm, '$1FieldValue:')
  output = output.replace(/^(enum |\/\/ MARK: - )Value\b(?! *[A-Z])/gm, '$1FieldValue')
  output = output.replace(/\bValue\.self\b/g, 'FieldValue.self')
  output = output.replace(/\blet defaultValue: Value\?/g, 'let defaultValue: FieldValue?')
  output = output.replace(/\blet value: Value\?/g, 'let value: FieldValue?')

  // `Detail` is too generic — rename to ErrorDetail (used inside ErrorResponse).
  output = output.replace(/^(struct |\/\/ MARK: - )Detail:/gm, '$1ErrorDetail:')
  output = output.replace(/^(struct |\/\/ MARK: - )Detail\b(?! *[A-Z])/gm, '$1ErrorDetail')
  output = output.replace(/\blet details: \[Detail\]\?/g, 'let details: [ErrorDetail]?')

  // `Category` shadows ObjC concept and would collide with iOS app's ReportCategory —
  // rename to ReportTypeCategory.
  output = output.replace(/^(enum |\/\/ MARK: - )Category:/gm, '$1ReportTypeCategory:')
  output = output.replace(/^(enum |\/\/ MARK: - )Category\b(?! *[A-Z])/gm, '$1ReportTypeCategory')
  output = output.replace(/\blet category: Category\b/g, 'let category: ReportTypeCategory')

  // `Operator` is near-identical to Swift keyword `operator` — rename to FieldOperator.
  output = output.replace(/^(enum |\/\/ MARK: - )Operator:/gm, '$1FieldOperator:')
  output = output.replace(/^(enum |\/\/ MARK: - )Operator\b(?! *[A-Z])/gm, '$1FieldOperator')
  output = output.replace(/\bshowWhenOperator: Operator\b/g, 'showWhenOperator: FieldOperator')

  // Note: CaseInteraction and EvidenceListResponse are NOT renamed — the iOS app
  // uses the generated types directly (custom duplicates removed from CaseRecord.swift).

  // Clean up consecutive blank lines
  output = output.replace(/\n{3,}/g, '\n\n')

  return output
}

/**
 * Post-process Kotlin output:
 * 1. Replace package name
 * 2. Add default values for required fields that have defaults in JSON Schema.
 *    quicktype generates `val x: Boolean` for required fields with `"default": false`,
 *    but kotlinx.serialization needs `val x: Boolean = false` to deserialize
 *    responses that omit the field (common with Zod `.default()` fields).
 * 3. Add `= emptyList()` for required List<*> fields that have `"default": []`.
 */
function postProcessKotlin(
  raw: string,
  schemas: Array<{ name: string; schema: string }>,
): string {
  let output = raw.replace('package quicktype', 'package org.llamenos.protocol')

  // Build a map of schema defaults: { TypeName: { fieldName: defaultValue } }
  const defaultsMap = new Map<string, Map<string, unknown>>()
  for (const { name, schema } of schemas) {
    try {
      const parsed = JSON.parse(schema)
      if (parsed.properties && parsed.required) {
        // Convert schema name to PascalCase type name (e.g., 'entityTypeDefinitionSchema' → 'EntityTypeDefinition')
        const typeName = name
          .replace(/Schema$/, '')
          .replace(/(^|_)(\w)/g, (_, _prefix, ch) => ch.toUpperCase())
        const fieldDefaults = new Map<string, unknown>()
        for (const [prop, def] of Object.entries(parsed.properties)) {
          const propDef = def as { default?: unknown }
          if (propDef.default !== undefined && parsed.required.includes(prop)) {
            fieldDefaults.set(prop, propDef.default)
          }
        }
        if (fieldDefaults.size > 0) {
          defaultsMap.set(typeName, fieldDefaults)
        }
      }
    } catch { /* skip non-JSON schemas */ }
  }

  // Apply defaults to Kotlin data class fields.
  // Match patterns like:
  //   val fieldName: Boolean,       → val fieldName: Boolean = false,
  //   val fieldName: Long,          → val fieldName: Long = 0,
  //   val fieldName: String,        → val fieldName: String = "",
  //   val fieldName: List<...>,     → val fieldName: List<...> = emptyList(),
  // Only within data class bodies for types that have defaults.

  // Build a map of enum types → { serialName: variant } for enum default injection
  const enumVariantMap = new Map<string, Map<string, string>>()
  const enumRegex = /^enum class (\w+)\(val value: String\) \{$/gm
  const variantRegex = /@SerialName\("(.+?)"\)\s+(\w+)\(".*?"\)/g
  let enumMatch: RegExpExecArray | null
  while ((enumMatch = enumRegex.exec(output)) !== null) {
    const enumName = enumMatch[1]
    const enumBlock = output.slice(enumMatch.index, output.indexOf('}', enumMatch.index + 1) + 1)
    const variants = new Map<string, string>()
    let varMatch: RegExpExecArray | null
    while ((varMatch = variantRegex.exec(enumBlock)) !== null) {
      variants.set(varMatch[1], varMatch[2]) // e.g., "case" → "Case"
    }
    enumVariantMap.set(enumName, variants)
  }

  // Build @SerialName → fieldName mapping for fields with renamed properties (e.g., hubId → hubID)
  let currentType: string | null = null
  let serialNameMap = new Map<string, string>() // serialName → fieldName for current class
  const lines = output.split('\n')
  const result: string[] = []

  // First pass: collect @SerialName mappings per class
  const classSerialNames = new Map<string, Map<string, string>>()
  let curClass: string | null = null
  let pendingSerialName: string | null = null
  for (const line of lines) {
    const classMatch = line.match(/^data class (\w+)\s*\(/)
    if (classMatch) curClass = classMatch[1]
    if (line.trim() === ')' || line.trim() === ') {') curClass = null

    if (curClass) {
      const snMatch = line.match(/@SerialName\("(.+?)"\)/)
      if (snMatch) {
        pendingSerialName = snMatch[1]
      } else if (pendingSerialName) {
        const fMatch = line.match(/^\s+val (\w+):/)
        if (fMatch) {
          if (!classSerialNames.has(curClass)) classSerialNames.set(curClass, new Map())
          classSerialNames.get(curClass)!.set(fMatch[1], pendingSerialName) // hubID → hubId
        }
        pendingSerialName = null
      }
    }
  }

  // Second pass: inject defaults
  currentType = null
  for (const line of lines) {
    // Track which data class we're inside
    const classMatch = line.match(/^data class (\w+)\s*\(/)
    if (classMatch) {
      currentType = classMatch[1]
      serialNameMap = classSerialNames.get(currentType) ?? new Map()
    }
    if (line.trim() === ')' || line.trim() === ') {') {
      currentType = null
    }

    // Check if this line is a field declaration that needs a default
    if (currentType && defaultsMap.has(currentType)) {
      const defaults = defaultsMap.get(currentType)!
      // Match: val fieldName: Type,  OR  val fieldName: Type
      const fieldMatch = line.match(/^(\s+val )(\w+)(: .+?)(,?\s*)$/)
      if (fieldMatch) {
        const [, prefix, fieldName, typeDecl, suffix] = fieldMatch
        // Look up default using: fieldName, snake_case(fieldName), or @SerialName mapping
        const jsonPropName = serialNameMap.get(fieldName) // e.g., hubID → hubId
        const defaultVal = defaults.get(fieldName)
          ?? defaults.get(fieldName.replace(/[A-Z]/g, m => '_' + m.toLowerCase()))
          ?? (jsonPropName ? defaults.get(jsonPropName) : undefined)
        if (defaultVal !== undefined && !typeDecl.includes('=')) {
          // Determine the Kotlin default expression
          let kotlinDefault: string | undefined
          if (typeof defaultVal === 'boolean') {
            kotlinDefault = String(defaultVal)
          } else if (typeof defaultVal === 'number') {
            kotlinDefault = typeDecl.includes('Long') ? `${defaultVal}L` : String(defaultVal)
          } else if (typeof defaultVal === 'string') {
            const typeOnly = typeDecl.replace(/^:\s*/, '').replace(/[,\s].*$/, '')
            if (typeOnly === 'String' || typeOnly === 'String?') {
              kotlinDefault = `"${defaultVal}"`
            } else {
              // Try to map string default to enum variant
              const variants = enumVariantMap.get(typeOnly)
              if (variants?.has(defaultVal)) {
                kotlinDefault = `${typeOnly}.${variants.get(defaultVal)}`
              }
              // else: skip — can't inject default for unknown types
            }
          } else if (Array.isArray(defaultVal) && defaultVal.length === 0) {
            kotlinDefault = 'emptyList()'
          }
          if (kotlinDefault !== undefined) {
            result.push(`${prefix}${fieldName}${typeDecl} = ${kotlinDefault}${suffix}`)
            continue
          }
        }
      }
    }

    result.push(line)
  }

  return result.join('\n')
}

async function main() {
  // Build schema registry from Zod schemas
  const registry = getSchemaRegistry()
  console.log(`Found ${registry.length} schemas from Zod registry`)

  // Convert registry entries to JSON strings for quicktype
  const allSchemas = registry.map(({ name, jsonSchema }) => ({
    name,
    schema: JSON.stringify(stripAdditionalProperties(jsonSchema)),
  }))

  // Read crypto labels
  const cryptoLabelsData = JSON.parse(readFileSync(CRYPTO_LABELS_FILE, 'utf-8'))
  const cryptoLabels = cryptoLabelsData.labels as Record<string, string>
  console.log(`Found ${Object.keys(cryptoLabels).length} crypto labels`)

  // Generate for Swift and Kotlin (TypeScript consumers use z.infer<> directly)
  const [swiftLines, kotlinLines] = await Promise.all([
    generateForLanguage('swift', allSchemas, {
      'struct-or-class': 'struct',
      'swift-5-support': 'true',
      density: 'dense',
      'access-level': 'internal',
    }),
    generateForLanguage('kotlin', allSchemas, {
      'just-types': 'true',
      framework: 'kotlinx',
    }),
  ])

  const header = '// Auto-generated by packages/protocol/tools/codegen.ts\n// Do not edit manually.\n\n'

  // Post-process Swift: strip convenience initializer extensions, keep only types + CodingKeys.
  // Also add Sendable conformance to all generated structs and enums.
  const swiftContent = header + stripSwiftConvenienceExtensions(swiftLines) + '\n'
  const kotlinContent = header + postProcessKotlin(kotlinLines.join('\n'), allSchemas) + '\n'

  const swiftCryptoContent = generateSwiftCryptoLabels(cryptoLabels)
  const kotlinCryptoContent = generateKotlinCryptoLabels(cryptoLabels)

  // Write generated files
  for (const dir of ['swift', 'kotlin']) {
    mkdirSync(join(GENERATED_DIR, dir), { recursive: true })
  }

  writeFileSync(join(GENERATED_DIR, 'swift', 'Types.swift'), swiftContent)
  writeFileSync(join(GENERATED_DIR, 'swift', 'CryptoLabels.swift'), swiftCryptoContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'Types.kt'), kotlinContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'CryptoLabels.kt'), kotlinCryptoContent)

  console.log('Generated:')
  console.log('  swift/Types.swift + CryptoLabels.swift')
  console.log('  kotlin/Types.kt + CryptoLabels.kt')
}

main()
