#!/usr/bin/env bun
/**
 * Protocol codegen tool.
 *
 * Generates TypeScript interfaces, Swift structs, and Kotlin data classes
 * from Zod schemas (via toJSONSchema()) defined in apps/worker/schemas/.
 * Also generates crypto label constants.
 *
 * Usage:
 *   bun run codegen           # Generate all platform types
 */

import {
  quicktype,
  InputData,
  JSONSchemaInput,
  JSONSchemaStore,
  type LanguageName,
} from 'quicktype-core'
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { getSchemaRegistry } from './schema-registry'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const GENERATED_DIR = resolve(__dirname, '../generated')
const CRYPTO_LABELS_FILE = resolve(__dirname, '../crypto-labels.json')

// No-op schema store — all schemas are self-contained (no $ref across files)
class InlineSchemaStore extends JSONSchemaStore {
  async fetch(_address: string) {
    return undefined
  }
}

// Generate types for a target language from all schemas
async function generateForLanguage(
  language: LanguageName,
  schemas: Array<{ name: string; schema: string }>,
  rendererOptions: Record<string, string> = {},
): Promise<string[]> {
  const store = new InlineSchemaStore()
  const schemaInput = new JSONSchemaInput(store)

  for (const { name, schema } of schemas) {
    await schemaInput.addSource({ name, schema })
  }

  const inputData = new InputData()
  inputData.addInput(schemaInput)

  const result = await quicktype({
    inputData,
    lang: language,
    rendererOptions,
  })

  return result.lines
}

// Generate Swift crypto labels
function generateSwiftCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'import Foundation',
    '',
    '/// Cryptographic domain separation labels for all llamenos crypto operations.',
    '/// Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    '/// uses a unique context string from this enum.',
    'enum CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    static let ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

// Generate Kotlin crypto labels
function generateKotlinCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
    'package org.llamenos.protocol',
    '',
    '/**',
    ' * Cryptographic domain separation labels for all llamenos crypto operations.',
    ' * Every ECIES derivation, HKDF context, HMAC key, and Schnorr signature binding',
    ' * uses a unique context string from this object.',
    ' */',
    'object CryptoLabels {',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`    const val ${name} = "${value}"`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

// Generate TypeScript crypto labels
function generateTSCryptoLabels(labels: Record<string, string>): string {
  const lines = [
    '// Auto-generated by packages/protocol/tools/codegen.ts',
    '// Do not edit manually.',
    '',
  ]
  for (const [name, value] of Object.entries(labels)) {
    lines.push(`export const ${name} = '${value}'`)
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Strip quicktype convenience initializer extensions from Swift output,
 * keeping only struct/enum/class/typealias definitions with CodingKeys.
 * Also adds Sendable conformance alongside Codable.
 */
function stripSwiftConvenienceExtensions(lines: string[]): string {
  const result: string[] = []
  let skipDepth = 0  // brace depth when skipping a block
  let isSkipping = false

  for (const line of lines) {
    // Detect start of blocks to skip:
    // 1. extension blocks (convenience initializers)
    // 2. func newJSONDecoder/newJSONEncoder
    if (!isSkipping) {
      if (/^extension\b/.test(line) && /\{/.test(line)) {
        isSkipping = true
        skipDepth = 0
        for (const ch of line) {
          if (ch === '{') skipDepth++
          if (ch === '}') skipDepth--
        }
        if (skipDepth <= 0) isSkipping = false
        continue
      }
      if (/^func newJSON/.test(line) || /^\s+func newJSON/.test(line)) {
        isSkipping = true
        skipDepth = 0
        for (const ch of line) {
          if (ch === '{') skipDepth++
          if (ch === '}') skipDepth--
        }
        if (skipDepth <= 0) isSkipping = false
        continue
      }
    }

    // Track braces inside skipped blocks
    if (isSkipping) {
      for (const ch of line) {
        if (ch === '{') skipDepth++
        if (ch === '}') skipDepth--
      }
      if (skipDepth <= 0) isSkipping = false
      continue
    }

    // Skip standalone "// MARK: ... convenience initializers" comments
    if (/convenience initializers/.test(line)) continue
    // Skip "// MARK: - Helper functions for creating encoders and decoders"
    if (/Helper functions for creating/.test(line)) continue
    // Skip "// MARK: - Encode/decode helpers"
    if (/Encode\/decode helpers/.test(line)) continue
    // Skip orphaned decoder/encoder body lines (from stripped func declarations)
    if (/^\s+let (decoder|encoder) = JSON(De|En)coder\(\)/.test(line)) continue
    if (/^\s+if #available/.test(line) && /(dateDecod|dateEncod)/.test(line)) continue
    if (/^\s+(decoder|encoder)\.(date(De|En)codingStrategy)/.test(line)) continue
    if (/^\s+return (decoder|encoder)/.test(line)) continue

    result.push(line)
  }

  // Add Sendable to Codable structs and enums
  let output = result.join('\n')
  output = output.replace(/^(struct \w+): Codable \{/gm, '$1: Codable, Sendable {')
  output = output.replace(/^(enum \w+: String), Codable \{/gm, '$1, Codable, Sendable {')

  // Clean up consecutive blank lines
  output = output.replace(/\n{3,}/g, '\n\n')

  return output
}

async function main() {
  // Build schema registry from Zod schemas
  const registry = getSchemaRegistry()
  console.log(`Found ${registry.length} schemas from Zod registry`)

  // Convert registry entries to JSON strings for quicktype
  const allSchemas = registry.map(({ name, jsonSchema }) => ({
    name,
    schema: JSON.stringify(jsonSchema),
  }))

  // Read crypto labels
  const cryptoLabelsData = JSON.parse(readFileSync(CRYPTO_LABELS_FILE, 'utf-8'))
  const cryptoLabels = cryptoLabelsData.labels as Record<string, string>
  console.log(`Found ${Object.keys(cryptoLabels).length} crypto labels`)

  // Generate for all three languages
  const [tsLines, swiftLines, kotlinLines] = await Promise.all([
    generateForLanguage('typescript', allSchemas, {
      'just-types': 'true',
    }),
    generateForLanguage('swift', allSchemas, {
      'struct-or-class': 'struct',
      'swift-5-support': 'true',
      density: 'dense',
      'access-level': 'internal',
    }),
    generateForLanguage('kotlin', allSchemas, {
      'just-types': 'true',
      framework: 'kotlinx',
    }),
  ])

  const header = '// Auto-generated by packages/protocol/tools/codegen.ts\n// Do not edit manually.\n\n'

  const tsContent = header + tsLines.join('\n') + '\n'
  // Post-process Swift: strip convenience initializer extensions, keep only types + CodingKeys.
  // Also add Sendable conformance to all generated structs and enums.
  const swiftContent = header + stripSwiftConvenienceExtensions(swiftLines) + '\n'
  const kotlinContent = header + kotlinLines.join('\n').replace(
    'package quicktype',
    'package org.llamenos.protocol',
  ) + '\n'

  const tsCryptoContent = generateTSCryptoLabels(cryptoLabels)
  const swiftCryptoContent = generateSwiftCryptoLabels(cryptoLabels)
  const kotlinCryptoContent = generateKotlinCryptoLabels(cryptoLabels)

  // Write generated files
  for (const dir of ['typescript', 'swift', 'kotlin']) {
    mkdirSync(join(GENERATED_DIR, dir), { recursive: true })
  }

  writeFileSync(join(GENERATED_DIR, 'typescript', 'types.ts'), tsContent)
  writeFileSync(join(GENERATED_DIR, 'typescript', 'crypto-labels.ts'), tsCryptoContent)
  writeFileSync(join(GENERATED_DIR, 'swift', 'Types.swift'), swiftContent)
  writeFileSync(join(GENERATED_DIR, 'swift', 'CryptoLabels.swift'), swiftCryptoContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'Types.kt'), kotlinContent)
  writeFileSync(join(GENERATED_DIR, 'kotlin', 'CryptoLabels.kt'), kotlinCryptoContent)

  console.log('Generated:')
  console.log('  typescript/types.ts + crypto-labels.ts')
  console.log('  swift/Types.swift + CryptoLabels.swift')
  console.log('  kotlin/Types.kt + CryptoLabels.kt')
}

main()
