all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    llamenos_servers:
      hosts:
        vps1:
          ansible_host: 195.246.230.104
          # Primary: try root on port 22 (default)
          # Fallback: if hardening was applied, use deploy on port 2222
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/riseup
          ansible_port: 22
    llamenos_app:
      hosts:
        vps1: {}
    llamenos_db:
      hosts:
        vps1: {}
    llamenos_proxy:
      hosts:
        vps1: {}
    llamenos_storage:
      hosts:
        vps1: {}
    llamenos_relay:
      hosts:
        vps1: {}
