import Foundation

// All call response types (ActiveCallsResponse, CallHistoryResponse, SharedCall)
// are generated by protocol codegen. See packages/protocol/schemas/calls.ts.
//
// Hand-written types removed to avoid "invalid redeclaration" build errors
// when codegen outputs the same type names.
