/**
 * Cross-platform crypto interop test.
 *
 * Verifies that the JavaScript crypto implementation (FFI to Rust llamenos-core)
 * produces output compatible with the Rust implementation by consuming test
 * vectors generated by `llamenos-core/tests/interop.rs`.
 *
 * Run the Rust test first to generate vectors:
 *   cd packages/crypto && cargo test --test interop
 *
 * Then run this test:
 *   bun run test -- tests/crypto-interop.spec.ts
 */

import { test, expect } from '@playwright/test'
import { readFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import {
  sha256,
  symmetricDecrypt,
  hpkeOpen,
  ed25519Verify,
  hkdfSha256,
} from '@llamenos/crypto/ffi'
import { bytesToHex, hexToBytes, utf8ToBytes } from '@shared/encoding'
import { x25519 } from '@noble/curves/ed25519.js'
import * as labels from '../packages/shared/crypto-labels'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const VECTORS_PATH = resolve(__dirname, '../packages/crypto/tests/fixtures/test-vectors.json')

// Skip if test vectors haven't been generated yet
const hasVectors = existsSync(VECTORS_PATH)
const vectors = hasVectors ? JSON.parse(readFileSync(VECTORS_PATH, 'utf-8')) : null

test.describe('Cross-platform crypto interop', () => {
  test.skip(!hasVectors, 'Test vectors not found — run: cd packages/crypto && cargo test --test interop')

  test('label constants match Rust', () => {
    const rustLabels = vectors.labels

    expect(labels.LABEL_NOTE_KEY).toBe(rustLabels.labelNoteKey)
    expect(labels.LABEL_FILE_KEY).toBe(rustLabels.labelFileKey)
    expect(labels.LABEL_FILE_METADATA).toBe(rustLabels.labelFileMetadata)
    expect(labels.LABEL_HUB_KEY_WRAP).toBe(rustLabels.labelHubKeyWrap)
    expect(labels.LABEL_TRANSCRIPTION).toBe(rustLabels.labelTranscription)
    expect(labels.LABEL_MESSAGE).toBe(rustLabels.labelMessage)
    expect(labels.LABEL_CALL_META).toBe(rustLabels.labelCallMeta)
    expect(labels.LABEL_SHIFT_SCHEDULE).toBe(rustLabels.labelShiftSchedule)
    expect(labels.HKDF_SALT).toBe(rustLabels.hkdfSalt)
    expect(labels.HKDF_CONTEXT_NOTES).toBe(rustLabels.hkdfContextNotes)
    expect(labels.HKDF_CONTEXT_DRAFTS).toBe(rustLabels.hkdfContextDrafts)
    expect(labels.HKDF_CONTEXT_EXPORT).toBe(rustLabels.hkdfContextExport)
    expect(labels.LABEL_HUB_EVENT).toBe(rustLabels.labelHubEvent)
    expect(labels.LABEL_DEVICE_PROVISION).toBe(rustLabels.labelDeviceProvision)
    expect(labels.SAS_SALT).toBe(rustLabels.sasSalt)
    expect(labels.SAS_INFO).toBe(rustLabels.sasInfo)
    expect(labels.AUTH_PREFIX).toBe(rustLabels.authPrefix)
    expect(labels.HMAC_PHONE_PREFIX).toBe(rustLabels.hmacPhonePrefix)
    expect(labels.HMAC_IP_PREFIX).toBe(rustLabels.hmacIpPrefix)
    expect(labels.HMAC_KEYID_PREFIX).toBe(rustLabels.hmacKeyidPrefix)
    expect(labels.HMAC_SUBSCRIBER).toBe(rustLabels.hmacSubscriber)
    expect(labels.HMAC_PREFERENCE_TOKEN).toBe(rustLabels.hmacPreferenceToken)
    expect(labels.RECOVERY_SALT).toBe(rustLabels.recoverySalt)
    expect(labels.LABEL_BACKUP).toBe(rustLabels.labelBackup)
    expect(labels.LABEL_PUSH_WAKE).toBe(rustLabels.labelPushWake)
    expect(labels.LABEL_PUSH_FULL).toBe(rustLabels.labelPushFull)
  })

  test('JS derives same X25519 pubkey from test secret key', () => {
    const secretKeyHex = vectors.keys.secretKeyHex
    const expectedPubkey = vectors.keys.x25519PubkeyHex

    // X25519 public key derivation — uses top-level ESM import of @noble/curves
    const pubkey = x25519.getPublicKey(hexToBytes(secretKeyHex))
    expect(bytesToHex(pubkey)).toBe(expectedPubkey)
  })

  test('JS derives same admin X25519 pubkey', () => {
    const secretKeyHex = vectors.keys.adminSecretKeyHex
    const expectedPubkey = vectors.keys.adminX25519PubkeyHex

    // X25519 pubkey derivation — uses top-level ESM import of @noble/curves
    const pubkey = x25519.getPublicKey(hexToBytes(secretKeyHex))
    expect(bytesToHex(pubkey)).toBe(expectedPubkey)
  })

  test('JS can unwrap HPKE envelope produced by Rust', () => {
    const { envelope, originalKeyHex, label } = vectors.hpke
    const adminSecretKey = vectors.keys.adminSecretKeyHex

    const decrypted = hpkeUnwrap(envelope, adminSecretKey, label)
    expect(bytesToHex(decrypted)).toBe(originalKeyHex)
  })

  test('JS can decrypt note produced by Rust (author key)', () => {
    const { encrypted, plaintextJson } = vectors.noteEncryption
    const authorSecretKey = vectors.keys.secretKeyHex

    const noteKey = hpkeUnwrap(encrypted.authorEnvelope, authorSecretKey, labels.LABEL_NOTE_KEY)
    const decoded = decryptContent(encrypted.encryptedContent, noteKey, labels.LABEL_NOTE_KEY)
    expect(decoded).toBe(plaintextJson)
  })

  test('JS can decrypt note produced by Rust (admin key)', () => {
    const { encrypted, plaintextJson } = vectors.noteEncryption
    const adminSecretKey = vectors.keys.adminSecretKeyHex
    const adminPubkey = vectors.keys.adminX25519PubkeyHex

    const adminEnvelope = encrypted.adminEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === adminPubkey,
    )
    expect(adminEnvelope).toBeDefined()

    const noteKey = hpkeUnwrap(adminEnvelope, adminSecretKey, labels.LABEL_NOTE_KEY)
    const decoded = decryptContent(encrypted.encryptedContent, noteKey, labels.LABEL_NOTE_KEY)
    expect(decoded).toBe(plaintextJson)
  })

  test('JS can verify auth token produced by Rust', () => {
    const { token, method, path } = vectors.auth

    // Reconstruct the Ed25519 auth message: LABEL_DEVICE_AUTH:pubkey:timestamp:method:path
    // Signed as raw UTF-8 bytes (no SHA-256 pre-hash) — matches Rust build_auth_message()
    const message = `${labels.LABEL_DEVICE_AUTH}:${token.pubkey}:${token.timestamp}:${method}:${path}`

    // Verify Ed25519 signature via FFI (signs raw message bytes, not a hash)
    const valid = ed25519Verify(
      hexToBytes(token.pubkey),
      utf8ToBytes(message),
      hexToBytes(token.token),
    )
    expect(valid).toBe(true)
  })

  test('JS can decrypt draft produced by Rust', () => {
    const { encryptedHex, secretKeyHex, plaintext } = vectors.draftEncryption

    // Draft encryption uses HKDF-derived key from the secret key
    const hkdfKey = hkdfSha256(
      hexToBytes(secretKeyHex),
      utf8ToBytes(labels.HKDF_SALT),
      utf8ToBytes(labels.HKDF_CONTEXT_DRAFTS),
      32,
    )

    // Parse: nonce(12) + ciphertext + tag(16) — pass entire packed blob to symmetricDecrypt
    const packed = hexToBytes(encryptedHex)
    const aad = utf8ToBytes(labels.HKDF_CONTEXT_DRAFTS)
    const decrypted = symmetricDecrypt(hkdfKey, packed, aad)
    const decoded = new TextDecoder().decode(decrypted)

    expect(decoded).toBe(plaintext)
  })

  test('PIN encryption structure matches expected format', () => {
    const { encrypted, pin } = vectors.pinEncryption

    // Validate structure (don't decrypt — Argon2id is too slow in Playwright)
    expect(encrypted.salt).toHaveLength(64) // 32 bytes hex
    expect(encrypted.nonce).toHaveLength(24) // 12 bytes hex (AES-256-GCM)
    expect(encrypted.ciphertext).toBeTruthy()
    expect(encrypted.pubkey).toBeTruthy()
    expect(pin).toBe('12345678')
  })

  // ─── v3 Tests (HPKE + AES-256-GCM) ────────────────────────────

  test('JS can decrypt message produced by Rust (volunteer)', () => {
    const { encrypted, plaintext } = vectors.messageEncryption
    const volSecretKey = vectors.keys.secretKeyHex
    const volPubkey = vectors.keys.x25519PubkeyHex

    // Find volunteer's envelope
    const volEnvelope = encrypted.readerEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === volPubkey,
    )
    expect(volEnvelope).toBeDefined()

    // Unwrap message key via HPKE with LABEL_MESSAGE
    const msgKey = hpkeUnwrap(volEnvelope, volSecretKey, labels.LABEL_MESSAGE)

    // Decrypt content
    const decoded = decryptContent(encrypted.encryptedContent, msgKey, labels.LABEL_MESSAGE)
    expect(decoded).toBe(plaintext)
  })

  test('JS can decrypt message produced by Rust (admin)', () => {
    const { encrypted, plaintext } = vectors.messageEncryption
    const adminSecretKey = vectors.keys.adminSecretKeyHex
    const adminPubkey = vectors.keys.adminX25519PubkeyHex

    const adminEnvelope = encrypted.readerEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === adminPubkey,
    )
    expect(adminEnvelope).toBeDefined()

    const msgKey = hpkeUnwrap(adminEnvelope, adminSecretKey, labels.LABEL_MESSAGE)
    const decoded = decryptContent(encrypted.encryptedContent, msgKey, labels.LABEL_MESSAGE)
    expect(decoded).toBe(plaintext)
  })

  test('JS can unwrap hub key produced by Rust', () => {
    const { hubKeyHex, wrappedEnvelopes, label } = vectors.hubKey
    const volSecretKey = vectors.keys.secretKeyHex

    // Unwrap first envelope (volunteer)
    const unwrapped = hpkeUnwrap(wrappedEnvelopes[0], volSecretKey, label)
    expect(bytesToHex(unwrapped)).toBe(hubKeyHex)

    // Unwrap second envelope (admin)
    const adminUnwrapped = hpkeUnwrap(
      wrappedEnvelopes[1],
      vectors.keys.adminSecretKeyHex,
      label,
    )
    expect(bytesToHex(adminUnwrapped)).toBe(hubKeyHex)
  })

  test('JS can verify Ed25519-signed event produced by Rust', () => {
    const { event, canonicalJson } = vectors.nostrEvent

    // Recompute event ID from canonical JSON
    const computedId = bytesToHex(sha256(utf8ToBytes(canonicalJson)))
    expect(computedId).toBe(event.id)

    // Verify Ed25519 signature over the event ID hash
    const idHash = sha256(hexToBytes(event.id))
    const valid = ed25519Verify(
      hexToBytes(event.pubkey),
      idHash,
      hexToBytes(event.sig),
    )
    expect(valid).toBe(true)

    // Verify canonical JSON structure matches NIP-01
    const parsed = JSON.parse(canonicalJson)
    expect(parsed[0]).toBe(0)
    expect(parsed[1]).toBe(event.pubkey)
    expect(parsed[2]).toBe(event.createdAt)
    expect(parsed[3]).toBe(event.kind)
  })

  test('JS can decrypt export produced by Rust', () => {
    const { encryptedBase64, secretKeyHex, plaintextJson } = vectors.exportEncryption

    // Derive key using HKDF with HKDF_CONTEXT_EXPORT
    const exportKey = hkdfSha256(
      hexToBytes(secretKeyHex),
      utf8ToBytes(labels.HKDF_SALT),
      utf8ToBytes(labels.HKDF_CONTEXT_EXPORT),
      32,
    )

    // Decode base64 → nonce(12) + ciphertext + tag(16) — pass entire packed blob
    const packed = Uint8Array.from(atob(encryptedBase64), c => c.charCodeAt(0))
    const aad = utf8ToBytes(labels.HKDF_CONTEXT_EXPORT)
    const decrypted = symmetricDecrypt(exportKey, packed, aad)
    const decoded = new TextDecoder().decode(decrypted)

    expect(decoded).toBe(plaintextJson)
  })

  test('JS can decrypt call record produced by Rust (admin)', () => {
    const { encryptedContent, adminEnvelopes, plaintextJson } = vectors.callRecord
    const adminSecretKey = vectors.keys.adminSecretKeyHex
    const adminPubkey = vectors.keys.adminX25519PubkeyHex

    const adminEnvelope = adminEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === adminPubkey,
    )
    expect(adminEnvelope).toBeDefined()

    // Unwrap with LABEL_CALL_META (not LABEL_MESSAGE)
    const recordKey = hpkeUnwrap(adminEnvelope, adminSecretKey, labels.LABEL_CALL_META)
    const decoded = decryptContent(encryptedContent, recordKey, labels.LABEL_CALL_META)
    expect(decoded).toBe(plaintextJson)
  })

  test('Domain separation prevents cross-label unwrap', () => {
    const { wrappedWithNoteLabel, wrappedWithMessageLabel, wrappedWithHubLabel } =
      vectors.domainSeparation
    const adminSecretKey = vectors.keys.adminSecretKeyHex

    // Same-label unwrap succeeds
    expect(() => hpkeUnwrap(wrappedWithNoteLabel, adminSecretKey, labels.LABEL_NOTE_KEY)).not.toThrow()
    expect(() => hpkeUnwrap(wrappedWithMessageLabel, adminSecretKey, labels.LABEL_MESSAGE)).not.toThrow()
    expect(() => hpkeUnwrap(wrappedWithHubLabel, adminSecretKey, labels.LABEL_HUB_KEY_WRAP)).not.toThrow()

    // Cross-label unwrap fails (AEAD verification failure)
    expect(() => hpkeUnwrap(wrappedWithNoteLabel, adminSecretKey, labels.LABEL_MESSAGE)).toThrow()
    expect(() => hpkeUnwrap(wrappedWithMessageLabel, adminSecretKey, labels.LABEL_NOTE_KEY)).toThrow()
    expect(() => hpkeUnwrap(wrappedWithHubLabel, adminSecretKey, labels.LABEL_NOTE_KEY)).toThrow()
  })

  // ─── Adversarial Tests ─────────────────────────────────────

  test('HPKE unwrap with tampered ciphertext throws', () => {
    const { tamperedCt, validEnvelope, validLabel } = vectors.adversarial.hpke
    const adminSecretKey = vectors.keys.adminSecretKeyHex

    const tamperedEnvelope = {
      ct: tamperedCt,
      enc: validEnvelope.enc,
    }
    expect(() => hpkeUnwrap(tamperedEnvelope, adminSecretKey, validLabel)).toThrow()
  })

  test('HPKE unwrap with truncated data throws', () => {
    const { truncatedCt, validEnvelope, validLabel } = vectors.adversarial.hpke
    const adminSecretKey = vectors.keys.adminSecretKeyHex

    const truncatedEnvelope = {
      ct: truncatedCt,
      enc: validEnvelope.enc,
    }
    expect(() => hpkeUnwrap(truncatedEnvelope, adminSecretKey, validLabel)).toThrow()
  })

  test('HPKE unwrap with wrong key throws', () => {
    const { validEnvelope, validLabel } = vectors.adversarial.hpke
    const wrongSecretKey = vectors.keys.wrongSecretKeyHex

    expect(() => hpkeUnwrap(validEnvelope, wrongSecretKey, validLabel)).toThrow()
  })

  test('Note decrypt with tampered content throws', () => {
    const { validEncrypted, tamperedContent } = vectors.adversarial.note
    const authorSecretKey = vectors.keys.secretKeyHex

    // Unwrap the note key (should succeed)
    const noteKey = hpkeUnwrap(
      validEncrypted.authorEnvelope,
      authorSecretKey,
      labels.LABEL_NOTE_KEY,
    )

    // Decrypt tampered content (should fail — AES-256-GCM auth tag mismatch)
    const contentBytes = hexToBytes(tamperedContent)
    const aad = utf8ToBytes(labels.LABEL_NOTE_KEY)

    expect(() => {
      symmetricDecrypt(noteKey, contentBytes, aad)
    }).toThrow()
  })

  test('Auth token with wrong method fails verification', () => {
    const { validToken, validPath, wrongMethod } = vectors.adversarial.auth

    // New format: includes pubkey, raw UTF-8 (no SHA-256 pre-hash)
    const message = `${labels.LABEL_DEVICE_AUTH}:${validToken.pubkey}:${validToken.timestamp}:${wrongMethod}:${validPath}`
    const valid = ed25519Verify(
      hexToBytes(validToken.pubkey),
      utf8ToBytes(message),
      hexToBytes(validToken.token),
    )
    expect(valid).toBe(false)
  })

  test('Auth token with wrong path fails verification', () => {
    const { validToken, validMethod, wrongPath } = vectors.adversarial.auth

    // New format: includes pubkey, raw UTF-8 (no SHA-256 pre-hash)
    const message = `${labels.LABEL_DEVICE_AUTH}:${validToken.pubkey}:${validToken.timestamp}:${validMethod}:${wrongPath}`
    const valid = ed25519Verify(
      hexToBytes(validToken.pubkey),
      utf8ToBytes(message),
      hexToBytes(validToken.token),
    )
    expect(valid).toBe(false)
  })

  test('Message decrypt with wrong reader key fails', () => {
    const { validEncrypted } = vectors.adversarial.message
    const wrongPubkey = vectors.keys.wrongX25519PubkeyHex

    // Wrong key won't be found in envelopes
    const wrongEnvelope = validEncrypted.readerEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === wrongPubkey,
    )
    expect(wrongEnvelope).toBeUndefined()
  })
})

// ─── Helpers ─────────────────────────────────────────────────

/**
 * HPKE unwrap: RFC 9180 DHKEM(X25519, HKDF-SHA256) + HKDF-SHA256 + AES-256-GCM.
 * info = label bytes, aad = "${label}:key-wrap" bytes.
 * Envelope fields: { enc: hex, ct: hex }
 *
 * Concatenates enc + ct into the wire format expected by hpkeOpen:
 * enc(32) || ciphertext || tag(16)
 */
function hpkeUnwrap(
  envelope: { ct: string; enc: string },
  secretKeyHex: string,
  label: string,
): Uint8Array {
  const enc = hexToBytes(envelope.enc)
  const ct = hexToBytes(envelope.ct)
  const info = utf8ToBytes(label)
  const aad = utf8ToBytes(`${label}:key-wrap`)

  // Reconstruct wire format: enc(32) || ciphertext || tag(16)
  const combined = new Uint8Array(enc.length + ct.length)
  combined.set(enc)
  combined.set(ct, enc.length)

  return hpkeOpen(hexToBytes(secretKeyHex), combined, info, aad)
}

/** Decrypt hex(nonce_12 + ciphertext + tag_16) with AES-256-GCM + AAD via FFI */
function decryptContent(encryptedContentHex: string, key: Uint8Array, label: string): string {
  const contentBytes = hexToBytes(encryptedContentHex)
  const aad = utf8ToBytes(label)
  const plaintext = symmetricDecrypt(key, contentBytes, aad)
  return new TextDecoder().decode(plaintext)
}
