/**
 * Cross-platform crypto interop test.
 *
 * Verifies that the JavaScript crypto implementation (@noble/*) produces
 * output compatible with the Rust llamenos-core implementation by consuming
 * test vectors generated by `llamenos-core/tests/interop.rs`.
 *
 * Run the Rust test first to generate vectors:
 *   cd ../llamenos-core && cargo test --test interop
 *
 * Then run this test:
 *   bun run test -- tests/crypto-interop.spec.ts
 */

import { test, expect } from '@playwright/test'
import { readFileSync, existsSync } from 'fs'
import { resolve } from 'path'
import { sha256 } from '@noble/hashes/sha256.js'
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js'
import { bytesToHex, hexToBytes, utf8ToBytes } from '@noble/hashes/utils.js'
import { secp256k1 } from '@noble/curves/secp256k1.js'
import { hkdf } from '@noble/hashes/hkdf.js'
import * as labels from '../src/shared/crypto-labels'

const VECTORS_PATH = resolve(__dirname, '../../llamenos-core/tests/fixtures/test-vectors.json')

// Skip if test vectors haven't been generated yet
const hasVectors = existsSync(VECTORS_PATH)
const vectors = hasVectors ? JSON.parse(readFileSync(VECTORS_PATH, 'utf-8')) : null

test.describe('Cross-platform crypto interop', () => {
  test.skip(!hasVectors, 'Test vectors not found — run: cd ../llamenos-core && cargo test --test interop')

  test('label constants match Rust', () => {
    const rustLabels = vectors.labels

    expect(labels.LABEL_NOTE_KEY).toBe(rustLabels.labelNoteKey)
    expect(labels.LABEL_FILE_KEY).toBe(rustLabels.labelFileKey)
    expect(labels.LABEL_FILE_METADATA).toBe(rustLabels.labelFileMetadata)
    expect(labels.LABEL_HUB_KEY_WRAP).toBe(rustLabels.labelHubKeyWrap)
    expect(labels.LABEL_TRANSCRIPTION).toBe(rustLabels.labelTranscription)
    expect(labels.LABEL_MESSAGE).toBe(rustLabels.labelMessage)
    expect(labels.LABEL_CALL_META).toBe(rustLabels.labelCallMeta)
    expect(labels.LABEL_SHIFT_SCHEDULE).toBe(rustLabels.labelShiftSchedule)
    expect(labels.HKDF_SALT).toBe(rustLabels.hkdfSalt)
    expect(labels.HKDF_CONTEXT_NOTES).toBe(rustLabels.hkdfContextNotes)
    expect(labels.HKDF_CONTEXT_DRAFTS).toBe(rustLabels.hkdfContextDrafts)
    expect(labels.HKDF_CONTEXT_EXPORT).toBe(rustLabels.hkdfContextExport)
    expect(labels.LABEL_HUB_EVENT).toBe(rustLabels.labelHubEvent)
    expect(labels.LABEL_DEVICE_PROVISION).toBe(rustLabels.labelDeviceProvision)
    expect(labels.SAS_SALT).toBe(rustLabels.sasSalt)
    expect(labels.SAS_INFO).toBe(rustLabels.sasInfo)
    expect(labels.AUTH_PREFIX).toBe(rustLabels.authPrefix)
    expect(labels.HMAC_PHONE_PREFIX).toBe(rustLabels.hmacPhonePrefix)
    expect(labels.HMAC_IP_PREFIX).toBe(rustLabels.hmacIpPrefix)
    expect(labels.HMAC_KEYID_PREFIX).toBe(rustLabels.hmacKeyidPrefix)
    expect(labels.HMAC_SUBSCRIBER).toBe(rustLabels.hmacSubscriber)
    expect(labels.HMAC_PREFERENCE_TOKEN).toBe(rustLabels.hmacPreferenceToken)
    expect(labels.RECOVERY_SALT).toBe(rustLabels.recoverySalt)
    expect(labels.LABEL_BACKUP).toBe(rustLabels.labelBackup)
    expect(labels.LABEL_SERVER_NOSTR_KEY).toBe(rustLabels.labelServerNostrKey)
    expect(labels.LABEL_SERVER_NOSTR_KEY_INFO).toBe(rustLabels.labelServerNostrKeyInfo)
    expect(labels.LABEL_PUSH_WAKE).toBe(rustLabels.labelPushWake)
    expect(labels.LABEL_PUSH_FULL).toBe(rustLabels.labelPushFull)
  })

  test('JS derives same pubkey from test secret key', () => {
    const secretKeyHex = vectors.keys.secretKeyHex
    const expectedPubkey = vectors.keys.publicKeyHex

    // Derive x-only pubkey (BIP-340 style)
    const fullPubkey = secp256k1.getPublicKey(secretKeyHex, true) // compressed
    // x-only = drop the 02/03 prefix
    const xOnlyHex = bytesToHex(fullPubkey.slice(1))

    expect(xOnlyHex).toBe(expectedPubkey)
  })

  test('JS derives same admin pubkey', () => {
    const secretKeyHex = vectors.keys.adminSecretKeyHex
    const expectedPubkey = vectors.keys.adminPublicKeyHex

    const fullPubkey = secp256k1.getPublicKey(secretKeyHex, true)
    const xOnlyHex = bytesToHex(fullPubkey.slice(1))

    expect(xOnlyHex).toBe(expectedPubkey)
  })

  test('JS can unwrap ECIES envelope produced by Rust', () => {
    const { envelope, originalKeyHex, label, recipientPubkeyHex } = vectors.ecies
    const adminSecretKey = vectors.keys.adminSecretKeyHex

    // Parse the wrapped key: nonce(24) + ciphertext(48)
    const wrappedBytes = hexToBytes(envelope.wrappedKey)
    const nonce = wrappedBytes.slice(0, 24)
    const ciphertext = wrappedBytes.slice(24)

    // Parse ephemeral pubkey (compressed 33 bytes)
    const ephPubkeyBytes = hexToBytes(envelope.ephemeralPubkey)

    // ECDH: recipientSecret * ephemeralPub → shared point
    const secretKeyBytes = hexToBytes(adminSecretKey)
    const sharedPoint = secp256k1.getSharedSecret(secretKeyBytes, ephPubkeyBytes)
    const sharedX = sharedPoint.slice(1, 33) // x-coordinate only

    // Derive symmetric key: SHA-256(label || sharedX)
    const keyMaterial = new Uint8Array([...utf8ToBytes(label), ...sharedX])
    const symmetricKey = sha256(keyMaterial)

    // Decrypt with XChaCha20-Poly1305
    const cipher = xchacha20poly1305(symmetricKey, nonce)
    const decrypted = cipher.decrypt(ciphertext)

    expect(bytesToHex(decrypted)).toBe(originalKeyHex)
  })

  test('JS can decrypt note produced by Rust (author key)', () => {
    const { encrypted, plaintext_json: plaintextJson } = vectors.noteEncryption
    const authorSecretKey = vectors.keys.secretKeyHex

    // Unwrap the note key from author envelope
    const wrappedBytes = hexToBytes(encrypted.authorEnvelope.wrappedKey)
    const nonce = wrappedBytes.slice(0, 24)
    const envelopeCiphertext = wrappedBytes.slice(24)
    const ephPubkey = hexToBytes(encrypted.authorEnvelope.ephemeralPubkey)

    // ECDH
    const sharedPoint = secp256k1.getSharedSecret(hexToBytes(authorSecretKey), ephPubkey)
    const sharedX = sharedPoint.slice(1, 33)

    // Derive unwrap key
    const keyMaterial = new Uint8Array([...utf8ToBytes(labels.LABEL_NOTE_KEY), ...sharedX])
    const unwrapKey = sha256(keyMaterial)

    // Unwrap note key
    const unwrapCipher = xchacha20poly1305(unwrapKey, nonce)
    const noteKey = unwrapCipher.decrypt(envelopeCiphertext)

    // Decrypt note content
    const contentBytes = hexToBytes(encrypted.encryptedContent)
    const contentNonce = contentBytes.slice(0, 24)
    const contentCiphertext = contentBytes.slice(24)

    const contentCipher = xchacha20poly1305(noteKey, contentNonce)
    const plaintext = contentCipher.decrypt(contentCiphertext)
    const decoded = new TextDecoder().decode(plaintext)

    expect(decoded).toBe(plaintextJson)
  })

  test('JS can decrypt note produced by Rust (admin key)', () => {
    const { encrypted, plaintext_json: plaintextJson } = vectors.noteEncryption
    const adminSecretKey = vectors.keys.adminSecretKeyHex
    const adminPubkey = vectors.keys.adminPublicKeyHex

    // Find admin's envelope
    const adminEnvelope = encrypted.adminEnvelopes.find(
      (e: { pubkey: string }) => e.pubkey === adminPubkey,
    )
    expect(adminEnvelope).toBeDefined()

    // Unwrap the note key
    const wrappedBytes = hexToBytes(adminEnvelope.wrappedKey)
    const nonce = wrappedBytes.slice(0, 24)
    const envelopeCiphertext = wrappedBytes.slice(24)
    const ephPubkey = hexToBytes(adminEnvelope.ephemeralPubkey)

    const sharedPoint = secp256k1.getSharedSecret(hexToBytes(adminSecretKey), ephPubkey)
    const sharedX = sharedPoint.slice(1, 33)

    const keyMaterial = new Uint8Array([...utf8ToBytes(labels.LABEL_NOTE_KEY), ...sharedX])
    const unwrapKey = sha256(keyMaterial)

    const unwrapCipher = xchacha20poly1305(unwrapKey, nonce)
    const noteKey = unwrapCipher.decrypt(envelopeCiphertext)

    // Decrypt note content
    const contentBytes = hexToBytes(encrypted.encryptedContent)
    const contentNonce = contentBytes.slice(0, 24)
    const contentCiphertext = contentBytes.slice(24)

    const contentCipher = xchacha20poly1305(noteKey, contentNonce)
    const plaintext = contentCipher.decrypt(contentCiphertext)
    const decoded = new TextDecoder().decode(plaintext)

    expect(decoded).toBe(plaintextJson)
  })

  test('JS can verify auth token produced by Rust', () => {
    const { token, method, path } = vectors.auth
    const { schnorr } = secp256k1

    // Reconstruct the message
    const message = `${labels.AUTH_PREFIX}${token.pubkey}:${token.timestamp}:${method}:${path}`
    const messageHash = sha256(utf8ToBytes(message))

    // Verify Schnorr signature
    const valid = schnorr.verify(token.token, messageHash, token.pubkey)
    expect(valid).toBe(true)
  })

  test('JS can decrypt draft produced by Rust', () => {
    const { encryptedHex, secretKeyHex, plaintext } = vectors.draftEncryption

    // Draft encryption uses HKDF-derived key from the secret key
    const hkdfKey = hkdf(sha256, hexToBytes(secretKeyHex), labels.HKDF_SALT, labels.HKDF_CONTEXT_DRAFTS, 32)

    // Parse: nonce(24) + ciphertext
    const packed = hexToBytes(encryptedHex)
    const nonce = packed.slice(0, 24)
    const ciphertext = packed.slice(24)

    const cipher = xchacha20poly1305(hkdfKey, nonce)
    const decrypted = cipher.decrypt(ciphertext)
    const decoded = new TextDecoder().decode(decrypted)

    expect(decoded).toBe(plaintext)
  })

  test('PIN encryption structure matches expected format', () => {
    const { encrypted, pin } = vectors.pinEncryption

    // Validate structure (don't decrypt — PBKDF2 is too slow in Playwright)
    expect(encrypted.salt).toHaveLength(32) // 16 bytes hex
    expect(encrypted.nonce).toHaveLength(48) // 24 bytes hex
    expect(encrypted.iterations).toBe(600_000)
    expect(encrypted.ciphertext).toBeTruthy()
    expect(encrypted.pubkey).toBeTruthy()
    expect(pin).toBe('1234')
  })
})
