//! Device key management — Ed25519 signing + X25519 encryption keypairs.
//!
//! Each device generates two independent keypairs on first launch:
//! - Ed25519 for signing (sigchain entries, auth tokens, MLS leaf credentials)
//! - X25519 for encryption (HPKE decapsulation, PUK seed wrapping)
//!
//! Key material is credential-encrypted for storage using Argon2id + AES-256-GCM.
//! Credentials can be numeric PINs (min 8 digits) or alphanumeric passphrases (min 8 chars).
//! The device keypairs are NEVER exported — a lost device means revocation via sigchain.

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use argon2::Argon2;
use ed25519_dalek::{SigningKey, VerifyingKey};
use serde::{Deserialize, Serialize};
use x25519_dalek::{PublicKey as X25519PublicKey, StaticSecret as X25519Secret};
use zeroize::Zeroize;

use crate::errors::CryptoError;

/// KDF version byte stored in encrypted key material for future-proofing.
/// v2 = Argon2id (64MB, 3 iterations, 4 parallelism).
const KDF_VERSION: u8 = 2;

/// Argon2id parameters — tuned for GPU/ASIC resistance.
const ARGON2_M_COST_KIB: u32 = 65_536; // 64 MB
const ARGON2_T_COST: u32 = 3; // 3 iterations
const ARGON2_P_COST: u32 = 4; // 4 lanes

/// Device key state exposed to callers (no secret material).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct DeviceKeyState {
    /// Unique device identifier (UUID)
    pub device_id: String,
    /// Ed25519 verifying (public) key, hex-encoded (32 bytes / 64 hex chars)
    pub signing_pubkey_hex: String,
    /// X25519 public key, hex-encoded (32 bytes / 64 hex chars)
    pub encryption_pubkey_hex: String,
}

/// Encrypted device key blob for credential-protected storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct EncryptedDeviceKeys {
    /// KDF version (2 = Argon2id)
    #[serde(default = "default_kdf_version")]
    pub kdf_version: u8,
    /// Argon2id salt, hex-encoded (32 bytes)
    pub salt: String,
    /// Argon2id memory cost in KiB
    #[serde(default = "default_argon2_m_cost")]
    pub argon2_m_cost: u32,
    /// Argon2id time cost (iterations)
    #[serde(default = "default_argon2_t_cost")]
    pub argon2_t_cost: u32,
    /// Argon2id parallelism
    #[serde(default = "default_argon2_p_cost")]
    pub argon2_p_cost: u32,
    /// AES-256-GCM nonce, hex-encoded (12 bytes)
    pub nonce: String,
    /// AES-256-GCM ciphertext of (signing_seed || encryption_seed), hex-encoded
    pub ciphertext: String,
    /// Device state (public info for identification)
    pub state: DeviceKeyState,
}

fn default_kdf_version() -> u8 { KDF_VERSION }
fn default_argon2_m_cost() -> u32 { ARGON2_M_COST_KIB }
fn default_argon2_t_cost() -> u32 { ARGON2_T_COST }
fn default_argon2_p_cost() -> u32 { ARGON2_P_COST }

/// Internal: holds the raw secret key bytes (zeroized on drop).
#[derive(Zeroize)]
#[zeroize(drop)]
pub struct DeviceSecrets {
    pub signing_seed: [u8; 32],
    pub encryption_seed: [u8; 32],
}

impl DeviceSecrets {
    /// Derive the Ed25519 signing key from the seed.
    pub fn signing_key(&self) -> SigningKey {
        SigningKey::from_bytes(&self.signing_seed)
    }

    /// Derive the X25519 secret key from the seed.
    pub fn encryption_secret(&self) -> X25519Secret {
        X25519Secret::from(self.encryption_seed)
    }

    /// Get the Ed25519 verifying (public) key.
    pub fn signing_pubkey(&self) -> VerifyingKey {
        self.signing_key().verifying_key()
    }

    /// Get the X25519 public key.
    pub fn encryption_pubkey(&self) -> X25519PublicKey {
        X25519PublicKey::from(&self.encryption_secret())
    }
}

/// Generate a new random Ed25519 + X25519 keypair for a device.
///
/// Returns the device key state (public info) and the encrypted key blob.
/// The `device_id` should be a UUID generated by the caller.
/// `credential` is a PIN (8+ digits) or alphanumeric passphrase (8+ chars with at least one letter).
pub fn generate_device_keys(
    device_id: &str,
    credential: &str,
) -> Result<EncryptedDeviceKeys, CryptoError> {
    if !is_valid_credential(credential) {
        return Err(CryptoError::InvalidPin);
    }

    // Generate random seeds
    let mut signing_seed = [0u8; 32];
    let mut encryption_seed = [0u8; 32];
    getrandom::getrandom(&mut signing_seed).expect("getrandom failed");
    getrandom::getrandom(&mut encryption_seed).expect("getrandom failed");

    let secrets = DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let state = DeviceKeyState {
        device_id: device_id.to_string(),
        signing_pubkey_hex: hex::encode(secrets.signing_pubkey().to_bytes()),
        encryption_pubkey_hex: hex::encode(secrets.encryption_pubkey().to_bytes()),
    };

    // Encrypt the secret seeds with credential
    let encrypted = encrypt_device_secrets(&secrets, credential, &state)?;

    // Zero the stack copies
    signing_seed.zeroize();
    encryption_seed.zeroize();

    Ok(encrypted)
}

/// Decrypt device keys from a credential-encrypted blob.
///
/// Returns the secrets (caller must hold in memory and zeroize on drop).
pub fn unlock_device_keys(
    encrypted: &EncryptedDeviceKeys,
    credential: &str,
) -> Result<DeviceSecrets, CryptoError> {
    let salt = hex::decode(&encrypted.salt).map_err(CryptoError::HexError)?;
    let nonce_bytes = hex::decode(&encrypted.nonce).map_err(CryptoError::HexError)?;
    let ciphertext = hex::decode(&encrypted.ciphertext).map_err(CryptoError::HexError)?;

    if nonce_bytes.len() != 12 {
        return Err(CryptoError::InvalidNonce);
    }

    let mut kek = derive_kek(credential, &salt)?;
    let nonce = Nonce::from_slice(&nonce_bytes);
    let cipher = Aes256Gcm::new_from_slice(&kek)
        .map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    let plaintext = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .map_err(|_| CryptoError::WrongPin)?;

    kek.zeroize();

    if plaintext.len() != 64 {
        return Err(CryptoError::InvalidFormat(
            "decrypted device key blob must be 64 bytes".into(),
        ));
    }

    let mut signing_seed = [0u8; 32];
    let mut encryption_seed = [0u8; 32];
    signing_seed.copy_from_slice(&plaintext[..32]);
    encryption_seed.copy_from_slice(&plaintext[32..]);

    // Verify the derived public keys match the stored state
    let secrets = DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let derived_signing_pubkey = hex::encode(secrets.signing_pubkey().to_bytes());
    let derived_encryption_pubkey = hex::encode(secrets.encryption_pubkey().to_bytes());

    if derived_signing_pubkey != encrypted.state.signing_pubkey_hex
        || derived_encryption_pubkey != encrypted.state.encryption_pubkey_hex
    {
        return Err(CryptoError::InvalidFormat(
            "derived public keys do not match stored state".into(),
        ));
    }

    Ok(secrets)
}

/// Sign a message with the device's Ed25519 signing key.
pub fn sign_bytes(secrets: &DeviceSecrets, message: &[u8]) -> Vec<u8> {
    use ed25519_dalek::Signer;
    let signing_key = secrets.signing_key();
    let signature = signing_key.sign(message);
    signature.to_bytes().to_vec()
}

/// Verify an Ed25519 signature against a public key.
pub fn verify_signature(
    message: &[u8],
    signature_bytes: &[u8],
    pubkey_hex: &str,
) -> Result<bool, CryptoError> {
    let pubkey_bytes = hex::decode(pubkey_hex).map_err(CryptoError::HexError)?;
    if pubkey_bytes.len() != 32 {
        return Err(CryptoError::InvalidPublicKey);
    }

    let pubkey_arr: [u8; 32] = pubkey_bytes
        .try_into()
        .map_err(|_| CryptoError::InvalidPublicKey)?;
    let verifying_key =
        VerifyingKey::from_bytes(&pubkey_arr).map_err(|_| CryptoError::InvalidPublicKey)?;

    if signature_bytes.len() != 64 {
        return Err(CryptoError::SignatureVerificationFailed);
    }
    let sig_arr: [u8; 64] = signature_bytes
        .try_into()
        .map_err(|_| CryptoError::SignatureVerificationFailed)?;
    let signature = ed25519_dalek::Signature::from_bytes(&sig_arr);

    use ed25519_dalek::Verifier;
    match verifying_key.verify(message, &signature) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

// --- Internal helpers ---

fn encrypt_device_secrets(
    secrets: &DeviceSecrets,
    credential: &str,
    state: &DeviceKeyState,
) -> Result<EncryptedDeviceKeys, CryptoError> {
    let mut salt = [0u8; 32];
    getrandom::getrandom(&mut salt).expect("getrandom failed");

    let mut kek = derive_kek(credential, &salt)?;

    let mut nonce_bytes = [0u8; 12];
    getrandom::getrandom(&mut nonce_bytes).expect("getrandom failed");
    let nonce = Nonce::from_slice(&nonce_bytes);

    let cipher = Aes256Gcm::new_from_slice(&kek)
        .map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    // Concatenate signing_seed || encryption_seed
    let mut plaintext = Vec::with_capacity(64);
    plaintext.extend_from_slice(&secrets.signing_seed);
    plaintext.extend_from_slice(&secrets.encryption_seed);

    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_ref())
        .map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    plaintext.zeroize();
    kek.zeroize();

    Ok(EncryptedDeviceKeys {
        kdf_version: KDF_VERSION,
        salt: hex::encode(salt),
        argon2_m_cost: ARGON2_M_COST_KIB,
        argon2_t_cost: ARGON2_T_COST,
        argon2_p_cost: ARGON2_P_COST,
        nonce: hex::encode(nonce_bytes),
        ciphertext: hex::encode(ciphertext),
        state: state.clone(),
    })
}

/// Derive a 32-byte KEK from a credential using Argon2id.
fn derive_kek(credential: &str, salt: &[u8]) -> Result<[u8; 32], CryptoError> {
    let mut kek = [0u8; 32];
    let params = argon2::Params::new(ARGON2_M_COST_KIB, ARGON2_T_COST, ARGON2_P_COST, Some(32))
        .map_err(|e| CryptoError::EncryptionFailed(format!("argon2 params: {e}")))?;
    let argon2 = Argon2::new(argon2::Algorithm::Argon2id, argon2::Version::V0x13, params);
    argon2
        .hash_password_into(credential.as_bytes(), salt, &mut kek)
        .map_err(|e| CryptoError::EncryptionFailed(format!("argon2id: {e}")))?;
    Ok(kek)
}

/// Validate a credential: numeric PIN (8+ digits) or alphanumeric passphrase (8+ chars with at least one letter).
pub fn is_valid_credential(credential: &str) -> bool {
    let len = credential.len();
    if len < 8 {
        return false;
    }
    // All digits = numeric PIN (8+)
    if credential.chars().all(|c| c.is_ascii_digit()) {
        return true;
    }
    // Alphanumeric passphrase: must have at least one letter
    credential.chars().any(|c| c.is_alphabetic())
}

/// Backward-compatible alias — validates the new credential rules.
pub fn is_valid_pin(pin: &str) -> bool {
    is_valid_credential(pin)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_and_unlock_with_pin() {
        let encrypted = generate_device_keys("test-device-1", "12345678").unwrap();
        assert_eq!(encrypted.state.device_id, "test-device-1");
        assert_eq!(encrypted.state.signing_pubkey_hex.len(), 64);
        assert_eq!(encrypted.state.encryption_pubkey_hex.len(), 64);
        assert_eq!(encrypted.kdf_version, KDF_VERSION);
        assert_eq!(encrypted.argon2_m_cost, ARGON2_M_COST_KIB);

        let secrets = unlock_device_keys(&encrypted, "12345678").unwrap();
        assert_eq!(
            hex::encode(secrets.signing_pubkey().to_bytes()),
            encrypted.state.signing_pubkey_hex
        );
        assert_eq!(
            hex::encode(secrets.encryption_pubkey().to_bytes()),
            encrypted.state.encryption_pubkey_hex
        );
    }

    #[test]
    fn generate_and_unlock_with_passphrase() {
        let encrypted = generate_device_keys("test-device-pp", "MyStr0ngPass!").unwrap();
        let secrets = unlock_device_keys(&encrypted, "MyStr0ngPass!").unwrap();
        assert_eq!(
            hex::encode(secrets.signing_pubkey().to_bytes()),
            encrypted.state.signing_pubkey_hex
        );
    }

    #[test]
    fn wrong_credential_fails() {
        let encrypted = generate_device_keys("test-device-2", "12345678").unwrap();
        let result = unlock_device_keys(&encrypted, "99999999");
        assert!(result.is_err());
    }

    #[test]
    fn sign_and_verify() {
        let encrypted = generate_device_keys("test-device-3", "65432100").unwrap();
        let secrets = unlock_device_keys(&encrypted, "65432100").unwrap();

        let message = b"test message to sign";
        let signature = sign_bytes(&secrets, message);
        assert_eq!(signature.len(), 64);

        let valid =
            verify_signature(message, &signature, &encrypted.state.signing_pubkey_hex).unwrap();
        assert!(valid);

        // Wrong message fails
        let valid = verify_signature(
            b"wrong message",
            &signature,
            &encrypted.state.signing_pubkey_hex,
        )
        .unwrap();
        assert!(!valid);
    }

    #[test]
    fn verify_with_wrong_key_fails() {
        let encrypted1 = generate_device_keys("dev-1", "12345678").unwrap();
        let encrypted2 = generate_device_keys("dev-2", "12345678").unwrap();
        let secrets1 = unlock_device_keys(&encrypted1, "12345678").unwrap();

        let message = b"hello";
        let signature = sign_bytes(&secrets1, message);

        let valid =
            verify_signature(message, &signature, &encrypted2.state.signing_pubkey_hex).unwrap();
        assert!(!valid);
    }

    #[test]
    fn credential_validation() {
        // Too short
        assert!(!is_valid_credential("1234567")); // 7 digits
        assert!(!is_valid_credential("short")); // 5 chars
        assert!(!is_valid_credential("")); // empty

        // Old 6-digit PIN rejected (was valid before)
        assert!(!is_valid_credential("123456"));

        // Valid numeric PINs (8+ digits)
        assert!(is_valid_credential("12345678")); // exactly 8
        assert!(is_valid_credential("123456789012")); // 12 digits

        // Valid alphanumeric passphrases (8+ chars with at least one letter)
        assert!(is_valid_credential("abcdefgh")); // all letters
        assert!(is_valid_credential("MyPass12")); // mixed
        assert!(is_valid_credential("p@ssw0rd!")); // symbols + letters

        // 8 chars all symbols, no letters = invalid
        assert!(!is_valid_credential("!@#$%^&*"));
    }

    #[test]
    fn argon2id_derivation_is_deterministic() {
        let salt = [42u8; 32];
        let kek1 = derive_kek("testpassword", &salt).unwrap();
        let kek2 = derive_kek("testpassword", &salt).unwrap();
        assert_eq!(kek1, kek2);

        // Different credential → different key
        let kek3 = derive_kek("otherpassword", &salt).unwrap();
        assert_ne!(kek1, kek3);
    }

    #[test]
    fn secrets_zeroize_on_drop() {
        let encrypted = generate_device_keys("dev-z", "12345678").unwrap();
        let pubkey = encrypted.state.signing_pubkey_hex.clone();
        {
            let secrets = unlock_device_keys(&encrypted, "12345678").unwrap();
            assert_eq!(hex::encode(secrets.signing_pubkey().to_bytes()), pubkey);
        }
    }
}
