//! Device key management — Ed25519 signing + X25519 encryption keypairs.
//!
//! Each device generates two independent keypairs on first launch:
//! - Ed25519 for signing (sigchain entries, auth tokens, MLS leaf credentials)
//! - X25519 for encryption (HPKE decapsulation, PUK seed wrapping)
//!
//! Key material is PIN-encrypted for storage using PBKDF2-SHA256 + AES-256-GCM.
//! The device keypairs are NEVER exported — a lost device means revocation via sigchain.

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use ed25519_dalek::{SigningKey, VerifyingKey};
use pbkdf2::pbkdf2_hmac;
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use x25519_dalek::{PublicKey as X25519PublicKey, StaticSecret as X25519Secret};
use zeroize::Zeroize;

use crate::errors::CryptoError;

const PBKDF2_ITERATIONS: u32 = 600_000;

/// Device key state exposed to callers (no secret material).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct DeviceKeyState {
    /// Unique device identifier (UUID)
    pub device_id: String,
    /// Ed25519 verifying (public) key, hex-encoded (32 bytes / 64 hex chars)
    pub signing_pubkey_hex: String,
    /// X25519 public key, hex-encoded (32 bytes / 64 hex chars)
    pub encryption_pubkey_hex: String,
}

/// Encrypted device key blob for PIN-protected storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct EncryptedDeviceKeys {
    /// PBKDF2 salt, hex-encoded (32 bytes)
    pub salt: String,
    /// PBKDF2 iteration count
    pub iterations: u32,
    /// AES-256-GCM nonce, hex-encoded (12 bytes)
    pub nonce: String,
    /// AES-256-GCM ciphertext of (signing_seed || encryption_seed), hex-encoded
    pub ciphertext: String,
    /// Device state (public info for identification)
    pub state: DeviceKeyState,
}

/// Internal: holds the raw secret key bytes (zeroized on drop).
#[derive(Zeroize)]
#[zeroize(drop)]
pub struct DeviceSecrets {
    pub signing_seed: [u8; 32],
    pub encryption_seed: [u8; 32],
}

impl DeviceSecrets {
    /// Derive the Ed25519 signing key from the seed.
    pub fn signing_key(&self) -> SigningKey {
        SigningKey::from_bytes(&self.signing_seed)
    }

    /// Derive the X25519 secret key from the seed.
    pub fn encryption_secret(&self) -> X25519Secret {
        X25519Secret::from(self.encryption_seed)
    }

    /// Get the Ed25519 verifying (public) key.
    pub fn signing_pubkey(&self) -> VerifyingKey {
        self.signing_key().verifying_key()
    }

    /// Get the X25519 public key.
    pub fn encryption_pubkey(&self) -> X25519PublicKey {
        X25519PublicKey::from(&self.encryption_secret())
    }
}

/// Generate a new random Ed25519 + X25519 keypair for a device.
///
/// Returns the device key state (public info) and the encrypted key blob.
/// The `device_id` should be a UUID generated by the caller.
pub fn generate_device_keys(
    device_id: &str,
    pin: &str,
) -> Result<EncryptedDeviceKeys, CryptoError> {
    if !is_valid_pin(pin) {
        return Err(CryptoError::InvalidPin);
    }

    // Generate random seeds
    let mut signing_seed = [0u8; 32];
    let mut encryption_seed = [0u8; 32];
    getrandom::getrandom(&mut signing_seed).expect("getrandom failed");
    getrandom::getrandom(&mut encryption_seed).expect("getrandom failed");

    let secrets = DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let state = DeviceKeyState {
        device_id: device_id.to_string(),
        signing_pubkey_hex: hex::encode(secrets.signing_pubkey().to_bytes()),
        encryption_pubkey_hex: hex::encode(secrets.encryption_pubkey().to_bytes()),
    };

    // Encrypt the secret seeds with PIN
    let encrypted = encrypt_device_secrets(&secrets, pin, &state)?;

    // Zero the stack copies
    signing_seed.zeroize();
    encryption_seed.zeroize();

    Ok(encrypted)
}

/// Decrypt device keys from a PIN-encrypted blob.
///
/// Returns the secrets (caller must hold in memory and zeroize on drop).
pub fn unlock_device_keys(
    encrypted: &EncryptedDeviceKeys,
    pin: &str,
) -> Result<DeviceSecrets, CryptoError> {
    let salt = hex::decode(&encrypted.salt).map_err(CryptoError::HexError)?;
    let nonce_bytes = hex::decode(&encrypted.nonce).map_err(CryptoError::HexError)?;
    let ciphertext = hex::decode(&encrypted.ciphertext).map_err(CryptoError::HexError)?;

    if nonce_bytes.len() != 12 {
        return Err(CryptoError::InvalidNonce);
    }

    let mut kek = derive_kek(pin, &salt);
    let nonce = Nonce::from_slice(&nonce_bytes);
    let cipher =
        Aes256Gcm::new_from_slice(&kek).map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    let plaintext = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .map_err(|_| CryptoError::WrongPin)?;

    kek.zeroize();

    if plaintext.len() != 64 {
        return Err(CryptoError::InvalidFormat(
            "decrypted device key blob must be 64 bytes".into(),
        ));
    }

    let mut signing_seed = [0u8; 32];
    let mut encryption_seed = [0u8; 32];
    signing_seed.copy_from_slice(&plaintext[..32]);
    encryption_seed.copy_from_slice(&plaintext[32..]);

    // Verify the derived public keys match the stored state
    let secrets = DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let derived_signing_pubkey = hex::encode(secrets.signing_pubkey().to_bytes());
    let derived_encryption_pubkey = hex::encode(secrets.encryption_pubkey().to_bytes());

    if derived_signing_pubkey != encrypted.state.signing_pubkey_hex
        || derived_encryption_pubkey != encrypted.state.encryption_pubkey_hex
    {
        return Err(CryptoError::InvalidFormat(
            "derived public keys do not match stored state".into(),
        ));
    }

    Ok(secrets)
}

/// Sign a message with the device's Ed25519 signing key.
pub fn sign_bytes(secrets: &DeviceSecrets, message: &[u8]) -> Vec<u8> {
    use ed25519_dalek::Signer;
    let signing_key = secrets.signing_key();
    let signature = signing_key.sign(message);
    signature.to_bytes().to_vec()
}

/// Verify an Ed25519 signature against a public key.
pub fn verify_signature(
    message: &[u8],
    signature_bytes: &[u8],
    pubkey_hex: &str,
) -> Result<bool, CryptoError> {
    let pubkey_bytes = hex::decode(pubkey_hex).map_err(CryptoError::HexError)?;
    if pubkey_bytes.len() != 32 {
        return Err(CryptoError::InvalidPublicKey);
    }

    let pubkey_arr: [u8; 32] = pubkey_bytes
        .try_into()
        .map_err(|_| CryptoError::InvalidPublicKey)?;
    let verifying_key =
        VerifyingKey::from_bytes(&pubkey_arr).map_err(|_| CryptoError::InvalidPublicKey)?;

    if signature_bytes.len() != 64 {
        return Err(CryptoError::SignatureVerificationFailed);
    }
    let sig_arr: [u8; 64] = signature_bytes
        .try_into()
        .map_err(|_| CryptoError::SignatureVerificationFailed)?;
    let signature = ed25519_dalek::Signature::from_bytes(&sig_arr);

    use ed25519_dalek::Verifier;
    match verifying_key.verify(message, &signature) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

// --- Internal helpers ---

fn encrypt_device_secrets(
    secrets: &DeviceSecrets,
    pin: &str,
    state: &DeviceKeyState,
) -> Result<EncryptedDeviceKeys, CryptoError> {
    let mut salt = [0u8; 32];
    getrandom::getrandom(&mut salt).expect("getrandom failed");

    let mut kek = derive_kek(pin, &salt);

    let mut nonce_bytes = [0u8; 12];
    getrandom::getrandom(&mut nonce_bytes).expect("getrandom failed");
    let nonce = Nonce::from_slice(&nonce_bytes);

    let cipher =
        Aes256Gcm::new_from_slice(&kek).map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    // Concatenate signing_seed || encryption_seed
    let mut plaintext = Vec::with_capacity(64);
    plaintext.extend_from_slice(&secrets.signing_seed);
    plaintext.extend_from_slice(&secrets.encryption_seed);

    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_ref())
        .map_err(|e| CryptoError::EncryptionFailed(e.to_string()))?;

    plaintext.zeroize();
    kek.zeroize();

    Ok(EncryptedDeviceKeys {
        salt: hex::encode(salt),
        iterations: PBKDF2_ITERATIONS,
        nonce: hex::encode(nonce_bytes),
        ciphertext: hex::encode(ciphertext),
        state: state.clone(),
    })
}

fn derive_kek(pin: &str, salt: &[u8]) -> [u8; 32] {
    let mut kek = [0u8; 32];
    pbkdf2_hmac::<Sha256>(pin.as_bytes(), salt, PBKDF2_ITERATIONS, &mut kek);
    kek
}

/// Validate PIN format: 6-8 digits.
pub fn is_valid_pin(pin: &str) -> bool {
    let len = pin.len();
    (6..=8).contains(&len) && pin.chars().all(|c| c.is_ascii_digit())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_and_unlock() {
        let encrypted = generate_device_keys("test-device-1", "123456").unwrap();
        assert_eq!(encrypted.state.device_id, "test-device-1");
        assert_eq!(encrypted.state.signing_pubkey_hex.len(), 64);
        assert_eq!(encrypted.state.encryption_pubkey_hex.len(), 64);

        let secrets = unlock_device_keys(&encrypted, "123456").unwrap();
        assert_eq!(
            hex::encode(secrets.signing_pubkey().to_bytes()),
            encrypted.state.signing_pubkey_hex
        );
        assert_eq!(
            hex::encode(secrets.encryption_pubkey().to_bytes()),
            encrypted.state.encryption_pubkey_hex
        );
    }

    #[test]
    fn wrong_pin_fails() {
        let encrypted = generate_device_keys("test-device-2", "123456").unwrap();
        let result = unlock_device_keys(&encrypted, "999999");
        assert!(result.is_err());
    }

    #[test]
    fn sign_and_verify() {
        let encrypted = generate_device_keys("test-device-3", "654321").unwrap();
        let secrets = unlock_device_keys(&encrypted, "654321").unwrap();

        let message = b"test message to sign";
        let signature = sign_bytes(&secrets, message);
        assert_eq!(signature.len(), 64);

        let valid =
            verify_signature(message, &signature, &encrypted.state.signing_pubkey_hex).unwrap();
        assert!(valid);

        // Wrong message fails
        let valid =
            verify_signature(b"wrong message", &signature, &encrypted.state.signing_pubkey_hex)
                .unwrap();
        assert!(!valid);
    }

    #[test]
    fn verify_with_wrong_key_fails() {
        let encrypted1 = generate_device_keys("dev-1", "123456").unwrap();
        let encrypted2 = generate_device_keys("dev-2", "123456").unwrap();
        let secrets1 = unlock_device_keys(&encrypted1, "123456").unwrap();

        let message = b"hello";
        let signature = sign_bytes(&secrets1, message);

        // Verify with device2's pubkey should fail
        let valid =
            verify_signature(message, &signature, &encrypted2.state.signing_pubkey_hex).unwrap();
        assert!(!valid);
    }

    #[test]
    fn invalid_pin_rejected() {
        assert!(generate_device_keys("dev", "12345").is_err()); // too short
        assert!(generate_device_keys("dev", "123456789").is_err()); // too long
        assert!(generate_device_keys("dev", "abcdef").is_err()); // not digits
        assert!(generate_device_keys("dev", "123456").is_ok()); // valid
        assert!(generate_device_keys("dev", "12345678").is_ok()); // valid
    }

    #[test]
    fn secrets_zeroize_on_drop() {
        let encrypted = generate_device_keys("dev-z", "123456").unwrap();
        let pubkey = encrypted.state.signing_pubkey_hex.clone();
        {
            let secrets = unlock_device_keys(&encrypted, "123456").unwrap();
            assert_eq!(hex::encode(secrets.signing_pubkey().to_bytes()), pubkey);
            // secrets dropped here — Zeroize on drop
        }
        // Can't verify zeroization happened in a unit test, but the derive(Zeroize)
        // + #[zeroize(drop)] ensures it.
    }
}
