//! MLS (Messaging Layer Security, RFC 9420) integration via OpenMLS.
//!
//! Each hub is an MLS group. Each device is a leaf in the ratchet tree.
//!
//! Ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
//!
//! This module provides:
//! - Group creation and management
//! - Key package generation and consumption
//! - Member add/remove operations
//! - Epoch secret export for hub PTK derivation
//! - Self-update for post-compromise security

use openmls::prelude::*;
use openmls::prelude::tls_codec::{Deserialize as TlsDeserializeTrait, Serialize as TlsSerializeTrait};
use openmls_basic_credential::SignatureKeyPair;
use openmls_rust_crypto::OpenMlsRustCrypto;
use serde::{Deserialize, Serialize};
use std::sync::Mutex;

use crate::errors::CryptoError;
use crate::labels::LABEL_HUB_PTK;

/// The ciphersuite used for all MLS groups.
const CIPHERSUITE: Ciphersuite = Ciphersuite::MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519;

/// MLS group state (public info).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct MlsGroupState {
    /// Group ID bytes, hex-encoded
    pub group_id_hex: String,
    /// Current epoch
    pub epoch: u64,
    /// Number of members in the group
    pub member_count: u32,
}

/// Key package bundle for pre-publishing.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct MlsKeyPackageBundle {
    /// Serialized key package bytes, hex-encoded
    pub key_package_hex: String,
}

/// Result of an MLS commit operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "mobile", derive(uniffi::Record))]
pub struct MlsCommitResult {
    /// Serialized commit message, hex-encoded
    pub commit_hex: String,
    /// Optional welcome message for new members, hex-encoded
    pub welcome_hex: Option<String>,
    /// New epoch after commit
    pub new_epoch: u64,
}

/// Manages MLS group state for a single device.
pub struct MlsManager {
    provider: OpenMlsRustCrypto,
    credential_with_key: CredentialWithKey,
    signature_keypair: SignatureKeyPair,
    groups: Mutex<Vec<MlsGroup>>,
}

impl MlsManager {
    /// Create a new MLS manager for a device.
    ///
    /// Uses a fresh SignatureKeyPair generated by OpenMLS (Ed25519).
    pub fn new(device_id: &str) -> Result<Self, CryptoError> {
        let provider = OpenMlsRustCrypto::default();

        let signature_keypair =
            SignatureKeyPair::new(CIPHERSUITE.signature_algorithm())
                .map_err(|e| CryptoError::EncryptionFailed(format!("MLS keygen: {e:?}")))?;

        signature_keypair
            .store(provider.storage())
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS store: {e:?}")))?;

        let credential = BasicCredential::new(device_id.as_bytes().to_vec());
        let credential_with_key = CredentialWithKey {
            credential: credential.into(),
            signature_key: signature_keypair.public().into(),
        };

        Ok(Self {
            provider,
            credential_with_key,
            signature_keypair,
            groups: Mutex::new(Vec::new()),
        })
    }

    /// Create a new MLS group (for hub creation).
    pub fn create_group(&self, group_id: &[u8]) -> Result<MlsGroupState, CryptoError> {
        let group_config = MlsGroupCreateConfig::builder()
            .ciphersuite(CIPHERSUITE)
            .use_ratchet_tree_extension(true)
            .build();

        let group = MlsGroup::new_with_group_id(
            &self.provider,
            &self.signature_keypair,
            &group_config,
            GroupId::from_slice(group_id),
            self.credential_with_key.clone(),
        )
        .map_err(|e| CryptoError::EncryptionFailed(format!("MLS group create: {e:?}")))?;

        let state = MlsGroupState {
            group_id_hex: hex::encode(group_id),
            epoch: group.epoch().as_u64(),
            member_count: group.members().count() as u32,
        };

        self.groups.lock().unwrap().push(group);
        Ok(state)
    }

    /// Generate key packages for pre-publishing.
    pub fn generate_key_packages(
        &self,
        count: u32,
    ) -> Result<Vec<MlsKeyPackageBundle>, CryptoError> {
        let mut packages = Vec::with_capacity(count as usize);

        for _ in 0..count {
            let kp_bundle = KeyPackage::builder()
                .build(
                    CIPHERSUITE,
                    &self.provider,
                    &self.signature_keypair,
                    self.credential_with_key.clone(),
                )
                .map_err(|e| CryptoError::EncryptionFailed(format!("MLS KP build: {e:?}")))?;

            let kp_serialized = kp_bundle
                .key_package()
                .tls_serialize_detached()
                .map_err(|e| CryptoError::EncryptionFailed(format!("MLS KP serialize: {e:?}")))?;

            packages.push(MlsKeyPackageBundle {
                key_package_hex: hex::encode(&kp_serialized),
            });
        }

        Ok(packages)
    }

    /// Add a member to a group using their serialized key package.
    pub fn add_member(
        &self,
        group_id: &[u8],
        key_package_hex: &str,
    ) -> Result<MlsCommitResult, CryptoError> {
        let kp_bytes = hex::decode(key_package_hex).map_err(CryptoError::HexError)?;

        let key_package_in = KeyPackageIn::tls_deserialize(&mut kp_bytes.as_slice())
            .map_err(|e| CryptoError::InvalidFormat(format!("MLS KP deserialize: {e:?}")))?;

        // Validate the key package
        let key_package = key_package_in
            .validate(self.provider.crypto(), ProtocolVersion::Mls10)
            .map_err(|e| CryptoError::InvalidFormat(format!("MLS KP validate: {e:?}")))?;

        let mut groups = self.groups.lock().unwrap();
        let group = groups
            .iter_mut()
            .find(|g| g.group_id().as_slice() == group_id)
            .ok_or_else(|| CryptoError::InvalidInput("group not found".into()))?;

        let (commit_out, welcome_out, _group_info) = group
            .add_members(
                &self.provider,
                &self.signature_keypair,
                &[key_package],
            )
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS add member: {e:?}")))?;

        group
            .merge_pending_commit(&self.provider)
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS merge: {e:?}")))?;

        let commit_bytes = commit_out
            .tls_serialize_detached()
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS commit ser: {e:?}")))?;

        let welcome_bytes = welcome_out
            .tls_serialize_detached()
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS welcome ser: {e:?}")))?;

        Ok(MlsCommitResult {
            commit_hex: hex::encode(&commit_bytes),
            welcome_hex: Some(hex::encode(&welcome_bytes)),
            new_epoch: group.epoch().as_u64(),
        })
    }

    /// Process a welcome message to join a group.
    pub fn process_welcome(&self, welcome_hex: &str) -> Result<MlsGroupState, CryptoError> {
        let welcome_bytes = hex::decode(welcome_hex).map_err(CryptoError::HexError)?;

        let mls_message_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice())
            .map_err(|e| CryptoError::InvalidFormat(format!("MLS msg deser: {e:?}")))?;

        let welcome = match mls_message_in.extract() {
            MlsMessageBodyIn::Welcome(w) => w,
            _ => {
                return Err(CryptoError::InvalidFormat(
                    "message is not a Welcome".into(),
                ))
            }
        };

        let join_config = MlsGroupJoinConfig::builder()
            .use_ratchet_tree_extension(true)
            .build();

        let staged = StagedWelcome::new_from_welcome(
            &self.provider,
            &join_config,
            welcome,
            None, // ratchet tree from extension
        )
        .map_err(|e| CryptoError::EncryptionFailed(format!("MLS staged welcome: {e:?}")))?;

        let group = staged
            .into_group(&self.provider)
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS join group: {e:?}")))?;

        let state = MlsGroupState {
            group_id_hex: hex::encode(group.group_id().as_slice()),
            epoch: group.epoch().as_u64(),
            member_count: group.members().count() as u32,
        };

        self.groups.lock().unwrap().push(group);
        Ok(state)
    }

    /// Export a secret from the current epoch.
    ///
    /// Used to derive hub PTK and SFrame keys.
    /// `context` is passed as the MLS exporter context for domain separation
    /// (typically the hub_id bytes).
    pub fn export_secret(
        &self,
        group_id: &[u8],
        label: &str,
        context: &[u8],
        length: usize,
    ) -> Result<Vec<u8>, CryptoError> {
        let groups = self.groups.lock().unwrap();
        let group = groups
            .iter()
            .find(|g| g.group_id().as_slice() == group_id)
            .ok_or_else(|| CryptoError::InvalidInput("group not found".into()))?;

        let secret = group
            .export_secret(self.provider.crypto(), label, context, length)
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS export: {e:?}")))?;

        Ok(secret)
    }

    /// Perform a self-update for post-compromise security.
    pub fn self_update(&self, group_id: &[u8]) -> Result<MlsCommitResult, CryptoError> {
        let mut groups = self.groups.lock().unwrap();
        let group = groups
            .iter_mut()
            .find(|g| g.group_id().as_slice() == group_id)
            .ok_or_else(|| CryptoError::InvalidInput("group not found".into()))?;

        let commit_bundle = group
            .self_update(
                &self.provider,
                &self.signature_keypair,
                LeafNodeParameters::default(),
            )
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS self update: {e:?}")))?;

        group
            .merge_pending_commit(&self.provider)
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS merge: {e:?}")))?;

        let commit_bytes = commit_bundle
            .commit()
            .tls_serialize_detached()
            .map_err(|e| CryptoError::EncryptionFailed(format!("MLS commit ser: {e:?}")))?;

        Ok(MlsCommitResult {
            commit_hex: hex::encode(&commit_bytes),
            welcome_hex: None,
            new_epoch: group.epoch().as_u64(),
        })
    }

    /// Get the current state of a group.
    pub fn group_state(&self, group_id: &[u8]) -> Result<MlsGroupState, CryptoError> {
        let groups = self.groups.lock().unwrap();
        let group = groups
            .iter()
            .find(|g| g.group_id().as_slice() == group_id)
            .ok_or_else(|| CryptoError::InvalidInput("group not found".into()))?;

        Ok(MlsGroupState {
            group_id_hex: hex::encode(group.group_id().as_slice()),
            epoch: group.epoch().as_u64(),
            member_count: group.members().count() as u32,
        })
    }
}

/// Derive hub PTK from MLS export secret.
///
/// `hub_ptk = HKDF-Expand(export_secret, LABEL_HUB_PTK + ":" + hub_id_hex, 32)`
///
/// Returns `Zeroizing<[u8; 32]>` to ensure the PTK is zeroed on drop.
pub fn derive_hub_ptk(export_secret: &[u8], hub_id: &[u8]) -> zeroize::Zeroizing<[u8; 32]> {
    use hkdf::Hkdf;
    use sha2::Sha256;

    let info = format!("{}:{}", LABEL_HUB_PTK, hex::encode(hub_id));
    let hk = Hkdf::<Sha256>::new(None, export_secret);
    let mut ptk = [0u8; 32];
    hk.expand(info.as_bytes(), &mut ptk)
        .expect("HKDF expand should not fail for 32 bytes");
    zeroize::Zeroizing::new(ptk)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn create_group_and_check_state() {
        let manager = MlsManager::new("device-1").unwrap();

        let state = manager.create_group(b"test-hub-1").unwrap();
        assert_eq!(state.group_id_hex, hex::encode(b"test-hub-1"));
        assert_eq!(state.epoch, 0);
        assert_eq!(state.member_count, 1);
    }

    #[test]
    fn generate_key_packages() {
        let manager = MlsManager::new("device-1").unwrap();

        let packages = manager.generate_key_packages(5).unwrap();
        assert_eq!(packages.len(), 5);

        for pkg in &packages {
            assert!(!pkg.key_package_hex.is_empty());
        }
    }

    #[test]
    fn add_member_and_process_welcome() {
        let manager1 = MlsManager::new("device-1").unwrap();
        let manager2 = MlsManager::new("device-2").unwrap();

        // Device 1 creates group
        manager1.create_group(b"test-hub").unwrap();

        // Device 2 generates key packages
        let packages = manager2.generate_key_packages(1).unwrap();

        // Device 1 adds device 2
        let commit_result = manager1
            .add_member(b"test-hub", &packages[0].key_package_hex)
            .unwrap();
        assert!(commit_result.welcome_hex.is_some());
        assert_eq!(commit_result.new_epoch, 1);

        // Device 2 processes welcome
        let state2 = manager2
            .process_welcome(&commit_result.welcome_hex.unwrap())
            .unwrap();
        assert_eq!(state2.group_id_hex, hex::encode(b"test-hub"));
        assert_eq!(state2.member_count, 2);
    }

    #[test]
    fn export_secret_consistent() {
        let manager1 = MlsManager::new("device-1").unwrap();
        let manager2 = MlsManager::new("device-2").unwrap();

        manager1.create_group(b"export-hub").unwrap();

        let packages = manager2.generate_key_packages(1).unwrap();
        let commit = manager1
            .add_member(b"export-hub", &packages[0].key_package_hex)
            .unwrap();
        manager2
            .process_welcome(&commit.welcome_hex.unwrap())
            .unwrap();

        // Both members should derive the same export secret
        let secret1 = manager1
            .export_secret(b"export-hub", "test-label", b"export-hub", 32)
            .unwrap();
        let secret2 = manager2
            .export_secret(b"export-hub", "test-label", b"export-hub", 32)
            .unwrap();
        assert_eq!(secret1, secret2);
        assert_eq!(secret1.len(), 32);
    }

    #[test]
    fn self_update_advances_epoch() {
        let manager = MlsManager::new("device-1").unwrap();

        manager.create_group(b"update-hub").unwrap();
        let result = manager.self_update(b"update-hub").unwrap();
        assert_eq!(result.new_epoch, 1);
        assert!(result.welcome_hex.is_none());

        let state = manager.group_state(b"update-hub").unwrap();
        assert_eq!(state.epoch, 1);
    }

    #[test]
    fn derive_hub_ptk_deterministic() {
        let secret = [42u8; 32];
        let hub_id = b"hub-123";
        let ptk1 = derive_hub_ptk(&secret, hub_id);
        let ptk2 = derive_hub_ptk(&secret, hub_id);
        assert_eq!(*ptk1, *ptk2);
        assert_ne!(*ptk1, [0u8; 32]);

        let ptk3 = derive_hub_ptk(&secret, b"hub-456");
        assert_ne!(*ptk1, *ptk3);
    }
}
