package org.llamenos.hotline.steps.crypto

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Data classes for deserializing test-vectors.json from packages/crypto/tests/fixtures/.
 *
 * These vectors are generated by the Rust interop tests and used to verify
 * that the Android crypto implementation (via UniFFI JNI or placeholder)
 * produces compatible output across all platforms.
 */
@Serializable
data class TestVectorsJson(
    val version: String,
    val keys: KeyVectors,
    val labels: Map<String, String>,
    val pinEncryption: PinEncryptionVectors,
    val auth: AuthVectors,
    val noteEncryption: NoteEncryptionVectors,
    val messageEncryption: MessageEncryptionVectors,
) {
    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        fun fromJson(jsonString: String): TestVectorsJson =
            json.decodeFromString(jsonString)
    }
}

@Serializable
data class KeyVectors(
    val secretKeyHex: String,
    val publicKeyHex: String,
    val nsec: String,
    val npub: String,
    val adminSecretKeyHex: String,
    val adminPublicKeyHex: String,
    val wrongSecretKeyHex: String = "",
    val wrongPublicKeyHex: String = "",
)

@Serializable
data class PinEncryptionVectors(
    val pin: String,
    val nsec: String,
    val pubkeyHex: String,
    val encrypted: PinEncryptedData,
    val decryptable: Boolean,
)

@Serializable
data class PinEncryptedData(
    val salt: String,
    val iterations: UInt,
    val nonce: String,
    val ciphertext: String,
    val pubkey: String,
)

@Serializable
data class AuthVectors(
    val secretKeyHex: String,
    val timestamp: Long,
    val method: String,
    val path: String,
    val token: AuthTokenData,
    val valid: Boolean,
)

@Serializable
data class AuthTokenData(
    val pubkey: String,
    val timestamp: Long,
    val token: String,
)

@Serializable
data class NoteEncryptionVectors(
    val plaintextJson: String,
    val authorPubkey: String,
    val adminPubkeys: List<String>,
    val authorCanDecrypt: Boolean,
    val adminCanDecrypt: Boolean,
)

@Serializable
data class MessageEncryptionVectors(
    val plaintext: String,
    val readerPubkeys: List<String>,
    val volunteerCanDecrypt: Boolean,
    val adminCanDecrypt: Boolean,
)
