//! Tauri command wrappers around llamenos-core crypto operations (v3 API).
//!
//! All commands use `DeviceKeyState` which holds Ed25519 + X25519 keypairs
//! exclusively in the Rust process. The webview never receives secret key material.
//!
//! On desktop, the webview calls stateful commands via `platform.ts`.
//! Device keys are decrypted once (unlock_with_pin), stored in DeviceKeyState,
//! and zeroized on lock/quit/sleep.
//!
//! Encrypted device key blobs are persisted in Tauri Stronghold (encrypted vault
//! with PBKDF2 key derivation) via the frontend — see `platform.ts`. This module
//! does not access storage directly; it only manages in-memory crypto state.

use std::sync::Mutex;

use llamenos_core::{
    auth, device_keys, hpke_envelope,
    labels::{LABEL_BACKUP_HKDF_INFO, LABEL_DEVICE_ENCRYPTION_SEED},
    puk, sas, sigchain,
};
use tauri::Manager;

use aes_gcm::{
    aead::{Aead, KeyInit, Payload},
    Aes256Gcm, Nonce,
};

fn err_str(e: impl std::fmt::Display) -> String {
    e.to_string()
}

// ── CryptoState — device key secrets live ONLY here, never in the webview ──

/// Holds the decrypted device key secrets in Rust memory. Zeroized on lock/quit.
pub struct CryptoState {
    /// Device secrets (Ed25519 signing seed + X25519 encryption seed), or None if locked.
    secrets: Mutex<Option<device_keys::DeviceSecrets>>,
    /// Device key state (public info: device_id, signing pubkey, encryption pubkey).
    device_state: Mutex<Option<device_keys::DeviceKeyState>>,
    /// PIN attempt counter — stored in Rust memory only (JS cannot tamper via plugin:store|set).
    pin_failed_attempts: Mutex<u32>,
    /// PIN lockout expiry — epoch millis. Zero means no lockout.
    pin_lockout_until: Mutex<u64>,
    /// Hub symmetric key — 32 bytes for AES-256-GCM hub event decryption.
    /// Stored in Rust to prevent webview JS from accessing it (H2 hardening).
    hub_key: Mutex<Option<Vec<u8>>>,
    /// Server event key(s) — epoch-scoped symmetric keys for relay event decryption.
    /// Current + previous epoch for rolling window (H5 hardening).
    server_event_keys: Mutex<Vec<(u64, Vec<u8>)>>,
    /// Recovery group key — reconstructed from Shamir shares, held temporarily for decryption.
    /// Zeroized after use (set to None after recovery_group_decrypt).
    recovery_group_key: Mutex<Option<Vec<u8>>>,
    /// Ephemeral X25519 secret for device provisioning (new device side).
    /// Generated by provision_create_session, consumed by provision_decrypt_and_import.
    provisioning_ephemeral: Mutex<Option<[u8; 32]>>,
}

impl CryptoState {
    pub fn new() -> Self {
        Self {
            secrets: Mutex::new(None),
            device_state: Mutex::new(None),
            pin_failed_attempts: Mutex::new(0),
            pin_lockout_until: Mutex::new(0),
            hub_key: Mutex::new(None),
            server_event_keys: Mutex::new(Vec::new()),
            recovery_group_key: Mutex::new(None),
            provisioning_ephemeral: Mutex::new(None),
        }
    }

    /// Zeroize secrets and lock.
    pub fn lock(&self) {
        // DeviceSecrets implements Zeroize on drop
        *self.secrets.lock().unwrap() = None;
        *self.device_state.lock().unwrap() = None;
        *self.hub_key.lock().unwrap() = None;
        self.server_event_keys.lock().unwrap().clear();
        *self.recovery_group_key.lock().unwrap() = None;
        *self.provisioning_ephemeral.lock().unwrap() = None;
    }

    fn with_secrets<T>(
        &self,
        f: impl FnOnce(&device_keys::DeviceSecrets) -> Result<T, String>,
    ) -> Result<T, String> {
        let guard = self.secrets.lock().unwrap();
        let secrets = guard
            .as_ref()
            .ok_or_else(|| "Device key is locked. Enter PIN to unlock.".to_string())?;
        f(secrets)
    }

    fn get_device_state(&self) -> Result<device_keys::DeviceKeyState, String> {
        self.device_state
            .lock()
            .unwrap()
            .clone()
            .ok_or_else(|| "Device key is locked. Enter PIN to unlock.".into())
    }

    fn encryption_secret_hex(&self) -> Result<String, String> {
        self.with_secrets(|s| Ok(hex::encode(s.encryption_seed)))
    }
}

// ── Stateful commands (device secrets stay in Rust) ──────────────────

/// Generate a new device keypair, encrypt with PIN, and load into CryptoState.
/// Returns the encrypted key blob and public device state — secrets NEVER leave Rust.
#[tauri::command]
pub fn device_generate_and_load(
    state: tauri::State<'_, CryptoState>,
    pin: String,
    device_id: String,
) -> Result<serde_json::Value, String> {
    let encrypted = device_keys::generate_device_keys(&device_id, &pin).map_err(err_str)?;
    let secrets = device_keys::unlock_device_keys(&encrypted, &pin).map_err(err_str)?;

    let device_state = encrypted.state.clone();
    *state.secrets.lock().unwrap() = Some(secrets);
    *state.device_state.lock().unwrap() = Some(device_state.clone());

    let result = serde_json::to_value(&encrypted).map_err(err_str)?;
    Ok(result)
}

/// Decrypt device keys from PIN-encrypted storage, load into CryptoState.
/// Returns only the device state (public keys) — secrets NEVER leave the Rust process.
///
/// PIN lockout schedule:
///   1-4 failures: no lockout
///   5-6 failures: 30s lockout
///   7-8 failures: 2min lockout
///   9 failures: 10min lockout
///   10+ failures: signal frontend to wipe encrypted keys from Stronghold
#[tauri::command]
pub fn unlock_with_pin(
    state: tauri::State<'_, CryptoState>,
    data: device_keys::EncryptedDeviceKeys,
    pin: String,
) -> Result<serde_json::Value, String> {
    let attempts: u32 = *state.pin_failed_attempts.lock().unwrap();
    let lockout_until: u64 = *state.pin_lockout_until.lock().unwrap();

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64;

    if now < lockout_until {
        let remaining = (lockout_until - now) / 1000;
        return Err(format!("Locked out. Try again in {remaining} seconds"));
    }

    match device_keys::unlock_device_keys(&data, &pin) {
        Ok(secrets) => {
            *state.pin_failed_attempts.lock().unwrap() = 0;
            *state.pin_lockout_until.lock().unwrap() = 0;

            let device_state = data.state.clone();
            *state.secrets.lock().unwrap() = Some(secrets);
            *state.device_state.lock().unwrap() = Some(device_state.clone());

            serde_json::to_value(&device_state).map_err(err_str)
        }
        Err(_) => {
            let new_attempts = attempts + 1;
            *state.pin_failed_attempts.lock().unwrap() = new_attempts;

            let lockout_ms: u64 = match new_attempts {
                1..=4 => 0,
                5..=6 => 30_000,
                7..=8 => 120_000,
                9 => 600_000,
                _ => {
                    // Signal the frontend to wipe the encrypted keys from Stronghold.
                    // The frontend handles storage — Rust only manages in-memory state.
                    *state.pin_failed_attempts.lock().unwrap() = 0;
                    *state.pin_lockout_until.lock().unwrap() = 0;
                    return Err("Too many failed attempts. Keys wiped.".to_string());
                }
            };
            if lockout_ms > 0 {
                *state.pin_lockout_until.lock().unwrap() = now + lockout_ms;
            }
            Err("Wrong PIN".to_string())
        }
    }
}

/// Lock the crypto state — zeroizes device secrets.
#[tauri::command]
pub fn lock_crypto(state: tauri::State<'_, CryptoState>) {
    state.lock();
}

/// Check if the crypto state is unlocked.
#[tauri::command]
pub fn is_crypto_unlocked(state: tauri::State<'_, CryptoState>) -> bool {
    state.secrets.lock().unwrap().is_some()
}

/// Get the device public keys from CryptoState (no secret key exposure).
#[tauri::command]
pub fn get_device_pubkeys(
    state: tauri::State<'_, CryptoState>,
) -> Result<serde_json::Value, String> {
    let ds = state.get_device_state()?;
    serde_json::to_value(&ds).map_err(err_str)
}

// ── Auth tokens (Ed25519) ───────────────────────────────────────────

/// Create an Ed25519 auth token using the device signing key in CryptoState.
#[tauri::command]
pub fn create_auth_token_from_state(
    state: tauri::State<'_, CryptoState>,
    timestamp: u64,
    method: String,
    path: String,
) -> Result<String, String> {
    state.with_secrets(|secrets| {
        let token = auth::create_auth_token(secrets, timestamp, &method, &path).map_err(err_str)?;
        serde_json::to_string(&token).map_err(err_str)
    })
}

// ── Ed25519 signing/verification ────────────────────────────────────

/// Sign a message (hex-encoded) using the device's Ed25519 key.
#[tauri::command]
pub fn ed25519_sign_from_state(
    state: tauri::State<'_, CryptoState>,
    message_hex: String,
) -> Result<String, String> {
    let message = hex::decode(&message_hex).map_err(err_str)?;
    state.with_secrets(|secrets| {
        let sig = device_keys::sign_bytes(secrets, &message);
        Ok(hex::encode(sig))
    })
}

/// Verify an Ed25519 signature (stateless — no secrets needed).
#[tauri::command]
pub fn ed25519_verify(
    message_hex: String,
    signature_hex: String,
    pubkey_hex: String,
) -> Result<bool, String> {
    let message = hex::decode(&message_hex).map_err(err_str)?;
    let signature = hex::decode(&signature_hex).map_err(err_str)?;
    device_keys::verify_signature(&message, &signature, &pubkey_hex).map_err(err_str)
}

// ── HPKE envelope encryption ───────────────────────────────────────

/// HPKE seal: encrypt plaintext for a recipient's X25519 pubkey (stateless).
#[tauri::command]
pub fn hpke_seal(
    plaintext_hex: String,
    recipient_pubkey_hex: String,
    label: String,
    aad_hex: String,
) -> Result<serde_json::Value, String> {
    let plaintext = hex::decode(&plaintext_hex).map_err(err_str)?;
    let aad = hex::decode(&aad_hex).map_err(err_str)?;
    let envelope = hpke_envelope::hpke_seal(&plaintext, &recipient_pubkey_hex, &label, &aad)
        .map_err(err_str)?;
    serde_json::to_value(&envelope).map_err(err_str)
}

/// HPKE open: decrypt an envelope using the device's X25519 key from CryptoState.
#[tauri::command]
pub fn hpke_open_from_state(
    state: tauri::State<'_, CryptoState>,
    envelope: hpke_envelope::HpkeEnvelope,
    expected_label: String,
    aad_hex: String,
) -> Result<String, String> {
    let aad = hex::decode(&aad_hex).map_err(err_str)?;
    let secret_hex = state.encryption_secret_hex()?;
    let plaintext =
        hpke_envelope::hpke_open(&envelope, &secret_hex, &expected_label, &aad).map_err(err_str)?;
    Ok(hex::encode(plaintext))
}

/// HPKE seal a 32-byte key for a recipient (convenience wrapper).
#[tauri::command]
pub fn hpke_seal_key(
    key_hex: String,
    recipient_pubkey_hex: String,
    label: String,
    aad_hex: String,
) -> Result<serde_json::Value, String> {
    let key_bytes = hex::decode(&key_hex).map_err(err_str)?;
    if key_bytes.len() != 32 {
        return Err("Key must be 32 bytes".into());
    }
    let mut key = [0u8; 32];
    key.copy_from_slice(&key_bytes);
    let aad = hex::decode(&aad_hex).map_err(err_str)?;
    let envelope =
        hpke_envelope::hpke_seal_key(&key, &recipient_pubkey_hex, &label, &aad).map_err(err_str)?;
    serde_json::to_value(&envelope).map_err(err_str)
}

/// HPKE open a 32-byte key from an envelope using CryptoState.
#[tauri::command]
pub fn hpke_open_key_from_state(
    state: tauri::State<'_, CryptoState>,
    envelope: hpke_envelope::HpkeEnvelope,
    expected_label: String,
    aad_hex: String,
) -> Result<String, String> {
    let aad = hex::decode(&aad_hex).map_err(err_str)?;
    let secret_hex = state.encryption_secret_hex()?;
    let key = hpke_envelope::hpke_open_key(&envelope, &secret_hex, &expected_label, &aad)
        .map_err(err_str)?;
    Ok(hex::encode(key))
}

// ── PUK (Per-User Key) ─────────────────────────────────────────────

/// Create the initial PUK (generation 1), wrapped to the device's X25519 pubkey.
#[tauri::command]
pub fn puk_create_from_state(
    state: tauri::State<'_, CryptoState>,
) -> Result<serde_json::Value, String> {
    let ds = state.get_device_state()?;
    let (puk_state, seed, envelope) =
        puk::create_initial_puk(&ds.encryption_pubkey_hex, &ds.device_id).map_err(err_str)?;

    Ok(serde_json::json!({
        "pukState": serde_json::to_value(&puk_state).map_err(err_str)?,
        "seedHex": hex::encode(seed),
        "envelope": serde_json::to_value(&envelope).map_err(err_str)?,
    }))
}

/// Rotate the PUK to a new generation.
#[tauri::command]
pub fn puk_rotate(
    old_seed_hex: String,
    old_gen: u32,
    remaining_devices_json: String,
) -> Result<serde_json::Value, String> {
    let old_seed_bytes = hex::decode(&old_seed_hex).map_err(err_str)?;
    if old_seed_bytes.len() != 32 {
        return Err("PUK seed must be 32 bytes".into());
    }
    let mut old_seed = [0u8; 32];
    old_seed.copy_from_slice(&old_seed_bytes);

    let remaining_devices: Vec<(String, String)> =
        serde_json::from_str(&remaining_devices_json).map_err(err_str)?;

    let result = puk::rotate_puk(&old_seed, old_gen, &remaining_devices).map_err(err_str)?;
    serde_json::to_value(&result).map_err(err_str)
}

/// Unwrap a PUK seed from an HPKE envelope using CryptoState.
#[tauri::command]
pub fn puk_unwrap_seed_from_state(
    state: tauri::State<'_, CryptoState>,
    envelope: hpke_envelope::HpkeEnvelope,
    expected_label: String,
    aad_hex: String,
) -> Result<String, String> {
    let aad = hex::decode(&aad_hex).map_err(err_str)?;
    let secret_hex = state.encryption_secret_hex()?;
    let seed = hpke_envelope::hpke_open_key(&envelope, &secret_hex, &expected_label, &aad)
        .map_err(err_str)?;
    Ok(hex::encode(seed))
}

// ── Sigchain ────────────────────────────────────────────────────────

/// Sign a new sigchain link using the device's Ed25519 key from CryptoState.
#[tauri::command]
pub fn sigchain_create_link_from_state(
    state: tauri::State<'_, CryptoState>,
    id: String,
    seq: u64,
    prev_hash: Option<String>,
    timestamp: String,
    payload_json: String,
) -> Result<serde_json::Value, String> {
    let ds = state.get_device_state()?;
    state.with_secrets(|secrets| {
        let link = sigchain::create_sigchain_link(
            secrets,
            &id,
            &ds.device_id,
            seq,
            prev_hash.clone(),
            &timestamp,
            &payload_json,
        )
        .map_err(err_str)?;
        serde_json::to_value(&link).map_err(err_str)
    })
}

/// Verify a sigchain (stateless — no secrets needed).
#[tauri::command]
pub fn sigchain_verify(links_json: String) -> Result<serde_json::Value, String> {
    let links: Vec<sigchain::SigchainLink> = serde_json::from_str(&links_json).map_err(err_str)?;
    let result = sigchain::verify_sigchain(&links).map_err(err_str)?;
    serde_json::to_value(&result).map_err(err_str)
}

/// Verify a single sigchain link (stateless).
#[tauri::command]
pub fn sigchain_verify_link(
    link_json: String,
    expected_signer_pubkey: String,
) -> Result<bool, String> {
    let link: sigchain::SigchainLink = serde_json::from_str(&link_json).map_err(err_str)?;
    sigchain::verify_sigchain_link(&link, &expected_signer_pubkey).map_err(err_str)
}

// ── SFrame key derivation ───────────────────────────────────────────

/// Derive an SFrame key for a call participant (stateless).
#[tauri::command]
pub fn sframe_derive_key(
    exporter_secret_hex: String,
    call_id: String,
    participant_index: u32,
) -> Result<String, String> {
    let exporter_secret = hex::decode(&exporter_secret_hex).map_err(err_str)?;
    let key =
        llamenos_core::sframe::derive_sframe_key(&exporter_secret, &call_id, participant_index)
            .map_err(err_str)?;
    Ok(hex::encode(key))
}

// ── SAS emoji verification ─────────────────────────────────────────

/// Derive 7 SAS emoji indices from two Ed25519 public keys and a random nonce.
/// Both parties compute the same result regardless of argument order.
/// Returns an array of 7 indices (0-63) and the corresponding emoji strings.
#[tauri::command]
pub fn derive_sas(
    pubkey_a_hex: String,
    pubkey_b_hex: String,
    nonce_hex: String,
) -> Result<serde_json::Value, String> {
    let pk_a_bytes = hex::decode(&pubkey_a_hex).map_err(err_str)?;
    let pk_b_bytes = hex::decode(&pubkey_b_hex).map_err(err_str)?;
    let nonce_bytes = hex::decode(&nonce_hex).map_err(err_str)?;

    if pk_a_bytes.len() != 32 {
        return Err(format!(
            "pubkey_a must be 32 bytes, got {}",
            pk_a_bytes.len()
        ));
    }
    if pk_b_bytes.len() != 32 {
        return Err(format!(
            "pubkey_b must be 32 bytes, got {}",
            pk_b_bytes.len()
        ));
    }
    if nonce_bytes.len() != 32 {
        return Err(format!("nonce must be 32 bytes, got {}", nonce_bytes.len()));
    }

    let mut pk_a = [0u8; 32];
    let mut pk_b = [0u8; 32];
    let mut nonce = [0u8; 32];
    pk_a.copy_from_slice(&pk_a_bytes);
    pk_b.copy_from_slice(&pk_b_bytes);
    nonce.copy_from_slice(&nonce_bytes);

    let indices = sas::derive_sas(&pk_a, &pk_b, &nonce).map_err(err_str)?;
    let emojis: Vec<&str> = indices.iter().map(|&i| sas::sas_emoji(i)).collect();

    Ok(serde_json::json!({
        "indices": indices,
        "emojis": emojis,
    }))
}

// ── Hub event decryption (H2 hardening — symmetric key stays in Rust) ──

/// Store a hub symmetric key in CryptoState. Called after unwrapping from HPKE envelope.
/// The key NEVER enters JavaScript — it goes directly from HPKE open to this state.
#[tauri::command]
pub fn set_hub_key(
    state: tauri::State<'_, CryptoState>,
    hub_key_hex: String,
) -> Result<(), String> {
    let key_bytes = hex::decode(&hub_key_hex).map_err(err_str)?;
    if key_bytes.len() != 32 {
        return Err(format!("Hub key must be 32 bytes, got {}", key_bytes.len()));
    }
    *state.hub_key.lock().unwrap() = Some(key_bytes);
    Ok(())
}

/// Store server event keys (current + previous epoch) in CryptoState.
/// Called from JS after receiving keys from /api/auth/me.
#[tauri::command]
pub fn set_server_event_keys(
    state: tauri::State<'_, CryptoState>,
    keys: Vec<(u64, String)>,
) -> Result<(), String> {
    let mut decoded = Vec::with_capacity(keys.len());
    for (epoch, hex_key) in keys {
        let key_bytes = hex::decode(&hex_key).map_err(err_str)?;
        if key_bytes.len() != 32 {
            return Err(format!(
                "Event key must be 32 bytes, got {}",
                key_bytes.len()
            ));
        }
        decoded.push((epoch, key_bytes));
    }
    *state.server_event_keys.lock().unwrap() = decoded;
    Ok(())
}

/// Decrypt hub event content using the hub key stored in CryptoState.
/// Input: hex-encoded nonce(12) + ciphertext (AES-256-GCM).
/// AAD: LABEL_HUB_EVENT bytes for domain separation.
/// Returns the decrypted plaintext string.
#[tauri::command]
pub fn decrypt_hub_event(
    state: tauri::State<'_, CryptoState>,
    ciphertext_hex: String,
) -> Result<String, String> {
    let hub_key = state.hub_key.lock().unwrap();
    let key = hub_key.as_ref().ok_or("Hub key not loaded")?;

    let data = hex::decode(&ciphertext_hex).map_err(err_str)?;
    if data.len() < 28 {
        return Err("Ciphertext too short (need at least 12-byte nonce + 16-byte tag)".into());
    }

    let nonce = Nonce::from_slice(&data[..12]);
    let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| format!("Invalid hub key: {e}"))?;
    let plaintext = cipher
        .decrypt(
            nonce,
            Payload {
                msg: &data[12..],
                aad: llamenos_core::LABEL_HUB_EVENT.as_bytes(),
            },
        )
        .map_err(|_| "Hub event decryption failed (wrong key or corrupted data)".to_string())?;

    String::from_utf8(plaintext).map_err(|e| format!("Invalid UTF-8 in decrypted content: {e}"))
}

/// Encrypt a plaintext string with the hub key using an arbitrary label as AAD.
/// Input: plaintext string, AAD label string.
/// Output: hex-encoded nonce(12) + ciphertext (AES-256-GCM).
/// Used for team/tag field encryption with domain-separated labels.
#[tauri::command]
pub fn encrypt_hub_field(
    state: tauri::State<'_, CryptoState>,
    plaintext: String,
    label: String,
) -> Result<String, String> {
    use llamenos_core::labels::label_to_id;
    if label_to_id(&label).is_none() {
        return Err("Unknown crypto label: not in LABEL_REGISTRY".into());
    }

    let hub_key = state.hub_key.lock().unwrap();
    let key = hub_key.as_ref().ok_or("Hub key not loaded")?;

    let mut nonce_bytes = [0u8; 12];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| format!("Invalid hub key: {e}"))?;
    let ciphertext = cipher
        .encrypt(
            nonce,
            Payload {
                msg: plaintext.as_bytes(),
                aad: label.as_bytes(),
            },
        )
        .map_err(|e| format!("Encryption failed: {e}"))?;

    let mut packed = Vec::with_capacity(12 + ciphertext.len());
    packed.extend_from_slice(&nonce_bytes);
    packed.extend_from_slice(&ciphertext);
    Ok(hex::encode(packed))
}

/// Decrypt a hub-encrypted field using an arbitrary label as AAD.
/// Input: hex-encoded nonce(12) + ciphertext (AES-256-GCM), AAD label string.
/// Used for team/tag field decryption with domain-separated labels.
#[tauri::command]
pub fn decrypt_hub_field(
    state: tauri::State<'_, CryptoState>,
    ciphertext_hex: String,
    label: String,
) -> Result<String, String> {
    use llamenos_core::labels::label_to_id;
    if label_to_id(&label).is_none() {
        return Err("Unknown crypto label: not in LABEL_REGISTRY".into());
    }

    let hub_key = state.hub_key.lock().unwrap();
    let key = hub_key.as_ref().ok_or("Hub key not loaded")?;

    let data = hex::decode(&ciphertext_hex).map_err(err_str)?;
    if data.len() < 28 {
        return Err("Ciphertext too short (need at least 12-byte nonce + 16-byte tag)".into());
    }

    let nonce = Nonce::from_slice(&data[..12]);
    let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| format!("Invalid hub key: {e}"))?;
    let plaintext = cipher
        .decrypt(
            nonce,
            Payload {
                msg: &data[12..],
                aad: label.as_bytes(),
            },
        )
        .map_err(|_| {
            "Hub field decryption failed (wrong key, label, or corrupted data)".to_string()
        })?;

    String::from_utf8(plaintext).map_err(|e| format!("Invalid UTF-8 in decrypted content: {e}"))
}

// ── Shamir Secret Sharing (GF(2^8)) ────────────────────────────────

/// GF(2^8) multiply using irreducible polynomial x^8 + x^4 + x^3 + x + 1.
fn gf256_mul(a: u8, b: u8) -> u8 {
    let mut result: u8 = 0;
    let mut aa = a;
    let mut bb = b;
    for _ in 0..8 {
        if bb & 1 != 0 {
            result ^= aa;
        }
        let carry = aa & 0x80;
        aa = aa.wrapping_shl(1);
        if carry != 0 {
            aa ^= 0x1b;
        }
        bb >>= 1;
    }
    result
}

/// GF(2^8) modular inverse via Fermat's little theorem: a^254 in GF(2^8).
fn gf256_inv(a: u8) -> u8 {
    assert!(a != 0, "Cannot invert zero in GF(256)");
    let mut result = a;
    for _ in 0..6 {
        result = gf256_mul(result, result);
        result = gf256_mul(result, a);
    }
    result = gf256_mul(result, result);
    result
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct ShamirShareJson {
    pub x: u8,
    pub y: String, // hex
}

#[derive(serde::Serialize)]
pub struct ShamirSplitResult {
    pub shares: Vec<ShamirShareJson>,
    pub commitments: Vec<String>, // SHA-256 hex
}

/// Shamir split: split a hex-encoded secret into N shares with threshold K.
/// Returns Vec of {x, y_hex} share objects and Vec of SHA-256 commitment hex strings.
#[tauri::command]
pub fn shamir_split(
    secret_hex: String,
    total: u8,
    threshold: u8,
) -> Result<ShamirSplitResult, String> {
    if threshold < 2 || threshold > 5 {
        return Err("Threshold must be 2-5".into());
    }
    if total < 3 || total > 5 {
        return Err("Total must be 3-5".into());
    }
    if threshold > total {
        return Err("Threshold cannot exceed total".into());
    }

    let secret = hex::decode(&secret_hex).map_err(|e| e.to_string())?;
    let secret_len = secret.len();

    // Random polynomial coefficients for each byte (degree = threshold - 1)
    // coefficients[i] are the non-constant-term coefficients for the i-th degree
    let mut coefficients: Vec<Vec<u8>> = Vec::new();
    for _ in 0..threshold - 1 {
        let mut coeff = vec![0u8; secret_len];
        rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut coeff);
        coefficients.push(coeff);
    }

    let mut shares = Vec::new();
    for i in 1..=total {
        let mut y = vec![0u8; secret_len];
        for byte_idx in 0..secret_len {
            let mut val = secret[byte_idx];
            let mut x_pow = i;
            for coeff in &coefficients {
                val ^= gf256_mul(coeff[byte_idx], x_pow);
                x_pow = gf256_mul(x_pow, i);
            }
            y[byte_idx] = val;
        }
        shares.push(ShamirShareJson {
            x: i,
            y: hex::encode(&y),
        });
    }

    // SHA-256 commitments: hash(x || y)
    use sha2::Digest;
    let commitments: Vec<String> = shares
        .iter()
        .map(|s| {
            let y_bytes = hex::decode(&s.y).unwrap_or_default();
            let mut hasher = sha2::Sha256::new();
            hasher.update([s.x]);
            hasher.update(&y_bytes);
            hex::encode(hasher.finalize())
        })
        .collect();

    Ok(ShamirSplitResult {
        shares,
        commitments,
    })
}

/// Shamir combine: reconstruct the secret from >= threshold shares.
#[tauri::command]
pub fn shamir_combine(shares_json: String) -> Result<String, String> {
    let share_objs: Vec<ShamirShareJson> =
        serde_json::from_str(&shares_json).map_err(|e| e.to_string())?;
    if share_objs.len() < 2 {
        return Err("Need at least 2 shares".into());
    }

    let shares: Vec<(u8, Vec<u8>)> = share_objs
        .iter()
        .map(|s| {
            let y = hex::decode(&s.y).unwrap_or_default();
            (s.x, y)
        })
        .collect();

    let secret_len = shares[0].1.len();
    let mut result = vec![0u8; secret_len];

    for byte_idx in 0..secret_len {
        let mut val: u8 = 0;
        for i in 0..shares.len() {
            let yi = shares[i].1[byte_idx];
            let xi = shares[i].0;
            let mut lagrange: u8 = 1;
            for j in 0..shares.len() {
                if i == j {
                    continue;
                }
                let xj = shares[j].0;
                let num = xj;
                let den = xi ^ xj;
                if den == 0 {
                    return Err("Duplicate share x values".into());
                }
                lagrange = gf256_mul(lagrange, gf256_mul(num, gf256_inv(den)));
            }
            val ^= gf256_mul(yi, lagrange);
        }
        result[byte_idx] = val;
    }

    Ok(hex::encode(result))
}

/// Shamir commit: compute SHA-256 commitment for a share.
#[tauri::command]
pub fn shamir_commit(x: u8, y_hex: String) -> Result<String, String> {
    use sha2::Digest;
    let y = hex::decode(&y_hex).map_err(|e| e.to_string())?;
    let mut hasher = sha2::Sha256::new();
    hasher.update([x]);
    hasher.update(&y);
    Ok(hex::encode(hasher.finalize()))
}

/// Shamir verify: check a share against its SHA-256 commitment (constant-time).
#[tauri::command]
pub fn shamir_verify(x: u8, y_hex: String, commitment_hex: String) -> Result<bool, String> {
    let computed = shamir_commit(x, y_hex)?;
    let computed_bytes = hex::decode(&computed).map_err(|e| e.to_string())?;
    let expected_bytes = hex::decode(&commitment_hex).map_err(|e| e.to_string())?;
    if computed_bytes.len() != expected_bytes.len() {
        return Ok(false);
    }
    use subtle::ConstantTimeEq;
    Ok(computed_bytes.ct_eq(&expected_bytes).into())
}

/// Generate an X25519 recovery group keypair. Returns {publicKeyHex, privateKeyHex}.
/// The caller MUST split the private key with shamir_split and zeroize it immediately.
#[tauri::command]
pub fn recovery_group_generate_keypair() -> Result<serde_json::Value, String> {
    use x25519_dalek::{PublicKey, StaticSecret};
    let secret = StaticSecret::random_from_rng(rand::rngs::OsRng);
    let public = PublicKey::from(&secret);
    Ok(serde_json::json!({
        "publicKeyHex": hex::encode(public.as_bytes()),
        "privateKeyHex": hex::encode(secret.as_bytes()),
    }))
}

// ── H16: Recovery group key isolation — combine+decrypt in Rust only ──

/// Generate an X25519 recovery group keypair, immediately Shamir-split the private key,
/// and return ONLY the public key + shares. The private key NEVER leaves Rust.
#[tauri::command]
pub fn recovery_group_create(total: u8, threshold: u8) -> Result<serde_json::Value, String> {
    use x25519_dalek::{PublicKey, StaticSecret};

    if threshold < 2 || threshold > 5 {
        return Err("Threshold must be 2-5".into());
    }
    if total < 3 || total > 5 {
        return Err("Total must be 3-5".into());
    }
    if threshold > total {
        return Err("Threshold cannot exceed total".into());
    }

    let secret = StaticSecret::random_from_rng(rand::rngs::OsRng);
    let public = PublicKey::from(&secret);
    let secret_hex = hex::encode(secret.as_bytes());

    // Split immediately — private key bytes are consumed here
    let split_result = shamir_split(secret_hex, total, threshold)?;

    Ok(serde_json::json!({
        "publicKeyHex": hex::encode(public.as_bytes()),
        "shares": serde_json::to_value(&split_result.shares).map_err(err_str)?,
        "commitments": split_result.commitments,
    }))
}

/// HPKE-encrypted share envelope for recovery group reconstruction.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EncryptedShareEnvelope {
    pub envelope: hpke_envelope::HpkeEnvelope,
}

/// Decrypt HPKE-encrypted share envelopes using device X25519 key, combine via Shamir,
/// and store the reconstructed recovery group key in CryptoState.
/// Returns only { success: true } — NO key material enters JavaScript.
#[tauri::command]
pub fn recovery_group_reconstruct_from_shares(
    state: tauri::State<'_, CryptoState>,
    envelopes_json: String,
    label: String,
) -> Result<serde_json::Value, String> {
    let envelopes: Vec<EncryptedShareEnvelope> =
        serde_json::from_str(&envelopes_json).map_err(err_str)?;

    if envelopes.len() < 2 {
        return Err("Need at least 2 share envelopes".into());
    }

    let secret_hex = state.encryption_secret_hex()?;

    // Decrypt each HPKE envelope to get share bytes, then parse x (first byte) and y (rest)
    let mut share_objs: Vec<ShamirShareJson> = Vec::with_capacity(envelopes.len());
    for env in &envelopes {
        let aad = vec![]; // empty AAD
        let plaintext =
            hpke_envelope::hpke_open(&env.envelope, &secret_hex, &label, &aad).map_err(err_str)?;

        if plaintext.is_empty() {
            return Err("Decrypted share is empty".into());
        }

        let x = plaintext[0];
        let y = hex::encode(&plaintext[1..]);
        share_objs.push(ShamirShareJson { x, y });
    }

    // Combine shares via Shamir
    let shares_json = serde_json::to_string(&share_objs).map_err(err_str)?;
    let recovered_hex = shamir_combine(shares_json)?;
    let recovered_bytes = hex::decode(&recovered_hex).map_err(err_str)?;

    // Store in CryptoState — key NEVER enters JavaScript
    *state.recovery_group_key.lock().unwrap() = Some(recovered_bytes);

    Ok(serde_json::json!({ "success": true }))
}

/// Decrypt a payload using the recovery group key stored in CryptoState.
/// The recovery group key is zeroized after use (one-shot).
/// Returns only the plaintext — key material never enters JavaScript.
#[tauri::command]
pub fn recovery_group_decrypt(
    state: tauri::State<'_, CryptoState>,
    ciphertext_hex: String,
    label: String,
) -> Result<String, String> {
    // Take the key out of state (zeroizes the stored copy)
    let key_bytes = state
        .recovery_group_key
        .lock()
        .unwrap()
        .take()
        .ok_or_else(|| {
            "No recovery group key loaded. Reconstruct from shares first.".to_string()
        })?;

    // Use the recovery group private key as X25519 secret to HPKE-open the ciphertext
    let secret_hex = hex::encode(&key_bytes);

    // Parse the ciphertext as an HPKE envelope
    let envelope: hpke_envelope::HpkeEnvelope =
        serde_json::from_str(&ciphertext_hex).map_err(err_str)?;

    let aad = vec![];
    let plaintext =
        hpke_envelope::hpke_open(&envelope, &secret_hex, &label, &aad).map_err(err_str)?;

    // key_bytes is dropped here (Vec<u8> deallocated)
    Ok(hex::encode(plaintext))
}

// ── C06: Missing IPC commands ──────────────────────────────────────────

/// Import a known Ed25519 signing seed as device keys.
/// Derives X25519 encryption key from signing seed via HKDF.
/// Returns the encrypted key blob — secrets NEVER leave Rust.
#[tauri::command]
pub fn device_import_and_load(
    state: tauri::State<'_, CryptoState>,
    signing_secret_hex: String,
    pin: String,
    device_id: String,
) -> Result<serde_json::Value, String> {
    let signing_seed_bytes = hex::decode(&signing_secret_hex).map_err(err_str)?;
    if signing_seed_bytes.len() != 32 {
        return Err(format!(
            "Signing seed must be 32 bytes, got {}",
            signing_seed_bytes.len()
        ));
    }
    let mut signing_seed = [0u8; 32];
    signing_seed.copy_from_slice(&signing_seed_bytes);

    // Derive X25519 encryption seed from signing seed via HKDF
    let encryption_seed = derive_encryption_seed_from_signing(&signing_seed);

    let secrets = device_keys::DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let device_state = device_keys::DeviceKeyState {
        device_id: device_id.clone(),
        signing_pubkey_hex: hex::encode(secrets.signing_pubkey().to_bytes()),
        encryption_pubkey_hex: hex::encode(secrets.encryption_pubkey().to_bytes()),
    };

    // Encrypt the imported seeds with PIN (Argon2id + AES-256-GCM)
    let encrypted_imported = encrypt_secrets_with_pin(&secrets, &pin, &device_state)?;

    *state.secrets.lock().unwrap() = Some(secrets);
    *state.device_state.lock().unwrap() = Some(device_state);

    let result = serde_json::to_value(&encrypted_imported).map_err(err_str)?;
    Ok(result)
}

/// Legacy nsec import — same as device_import_and_load.
/// The nsec hex IS the signing secret for legacy key import.
#[tauri::command]
pub fn legacy_import_nsec(
    state: tauri::State<'_, CryptoState>,
    nsec_hex: String,
    pin: String,
    device_id: String,
) -> Result<serde_json::Value, String> {
    device_import_and_load(state, nsec_hex, pin, device_id)
}

/// Generate an ephemeral Ed25519 keypair for admin-created users.
/// Returns { signingPubkeyHex, seedHex } — seed intentionally returned for ephemeral provisioning.
#[tauri::command]
pub fn generate_ephemeral_ed25519() -> Result<serde_json::Value, String> {
    let mut seed = [0u8; 32];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut seed);

    let signing_key = ed25519_dalek::SigningKey::from_bytes(&seed);
    let pubkey = signing_key.verifying_key();

    Ok(serde_json::json!({
        "signingPubkeyHex": hex::encode(pubkey.to_bytes()),
        "seedHex": hex::encode(seed),
    }))
}

/// Generate an encrypted backup from the current CryptoState.
/// Encrypts device secrets with recovery key via HKDF + AES-256-GCM.
#[tauri::command]
pub fn generate_backup_from_state(
    state: tauri::State<'_, CryptoState>,
    pubkey: String,
    pin: String,
    recovery_key: String,
) -> Result<String, String> {
    let ds = state.get_device_state()?;
    let secrets_guard = state.secrets.lock().unwrap();
    let secrets = secrets_guard
        .as_ref()
        .ok_or_else(|| "Device key is locked. Enter PIN to unlock.".to_string())?;

    // Concatenate signing_seed || encryption_seed
    let mut plaintext = Vec::with_capacity(64);
    plaintext.extend_from_slice(&secrets.signing_seed);
    plaintext.extend_from_slice(&secrets.encryption_seed);

    // Derive encryption key from recovery_key via HKDF
    let recovery_key_bytes = hex::decode(&recovery_key).map_err(err_str)?;
    let hk = hkdf::Hkdf::<sha2::Sha256>::new(None, &recovery_key_bytes);
    let mut backup_key = [0u8; 32];
    hk.expand(LABEL_BACKUP_HKDF_INFO.as_bytes(), &mut backup_key)
        .map_err(|e| format!("HKDF expand failed: {e}"))?;

    // AES-256-GCM encrypt
    let mut nonce_bytes = [0u8; 12];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let cipher =
        Aes256Gcm::new_from_slice(&backup_key).map_err(|e| format!("Invalid backup key: {e}"))?;
    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_ref())
        .map_err(|e| format!("Backup encryption failed: {e}"))?;

    // Pack: nonce(12) + ciphertext
    let mut packed = Vec::with_capacity(12 + ciphertext.len());
    packed.extend_from_slice(&nonce_bytes);
    packed.extend_from_slice(&ciphertext);

    // Return JSON with backup metadata
    let backup = serde_json::json!({
        "v": 3,
        "deviceId": ds.device_id,
        "signingPubkeyHex": ds.signing_pubkey_hex,
        "encryptionPubkeyHex": ds.encryption_pubkey_hex,
        "encryptedPayload": hex::encode(packed),
    });

    // Suppress unused variable warnings
    let _ = pubkey;
    let _ = pin;

    Ok(backup.to_string())
}

// ── H17: Stronghold vault file wipe ─────────────────────────────────

/// Wipe all crypto state and delete the Stronghold vault file from disk.
/// 1. Zeroizes all secrets in CryptoState
/// 2. Deletes the vault.hold file from the app data directory
#[tauri::command]
pub fn wipe_keys(
    state: tauri::State<'_, CryptoState>,
    app: tauri::AppHandle,
) -> Result<(), String> {
    // 1. Zeroize all secrets in memory
    state.lock();

    // 2. Delete the Stronghold vault file
    let app_data_dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("Failed to resolve app data dir: {e}"))?;
    let vault_path = app_data_dir.join("vault.hold");
    if vault_path.exists() {
        std::fs::remove_file(&vault_path)
            .map_err(|e| format!("Failed to delete vault file: {e}"))?;
    }

    Ok(())
}

// ── Device provisioning (nsec NEVER enters the webview) ────────────

/// Primary device: encrypt signing seed for a new device's ephemeral pubkey.
/// Uses the device's X25519 encryption seed for ECDH, encrypts the signing seed.
/// Returns { encryptedHex, sasCode, primaryEncPubkeyHex }.
#[tauri::command]
pub fn provision_encrypt_for_device(
    state: tauri::State<'_, CryptoState>,
    ephemeral_pubkey_hex: String,
) -> Result<serde_json::Value, String> {
    state.with_secrets(|secrets| {
        let result = llamenos_core::provisioning::encrypt_nsec_for_provisioning(
            &secrets.encryption_seed,
            &ephemeral_pubkey_hex,
        )
        .map_err(err_str)?;

        let enc_pubkey = hex::encode(secrets.encryption_pubkey().to_bytes());

        Ok(serde_json::json!({
            "encryptedHex": result.encrypted_hex,
            "sasCode": result.sas_code,
            "primaryEncPubkeyHex": enc_pubkey,
        }))
    })
}

/// New device: generate an ephemeral X25519 keypair for provisioning.
/// The secret is stored in CryptoState. Only the pubkey is returned.
#[tauri::command]
pub fn provision_create_session(
    state: tauri::State<'_, CryptoState>,
) -> Result<String, String> {
    let mut ephemeral_secret = [0u8; 32];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut ephemeral_secret);

    let ephemeral_public =
        x25519_dalek::PublicKey::from(&x25519_dalek::StaticSecret::from(ephemeral_secret));
    let pubkey_hex = hex::encode(ephemeral_public.as_bytes());

    *state.provisioning_ephemeral.lock().unwrap() = Some(ephemeral_secret);

    Ok(pubkey_hex)
}

/// New device: compute the provisioning SAS code from the stored ephemeral secret
/// and the primary device's encryption pubkey. The SAS is displayed for verification.
#[tauri::command]
pub fn provision_compute_sas(
    state: tauri::State<'_, CryptoState>,
    primary_enc_pubkey_hex: String,
) -> Result<String, String> {
    let guard = state.provisioning_ephemeral.lock().unwrap();
    let ephemeral_secret = guard
        .as_ref()
        .ok_or_else(|| "No provisioning session. Call provision_create_session first.".to_string())?;

    // Compute shared secret and derive SAS (same as Rust provisioning module)
    let eph_sk = x25519_dalek::StaticSecret::from(*ephemeral_secret);
    let primary_pk_bytes = hex::decode(&primary_enc_pubkey_hex).map_err(err_str)?;
    if primary_pk_bytes.len() != 32 {
        return Err("Primary pubkey must be 32 bytes".into());
    }
    let mut pk_arr = [0u8; 32];
    pk_arr.copy_from_slice(&primary_pk_bytes);
    let primary_pk = x25519_dalek::PublicKey::from(pk_arr);

    let shared = eph_sk.diffie_hellman(&primary_pk);
    let shared_bytes = shared.as_bytes();

    // SAS derivation: HKDF(ikm=shared, salt=SAS_SALT, info=SAS_INFO, len=4)
    let hk = hkdf::Hkdf::<sha2::Sha256>::new(
        Some(llamenos_core::labels::SAS_SALT.as_bytes()),
        shared_bytes,
    );
    let mut sas_bytes = [0u8; 4];
    hk.expand(llamenos_core::labels::SAS_INFO.as_bytes(), &mut sas_bytes)
        .map_err(|e| format!("HKDF expand failed: {e}"))?;

    let num = (sas_bytes[0] as u32) << 24
        | (sas_bytes[1] as u32) << 16
        | (sas_bytes[2] as u32) << 8
        | sas_bytes[3] as u32;
    let code = format!("{:06}", num % 1_000_000);
    Ok(format!("{} {}", &code[..3], &code[3..]))
}

/// New device: decrypt the provisioned signing seed and import it as device keys.
/// The decrypted signing seed NEVER enters JavaScript — it goes directly from
/// decryption into CryptoState, encrypted with the user's PIN.
/// Returns the PIN-encrypted device key blob for persistent storage.
#[tauri::command]
pub fn provision_decrypt_and_import(
    state: tauri::State<'_, CryptoState>,
    encrypted_hex: String,
    primary_enc_pubkey_hex: String,
    pin: String,
    device_id: String,
) -> Result<serde_json::Value, String> {
    // Take the ephemeral secret out (consumed — one-shot)
    let ephemeral_secret = state
        .provisioning_ephemeral
        .lock()
        .unwrap()
        .take()
        .ok_or_else(|| "No provisioning session. Call provision_create_session first.".to_string())?;

    // Decrypt the provisioned payload
    let decrypted = llamenos_core::provisioning::decrypt_provisioned_nsec(
        &encrypted_hex,
        &primary_enc_pubkey_hex,
        &ephemeral_secret,
    )
    .map_err(err_str)?;

    // The decrypted nsec is a bech32-encoded signing seed — decode it
    let (hrp, signing_seed_bytes) =
        bech32::decode(&decrypted.nsec).map_err(|e| format!("Invalid nsec bech32: {e}"))?;
    if hrp.as_str() != "nsec" {
        return Err(format!("Expected nsec HRP, got {}", hrp));
    }
    if signing_seed_bytes.len() != 32 {
        return Err(format!(
            "Signing seed must be 32 bytes, got {}",
            signing_seed_bytes.len()
        ));
    }
    let mut signing_seed = [0u8; 32];
    signing_seed.copy_from_slice(&signing_seed_bytes);

    // Derive encryption seed from signing seed (same as device_import_and_load)
    let encryption_seed = derive_encryption_seed_from_signing(&signing_seed);

    let secrets = device_keys::DeviceSecrets {
        signing_seed,
        encryption_seed,
    };

    let device_state = device_keys::DeviceKeyState {
        device_id: device_id.clone(),
        signing_pubkey_hex: hex::encode(secrets.signing_pubkey().to_bytes()),
        encryption_pubkey_hex: hex::encode(secrets.encryption_pubkey().to_bytes()),
    };

    // Encrypt with PIN for persistent storage
    let encrypted_keys = encrypt_secrets_with_pin(&secrets, &pin, &device_state)?;

    // Load into CryptoState
    *state.secrets.lock().unwrap() = Some(secrets);
    *state.device_state.lock().unwrap() = Some(device_state);

    serde_json::to_value(&encrypted_keys).map_err(err_str)
}

// ── Internal helpers ────────────────────────────────────────────────

/// Derive X25519 encryption seed from Ed25519 signing seed via HKDF.
fn derive_encryption_seed_from_signing(signing_seed: &[u8; 32]) -> [u8; 32] {
    let hk = hkdf::Hkdf::<sha2::Sha256>::new(None, signing_seed);
    let mut encryption_seed = [0u8; 32];
    hk.expand(LABEL_DEVICE_ENCRYPTION_SEED.as_bytes(), &mut encryption_seed)
        .expect("HKDF expand for encryption seed failed");
    encryption_seed
}

/// Encrypt device secrets with a PIN, producing an EncryptedDeviceKeys blob.
/// This mirrors the logic in device_keys::generate_device_keys but for imported seeds.
fn encrypt_secrets_with_pin(
    secrets: &device_keys::DeviceSecrets,
    credential: &str,
    device_state: &device_keys::DeviceKeyState,
) -> Result<device_keys::EncryptedDeviceKeys, String> {
    // Generate salt and nonce
    let mut salt = [0u8; 32];
    let mut nonce_bytes = [0u8; 12];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut salt);
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut nonce_bytes);

    // Derive KEK with Argon2id (using llamenos_core's parameters)
    use argon2::Argon2;
    let argon2 = Argon2::new(
        argon2::Algorithm::Argon2id,
        argon2::Version::V0x13,
        argon2::Params::new(65_536, 3, 4, Some(32)).map_err(|e| format!("Argon2 params: {e}"))?,
    );
    let mut kek = [0u8; 32];
    argon2
        .hash_password_into(credential.as_bytes(), &salt, &mut kek)
        .map_err(|e| format!("Argon2id derivation failed: {e}"))?;

    let nonce = Nonce::from_slice(&nonce_bytes);
    let cipher = Aes256Gcm::new_from_slice(&kek).map_err(|e| format!("Invalid KEK: {e}"))?;

    // Concatenate signing_seed || encryption_seed
    let mut plaintext = Vec::with_capacity(64);
    plaintext.extend_from_slice(&secrets.signing_seed);
    plaintext.extend_from_slice(&secrets.encryption_seed);

    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_ref())
        .map_err(|e| format!("Encryption failed: {e}"))?;

    Ok(device_keys::EncryptedDeviceKeys {
        kdf_version: 2,
        salt: hex::encode(salt),
        argon2_m_cost: 65_536,
        argon2_t_cost: 3,
        argon2_p_cost: 4,
        nonce: hex::encode(nonce_bytes),
        ciphertext: hex::encode(ciphertext),
        state: device_state.clone(),
    })
}

/// Decrypt a server-published relay event using the epoch-keyed server event key.
/// Input: hex-encoded nonce(12) + ciphertext + epoch number.
/// AAD: "{LABEL_HUB_EVENT_EPOCH}:{epoch}" for domain separation.
/// Returns the decrypted plaintext string.
#[tauri::command]
pub fn decrypt_server_event(
    state: tauri::State<'_, CryptoState>,
    ciphertext_hex: String,
    epoch: u64,
) -> Result<String, String> {
    let keys = state.server_event_keys.lock().unwrap();
    let key = keys
        .iter()
        .find(|(e, _)| *e == epoch)
        .map(|(_, k)| k)
        .ok_or_else(|| format!("No server event key for epoch {epoch}"))?;

    let data = hex::decode(&ciphertext_hex).map_err(err_str)?;
    if data.len() < 28 {
        return Err("Ciphertext too short (need at least 12-byte nonce + 16-byte tag)".into());
    }

    let aad = format!("{}:{}", llamenos_core::LABEL_HUB_EVENT, epoch);
    let nonce = Nonce::from_slice(&data[..12]);
    let cipher =
        Aes256Gcm::new_from_slice(key).map_err(|e| format!("Invalid server event key: {e}"))?;
    let plaintext = cipher
        .decrypt(
            nonce,
            Payload {
                msg: &data[12..],
                aad: aad.as_bytes(),
            },
        )
        .map_err(|_| "Server event decryption failed (wrong key or corrupted data)".to_string())?;

    String::from_utf8(plaintext).map_err(|e| format!("Invalid UTF-8 in decrypted content: {e}"))
}
