default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :beta do
    upload_to_testflight(
      ipa: "../build/export/Llamenos.ipa",
      skip_waiting_for_build_processing: true
    )
  end

  desc "Submit to App Store Review"
  lane :release do
    upload_to_app_store(
      ipa: "../build/export/Llamenos.ipa",
      submit_for_review: true,
      automatic_release: false,
      force: true
    )
  end
end
