// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package org.llamenos.core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_llamenos_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_llamenos_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "llamenos_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}




































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "llamenos_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_llamenos_core_fn_func_create_auth_token(`secretKeyHex`: RustBuffer.ByValue,`timestamp`: Long,`method`: RustBuffer.ByValue,`path`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_decrypt_call_record_for_reader(`encryptedContent`: RustBuffer.ByValue,`adminEnvelopes`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,`readerPubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_decrypt_draft(`packedHex`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_decrypt_message_for_reader(`encryptedContent`: RustBuffer.ByValue,`readerEnvelopes`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,`readerPubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_decrypt_note(`encryptedContent`: RustBuffer.ByValue,`envelope`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_decrypt_with_pin(`data`: RustBuffer.ByValue,`pin`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_derive_kek_hex(`pin`: RustBuffer.ByValue,`saltHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_ecies_unwrap_key_hex(`envelope`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,`label`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_ecies_wrap_key_hex(`keyHex`: RustBuffer.ByValue,`recipientPubkeyHex`: RustBuffer.ByValue,`label`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_encrypt_draft(`plaintext`: RustBuffer.ByValue,`secretKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_encrypt_message_for_readers(`plaintext`: RustBuffer.ByValue,`readerPubkeys`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_encrypt_note_for_recipients(`payloadJson`: RustBuffer.ByValue,`authorPubkey`: RustBuffer.ByValue,`adminPubkeys`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_encrypt_with_pin(`nsec`: RustBuffer.ByValue,`pin`: RustBuffer.ByValue,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_generate_keypair(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_get_public_key(`secretKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_is_valid_nsec(`nsec`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_llamenos_core_fn_func_is_valid_pin(`pin`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_llamenos_core_fn_func_keypair_from_nsec(`nsec`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_random_bytes_hex(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_llamenos_core_fn_func_verify_auth_token(`token`: RustBuffer.ByValue,`method`: RustBuffer.ByValue,`path`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_llamenos_core_fn_func_verify_schnorr(`messageHex`: RustBuffer.ByValue,`signatureHex`: RustBuffer.ByValue,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_llamenos_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_llamenos_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_llamenos_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_llamenos_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_llamenos_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_llamenos_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_llamenos_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_llamenos_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_llamenos_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_llamenos_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_llamenos_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_llamenos_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_llamenos_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_llamenos_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_llamenos_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_llamenos_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_llamenos_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_llamenos_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_llamenos_core_checksum_func_create_auth_token(
    ): Short
    fun uniffi_llamenos_core_checksum_func_decrypt_call_record_for_reader(
    ): Short
    fun uniffi_llamenos_core_checksum_func_decrypt_draft(
    ): Short
    fun uniffi_llamenos_core_checksum_func_decrypt_message_for_reader(
    ): Short
    fun uniffi_llamenos_core_checksum_func_decrypt_note(
    ): Short
    fun uniffi_llamenos_core_checksum_func_decrypt_with_pin(
    ): Short
    fun uniffi_llamenos_core_checksum_func_derive_kek_hex(
    ): Short
    fun uniffi_llamenos_core_checksum_func_ecies_unwrap_key_hex(
    ): Short
    fun uniffi_llamenos_core_checksum_func_ecies_wrap_key_hex(
    ): Short
    fun uniffi_llamenos_core_checksum_func_encrypt_draft(
    ): Short
    fun uniffi_llamenos_core_checksum_func_encrypt_message_for_readers(
    ): Short
    fun uniffi_llamenos_core_checksum_func_encrypt_note_for_recipients(
    ): Short
    fun uniffi_llamenos_core_checksum_func_encrypt_with_pin(
    ): Short
    fun uniffi_llamenos_core_checksum_func_generate_keypair(
    ): Short
    fun uniffi_llamenos_core_checksum_func_get_public_key(
    ): Short
    fun uniffi_llamenos_core_checksum_func_is_valid_nsec(
    ): Short
    fun uniffi_llamenos_core_checksum_func_is_valid_pin(
    ): Short
    fun uniffi_llamenos_core_checksum_func_keypair_from_nsec(
    ): Short
    fun uniffi_llamenos_core_checksum_func_random_bytes_hex(
    ): Short
    fun uniffi_llamenos_core_checksum_func_verify_auth_token(
    ): Short
    fun uniffi_llamenos_core_checksum_func_verify_schnorr(
    ): Short
    fun ffi_llamenos_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_llamenos_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_llamenos_core_checksum_func_create_auth_token() != 62800.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_decrypt_call_record_for_reader() != 10926.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_decrypt_draft() != 55174.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_decrypt_message_for_reader() != 24819.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_decrypt_note() != 17791.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_decrypt_with_pin() != 5372.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_derive_kek_hex() != 32027.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_ecies_unwrap_key_hex() != 45205.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_ecies_wrap_key_hex() != 31485.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_encrypt_draft() != 50495.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_encrypt_message_for_readers() != 63610.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_encrypt_note_for_recipients() != 14883.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_encrypt_with_pin() != 63866.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_generate_keypair() != 4768.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_get_public_key() != 41631.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_is_valid_nsec() != 41860.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_is_valid_pin() != 65518.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_keypair_from_nsec() != 313.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_random_bytes_hex() != 19039.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_verify_auth_token() != 39412.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_llamenos_core_checksum_func_verify_schnorr() != 51139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * A signed authentication token.
 */
data class AuthToken (
    val `pubkey`: kotlin.String, 
    val `timestamp`: kotlin.ULong, 
    val `token`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAuthToken: FfiConverterRustBuffer<AuthToken> {
    override fun read(buf: ByteBuffer): AuthToken {
        return AuthToken(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: AuthToken) = (
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterULong.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`token`)
    )

    override fun write(value: AuthToken, buf: ByteBuffer) {
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterULong.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`token`, buf)
    }
}



/**
 * Encrypted key data stored on disk (Stronghold on desktop, Keychain on mobile).
 */
data class EncryptedKeyData (
    /**
     * hex, 16 bytes
     */
    val `salt`: kotlin.String, 
    /**
     * PBKDF2 iteration count (600,000)
     */
    val `iterations`: kotlin.UInt, 
    /**
     * hex, 24 bytes (XChaCha20 nonce)
     */
    val `nonce`: kotlin.String, 
    /**
     * hex, encrypted nsec bech32 string
     */
    val `ciphertext`: kotlin.String, 
    /**
     * Truncated SHA-256 hash of pubkey (not plaintext) for identification
     */
    val `pubkey`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEncryptedKeyData: FfiConverterRustBuffer<EncryptedKeyData> {
    override fun read(buf: ByteBuffer): EncryptedKeyData {
        return EncryptedKeyData(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: EncryptedKeyData) = (
            FfiConverterString.allocationSize(value.`salt`) +
            FfiConverterUInt.allocationSize(value.`iterations`) +
            FfiConverterString.allocationSize(value.`nonce`) +
            FfiConverterString.allocationSize(value.`ciphertext`) +
            FfiConverterString.allocationSize(value.`pubkey`)
    )

    override fun write(value: EncryptedKeyData, buf: ByteBuffer) {
            FfiConverterString.write(value.`salt`, buf)
            FfiConverterUInt.write(value.`iterations`, buf)
            FfiConverterString.write(value.`nonce`, buf)
            FfiConverterString.write(value.`ciphertext`, buf)
            FfiConverterString.write(value.`pubkey`, buf)
    }
}



/**
 * Encrypted message with per-message key wrapped for each reader.
 */
data class EncryptedMessage (
    /**
     * hex: nonce(24) + ciphertext
     */
    val `encryptedContent`: kotlin.String, 
    /**
     * Message key wrapped for each reader (volunteer + admins)
     */
    val `readerEnvelopes`: List<RecipientKeyEnvelope>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEncryptedMessage: FfiConverterRustBuffer<EncryptedMessage> {
    override fun read(buf: ByteBuffer): EncryptedMessage {
        return EncryptedMessage(
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeRecipientKeyEnvelope.read(buf),
        )
    }

    override fun allocationSize(value: EncryptedMessage) = (
            FfiConverterString.allocationSize(value.`encryptedContent`) +
            FfiConverterSequenceTypeRecipientKeyEnvelope.allocationSize(value.`readerEnvelopes`)
    )

    override fun write(value: EncryptedMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`encryptedContent`, buf)
            FfiConverterSequenceTypeRecipientKeyEnvelope.write(value.`readerEnvelopes`, buf)
    }
}



/**
 * Encrypted note with per-note key wrapped for author + each admin.
 */
data class EncryptedNote (
    /**
     * hex: nonce(24) + ciphertext
     */
    val `encryptedContent`: kotlin.String, 
    /**
     * Note key wrapped for the author
     */
    val `authorEnvelope`: KeyEnvelope, 
    /**
     * Note key wrapped for each admin
     */
    val `adminEnvelopes`: List<RecipientKeyEnvelope>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEncryptedNote: FfiConverterRustBuffer<EncryptedNote> {
    override fun read(buf: ByteBuffer): EncryptedNote {
        return EncryptedNote(
            FfiConverterString.read(buf),
            FfiConverterTypeKeyEnvelope.read(buf),
            FfiConverterSequenceTypeRecipientKeyEnvelope.read(buf),
        )
    }

    override fun allocationSize(value: EncryptedNote) = (
            FfiConverterString.allocationSize(value.`encryptedContent`) +
            FfiConverterTypeKeyEnvelope.allocationSize(value.`authorEnvelope`) +
            FfiConverterSequenceTypeRecipientKeyEnvelope.allocationSize(value.`adminEnvelopes`)
    )

    override fun write(value: EncryptedNote, buf: ByteBuffer) {
            FfiConverterString.write(value.`encryptedContent`, buf)
            FfiConverterTypeKeyEnvelope.write(value.`authorEnvelope`, buf)
            FfiConverterSequenceTypeRecipientKeyEnvelope.write(value.`adminEnvelopes`, buf)
    }
}



/**
 * A symmetric key wrapped via ECIES for a single recipient.
 */
data class KeyEnvelope (
    /**
     * hex: nonce(24) + ciphertext(48 = 32 key + 16 tag)
     */
    val `wrappedKey`: kotlin.String, 
    /**
     * hex: compressed 33-byte ephemeral pubkey
     */
    val `ephemeralPubkey`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeKeyEnvelope: FfiConverterRustBuffer<KeyEnvelope> {
    override fun read(buf: ByteBuffer): KeyEnvelope {
        return KeyEnvelope(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: KeyEnvelope) = (
            FfiConverterString.allocationSize(value.`wrappedKey`) +
            FfiConverterString.allocationSize(value.`ephemeralPubkey`)
    )

    override fun write(value: KeyEnvelope, buf: ByteBuffer) {
            FfiConverterString.write(value.`wrappedKey`, buf)
            FfiConverterString.write(value.`ephemeralPubkey`, buf)
    }
}



/**
 * A secp256k1 keypair with Nostr bech32 encodings.
 */
data class KeyPair (
    /**
     * hex-encoded 32-byte secret key
     */
    val `secretKeyHex`: kotlin.String, 
    /**
     * hex-encoded 32-byte x-only public key
     */
    val `publicKey`: kotlin.String, 
    /**
     * bech32-encoded secret key (nsec1...)
     */
    val `nsec`: kotlin.String, 
    /**
     * bech32-encoded public key (npub1...)
     */
    val `npub`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeKeyPair: FfiConverterRustBuffer<KeyPair> {
    override fun read(buf: ByteBuffer): KeyPair {
        return KeyPair(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: KeyPair) = (
            FfiConverterString.allocationSize(value.`secretKeyHex`) +
            FfiConverterString.allocationSize(value.`publicKey`) +
            FfiConverterString.allocationSize(value.`nsec`) +
            FfiConverterString.allocationSize(value.`npub`)
    )

    override fun write(value: KeyPair, buf: ByteBuffer) {
            FfiConverterString.write(value.`secretKeyHex`, buf)
            FfiConverterString.write(value.`publicKey`, buf)
            FfiConverterString.write(value.`nsec`, buf)
            FfiConverterString.write(value.`npub`, buf)
    }
}



/**
 * A KeyEnvelope tagged with the recipient's pubkey (for multi-recipient scenarios).
 */
data class RecipientKeyEnvelope (
    /**
     * recipient's x-only pubkey (hex, 32 bytes / 64 hex chars)
     */
    val `pubkey`: kotlin.String, 
    /**
     * hex: nonce(24) + ciphertext(48)
     */
    val `wrappedKey`: kotlin.String, 
    /**
     * hex: compressed 33-byte ephemeral pubkey
     */
    val `ephemeralPubkey`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRecipientKeyEnvelope: FfiConverterRustBuffer<RecipientKeyEnvelope> {
    override fun read(buf: ByteBuffer): RecipientKeyEnvelope {
        return RecipientKeyEnvelope(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: RecipientKeyEnvelope) = (
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterString.allocationSize(value.`wrappedKey`) +
            FfiConverterString.allocationSize(value.`ephemeralPubkey`)
    )

    override fun write(value: RecipientKeyEnvelope, buf: ByteBuffer) {
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterString.write(value.`wrappedKey`, buf)
            FfiConverterString.write(value.`ephemeralPubkey`, buf)
    }
}





sealed class CryptoException(message: String): kotlin.Exception(message) {
        
        class InvalidSecretKey(message: String) : CryptoException(message)
        
        class InvalidPublicKey(message: String) : CryptoException(message)
        
        class InvalidEphemeralKey(message: String) : CryptoException(message)
        
        class EcdhFailed(message: String) : CryptoException(message)
        
        class EncryptionFailed(message: String) : CryptoException(message)
        
        class DecryptionFailed(message: String) : CryptoException(message)
        
        class HexException(message: String) : CryptoException(message)
        
        class InvalidNonce(message: String) : CryptoException(message)
        
        class InvalidCiphertext(message: String) : CryptoException(message)
        
        class KeyDerivationFailed(message: String) : CryptoException(message)
        
        class SignatureVerificationFailed(message: String) : CryptoException(message)
        
        class InvalidNsec(message: String) : CryptoException(message)
        
        class InvalidNpub(message: String) : CryptoException(message)
        
        class JsonException(message: String) : CryptoException(message)
        
        class WrongPin(message: String) : CryptoException(message)
        
        class InvalidPin(message: String) : CryptoException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CryptoException> {
        override fun lift(error_buf: RustBuffer.ByValue): CryptoException = FfiConverterTypeCryptoError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeCryptoError : FfiConverterRustBuffer<CryptoException> {
    override fun read(buf: ByteBuffer): CryptoException {
        
            return when(buf.getInt()) {
            1 -> CryptoException.InvalidSecretKey(FfiConverterString.read(buf))
            2 -> CryptoException.InvalidPublicKey(FfiConverterString.read(buf))
            3 -> CryptoException.InvalidEphemeralKey(FfiConverterString.read(buf))
            4 -> CryptoException.EcdhFailed(FfiConverterString.read(buf))
            5 -> CryptoException.EncryptionFailed(FfiConverterString.read(buf))
            6 -> CryptoException.DecryptionFailed(FfiConverterString.read(buf))
            7 -> CryptoException.HexException(FfiConverterString.read(buf))
            8 -> CryptoException.InvalidNonce(FfiConverterString.read(buf))
            9 -> CryptoException.InvalidCiphertext(FfiConverterString.read(buf))
            10 -> CryptoException.KeyDerivationFailed(FfiConverterString.read(buf))
            11 -> CryptoException.SignatureVerificationFailed(FfiConverterString.read(buf))
            12 -> CryptoException.InvalidNsec(FfiConverterString.read(buf))
            13 -> CryptoException.InvalidNpub(FfiConverterString.read(buf))
            14 -> CryptoException.JsonException(FfiConverterString.read(buf))
            15 -> CryptoException.WrongPin(FfiConverterString.read(buf))
            16 -> CryptoException.InvalidPin(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: CryptoException): ULong {
        return 4UL
    }

    override fun write(value: CryptoException, buf: ByteBuffer) {
        when(value) {
            is CryptoException.InvalidSecretKey -> {
                buf.putInt(1)
                Unit
            }
            is CryptoException.InvalidPublicKey -> {
                buf.putInt(2)
                Unit
            }
            is CryptoException.InvalidEphemeralKey -> {
                buf.putInt(3)
                Unit
            }
            is CryptoException.EcdhFailed -> {
                buf.putInt(4)
                Unit
            }
            is CryptoException.EncryptionFailed -> {
                buf.putInt(5)
                Unit
            }
            is CryptoException.DecryptionFailed -> {
                buf.putInt(6)
                Unit
            }
            is CryptoException.HexException -> {
                buf.putInt(7)
                Unit
            }
            is CryptoException.InvalidNonce -> {
                buf.putInt(8)
                Unit
            }
            is CryptoException.InvalidCiphertext -> {
                buf.putInt(9)
                Unit
            }
            is CryptoException.KeyDerivationFailed -> {
                buf.putInt(10)
                Unit
            }
            is CryptoException.SignatureVerificationFailed -> {
                buf.putInt(11)
                Unit
            }
            is CryptoException.InvalidNsec -> {
                buf.putInt(12)
                Unit
            }
            is CryptoException.InvalidNpub -> {
                buf.putInt(13)
                Unit
            }
            is CryptoException.JsonException -> {
                buf.putInt(14)
                Unit
            }
            is CryptoException.WrongPin -> {
                buf.putInt(15)
                Unit
            }
            is CryptoException.InvalidPin -> {
                buf.putInt(16)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRecipientKeyEnvelope: FfiConverterRustBuffer<List<RecipientKeyEnvelope>> {
    override fun read(buf: ByteBuffer): List<RecipientKeyEnvelope> {
        val len = buf.getInt()
        return List<RecipientKeyEnvelope>(len) {
            FfiConverterTypeRecipientKeyEnvelope.read(buf)
        }
    }

    override fun allocationSize(value: List<RecipientKeyEnvelope>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRecipientKeyEnvelope.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<RecipientKeyEnvelope>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRecipientKeyEnvelope.write(it, buf)
        }
    }
}
        /**
         * Create a Schnorr auth token for API authentication.
         *
         * The message is bound to the specific request method + path to prevent
         * cross-endpoint replay attacks.
         */
    @Throws(CryptoException::class) fun `createAuthToken`(`secretKeyHex`: kotlin.String, `timestamp`: kotlin.ULong, `method`: kotlin.String, `path`: kotlin.String): AuthToken {
            return FfiConverterTypeAuthToken.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_create_auth_token(
        FfiConverterString.lower(`secretKeyHex`),FfiConverterULong.lower(`timestamp`),FfiConverterString.lower(`method`),FfiConverterString.lower(`path`),_status)
}
    )
    }
    

        /**
         * Decrypt a call record's encrypted metadata using the admin's envelope.
         */
    @Throws(CryptoException::class) fun `decryptCallRecordForReader`(`encryptedContent`: kotlin.String, `adminEnvelopes`: List<RecipientKeyEnvelope>, `secretKeyHex`: kotlin.String, `readerPubkey`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_decrypt_call_record_for_reader(
        FfiConverterString.lower(`encryptedContent`),FfiConverterSequenceTypeRecipientKeyEnvelope.lower(`adminEnvelopes`),FfiConverterString.lower(`secretKeyHex`),FfiConverterString.lower(`readerPubkey`),_status)
}
    )
    }
    

        /**
         * Decrypt a draft.
         */
    @Throws(CryptoException::class) fun `decryptDraft`(`packedHex`: kotlin.String, `secretKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_decrypt_draft(
        FfiConverterString.lower(`packedHex`),FfiConverterString.lower(`secretKeyHex`),_status)
}
    )
    }
    

        /**
         * Decrypt a message using the reader's envelope from the list.
         */
    @Throws(CryptoException::class) fun `decryptMessageForReader`(`encryptedContent`: kotlin.String, `readerEnvelopes`: List<RecipientKeyEnvelope>, `secretKeyHex`: kotlin.String, `readerPubkey`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_decrypt_message_for_reader(
        FfiConverterString.lower(`encryptedContent`),FfiConverterSequenceTypeRecipientKeyEnvelope.lower(`readerEnvelopes`),FfiConverterString.lower(`secretKeyHex`),FfiConverterString.lower(`readerPubkey`),_status)
}
    )
    }
    

        /**
         * Decrypt a V2 note using the appropriate envelope for the current user.
         */
    @Throws(CryptoException::class) fun `decryptNote`(`encryptedContent`: kotlin.String, `envelope`: KeyEnvelope, `secretKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_decrypt_note(
        FfiConverterString.lower(`encryptedContent`),FfiConverterTypeKeyEnvelope.lower(`envelope`),FfiConverterString.lower(`secretKeyHex`),_status)
}
    )
    }
    

        /**
         * Decrypt a stored nsec using a PIN. Returns the nsec bech32 string or error.
         */
    @Throws(CryptoException::class) fun `decryptWithPin`(`data`: EncryptedKeyData, `pin`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_decrypt_with_pin(
        FfiConverterTypeEncryptedKeyData.lower(`data`),FfiConverterString.lower(`pin`),_status)
}
    )
    }
    

        /**
         * Derive a 32-byte KEK from a PIN using PBKDF2-SHA256, returned as hex.
         *
         * `salt_hex` is a hex-encoded salt (typically 16 bytes / 32 hex chars).
         */
    @Throws(CryptoException::class) fun `deriveKekHex`(`pin`: kotlin.String, `saltHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_derive_kek_hex(
        FfiConverterString.lower(`pin`),FfiConverterString.lower(`saltHex`),_status)
}
    )
    }
    

        /**
         * Unwrap a 32-byte symmetric key from an ECIES envelope, returned as hex.
         */
    @Throws(CryptoException::class) fun `eciesUnwrapKeyHex`(`envelope`: KeyEnvelope, `secretKeyHex`: kotlin.String, `label`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_ecies_unwrap_key_hex(
        FfiConverterTypeKeyEnvelope.lower(`envelope`),FfiConverterString.lower(`secretKeyHex`),FfiConverterString.lower(`label`),_status)
}
    )
    }
    

        /**
         * Wrap a 32-byte symmetric key (hex) for a recipient using ECIES.
         *
         * The `key_hex` parameter is a 64-char hex string encoding 32 bytes.
         */
    @Throws(CryptoException::class) fun `eciesWrapKeyHex`(`keyHex`: kotlin.String, `recipientPubkeyHex`: kotlin.String, `label`: kotlin.String): KeyEnvelope {
            return FfiConverterTypeKeyEnvelope.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_ecies_wrap_key_hex(
        FfiConverterString.lower(`keyHex`),FfiConverterString.lower(`recipientPubkeyHex`),FfiConverterString.lower(`label`),_status)
}
    )
    }
    

        /**
         * Encrypt a draft (local auto-save) with HKDF-derived key.
         */
    @Throws(CryptoException::class) fun `encryptDraft`(`plaintext`: kotlin.String, `secretKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_encrypt_draft(
        FfiConverterString.lower(`plaintext`),FfiConverterString.lower(`secretKeyHex`),_status)
}
    )
    }
    

        /**
         * Encrypt a message for multiple readers using the envelope pattern.
         */
    @Throws(CryptoException::class) fun `encryptMessageForReaders`(`plaintext`: kotlin.String, `readerPubkeys`: List<kotlin.String>): EncryptedMessage {
            return FfiConverterTypeEncryptedMessage.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_encrypt_message_for_readers(
        FfiConverterString.lower(`plaintext`),FfiConverterSequenceString.lower(`readerPubkeys`),_status)
}
    )
    }
    

        /**
         * Encrypt a note with a random per-note key, wrapped for the author and all admins.
         */
    @Throws(CryptoException::class) fun `encryptNoteForRecipients`(`payloadJson`: kotlin.String, `authorPubkey`: kotlin.String, `adminPubkeys`: List<kotlin.String>): EncryptedNote {
            return FfiConverterTypeEncryptedNote.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_encrypt_note_for_recipients(
        FfiConverterString.lower(`payloadJson`),FfiConverterString.lower(`authorPubkey`),FfiConverterSequenceString.lower(`adminPubkeys`),_status)
}
    )
    }
    

        /**
         * Encrypt an nsec bech32 string with a PIN.
         */
    @Throws(CryptoException::class) fun `encryptWithPin`(`nsec`: kotlin.String, `pin`: kotlin.String, `pubkeyHex`: kotlin.String): EncryptedKeyData {
            return FfiConverterTypeEncryptedKeyData.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_encrypt_with_pin(
        FfiConverterString.lower(`nsec`),FfiConverterString.lower(`pin`),FfiConverterString.lower(`pubkeyHex`),_status)
}
    )
    }
    

        /**
         * Generate a new random secp256k1 keypair.
         */ fun `generateKeypair`(): KeyPair {
            return FfiConverterTypeKeyPair.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_generate_keypair(
        _status)
}
    )
    }
    

        /**
         * Get the x-only public key (hex) from a secret key (hex).
         */
    @Throws(CryptoException::class) fun `getPublicKey`(`secretKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_get_public_key(
        FfiConverterString.lower(`secretKeyHex`),_status)
}
    )
    }
    

        /**
         * Validate an nsec bech32 string.
         */ fun `isValidNsec`(`nsec`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_is_valid_nsec(
        FfiConverterString.lower(`nsec`),_status)
}
    )
    }
    

        /**
         * Validate PIN format: 4-6 digits.
         */ fun `isValidPin`(`pin`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_is_valid_pin(
        FfiConverterString.lower(`pin`),_status)
}
    )
    }
    

        /**
         * Derive a keypair from an nsec bech32 string.
         */
    @Throws(CryptoException::class) fun `keypairFromNsec`(`nsec`: kotlin.String): KeyPair {
            return FfiConverterTypeKeyPair.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_keypair_from_nsec(
        FfiConverterString.lower(`nsec`),_status)
}
    )
    }
    

        /**
         * Generate 32 random bytes, returned as a hex string.
         */ fun `randomBytesHex`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_random_bytes_hex(
        _status)
}
    )
    }
    

        /**
         * Verify a Schnorr auth token.
         *
         * Returns true if the signature is valid for the given method + path.
         */
    @Throws(CryptoException::class) fun `verifyAuthToken`(`token`: AuthToken, `method`: kotlin.String, `path`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_verify_auth_token(
        FfiConverterTypeAuthToken.lower(`token`),FfiConverterString.lower(`method`),FfiConverterString.lower(`path`),_status)
}
    )
    }
    

        /**
         * Verify a raw Schnorr signature over a message hash.
         */
    @Throws(CryptoException::class) fun `verifySchnorr`(`messageHex`: kotlin.String, `signatureHex`: kotlin.String, `pubkeyHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(CryptoException) { _status ->
    UniffiLib.INSTANCE.uniffi_llamenos_core_fn_func_verify_schnorr(
        FfiConverterString.lower(`messageHex`),FfiConverterString.lower(`signatureHex`),FfiConverterString.lower(`pubkeyHex`),_status)
}
    )
    }
    


