// Build-time constants injected by Vite (Epic 79: Reproducible Builds)
// CI sets these from SOURCE_DATE_EPOCH and GITHUB_SHA; dev builds use defaults
declare const __BUILD_TIME__: string
declare const __BUILD_COMMIT__: string
declare const __BUILD_VERSION__: string

// WASM crypto module — generated by `bun run crypto:wasm` (wasm-pack).
// This ambient declaration satisfies TypeScript when the generated file
// doesn't exist yet. The actual module is loaded dynamically at runtime.
// Replace with generated types after running: bun run crypto:wasm
declare module '*/llamenos_core' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const _: any
  export = _
}
