// Build-time constants injected by Vite (Epic 79: Reproducible Builds)
// CI sets these from SOURCE_DATE_EPOCH and GITHUB_SHA; dev builds use defaults
declare const __BUILD_TIME__: string
declare const __BUILD_COMMIT__: string
declare const __BUILD_VERSION__: string

// ---------------------------------------------------------------------------
// WASM crypto module stub
// Generated by `bun run crypto:wasm` from packages/crypto (gitignored build artifact).
// This ambient declaration satisfies TypeScript without requiring the build output.
// ---------------------------------------------------------------------------
declare module '*/packages/crypto/dist/wasm/llamenos_core' {
  const init: () => Promise<void>
  export default init

  export interface KeyPair {
    pubkeyHex: string
    npub: string
    nsec: string
  }

  export interface EncryptedNoteResult {
    encryptedContent: string
    authorEnvelope: { pubkey: string; wrappedKey: string; ephemeralPubkey: string }
    adminEnvelopes: Array<{ pubkey: string; wrappedKey: string; ephemeralPubkey: string }>
  }

  export interface EncryptedMessageResult {
    encryptedContent: string
    readerEnvelopes: Array<{ pubkey: string; wrappedKey: string; ephemeralPubkey: string }>
  }

  export interface SignedNostrEvent {
    id: string
    pubkey: string
    created_at: number
    kind: number
    tags: string[][]
    content: string
    sig: string
  }

  export interface ProvisioningEncryptResult {
    encryptedHex: string
    sasCode: string
  }

  export interface ProvisioningDecryptResult {
    nsec: string
    sasCode: string
  }

  export class WasmCryptoState {
    importKey(nsec: string, pin: string): unknown
    getPublicKey(): string
    createAuthToken(method: string, path: string): unknown
    eciesUnwrapKey(envelopeJson: string, label: string): string
    encryptNote(payloadJson: string, authorPubkey: string, adminPubkeysJson: string): EncryptedNoteResult
    decryptNote(encryptedContent: string, envelopeJson: string): string
    decryptLegacyNote(packed: string): string
    encryptMessage(plaintext: string, readerPubkeysJson: string): EncryptedMessageResult
    decryptMessage(encryptedContent: string, readerEnvelopesJson: string): string
    decryptCallRecord(encryptedContent: string, adminEnvelopesJson: string): string
    decryptTranscription(packed: string, ephemeralPubkeyHex: string): string
    encryptDraft(plaintext: string): string
    decryptDraft(packed: string): string
    encryptExport(jsonString: string): string
    signNostrEvent(eventTemplateJson: string): SignedNostrEvent
    decryptFileMetadata(encryptedContentHex: string, envelopeJson: string): string
    unwrapFileKey(envelopeJson: string): string
    unwrapHubKey(envelopeJson: string): string
    rewrapFileKey(envelopeJson: string, newRecipientPubkeyHex: string): { pubkey: string; wrappedKey: string; ephemeralPubkey: string; [x: string]: unknown }
    encryptNsecForProvisioning(ephemeralPubkeyHex: string): ProvisioningEncryptResult
    generateProvisioningEphemeral(): string
    decryptProvisionedNsec(encryptedHex: string, primaryPubkeyHex: string): ProvisioningDecryptResult
    unlockWithPin(dataJson: string, pin: string): string | null
    lock(): void
    isUnlocked(): boolean
  }

  export function generateKeypair(): KeyPair
  export function keyPairFromNsec(nsec: string): KeyPair | undefined
  export function verifySchnorr(message: string, signature: string, pubkey: string): boolean
  export function isValidNsec(nsec: string): boolean
  export function eciesWrapKey(
    keyHex: string,
    recipientPubkeyHex: string,
    label: string,
  ): { pubkey?: string; wrappedKey: string; ephemeralPubkey: string; [x: string]: unknown }
}
