/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkDeviceRouteImport } from './routes/link-device'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ContactsDirectoryRouteImport } from './routes/contacts-directory'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as BlastsRouteImport } from './routes/blasts'
import { Route as BansRouteImport } from './routes/bans'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteersPubkeyRouteImport } from './routes/volunteers_.$pubkey'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminHubsRouteImport } from './routes/admin/hubs'
import { Route as AdminCaseManagementRouteImport } from './routes/admin/case-management'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkDeviceRoute = LinkDeviceRouteImport.update({
  id: '/link-device',
  path: '/link-device',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsDirectoryRoute = ContactsDirectoryRouteImport.update({
  id: '/contacts-directory',
  path: '/contacts-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastsRoute = BlastsRouteImport.update({
  id: '/blasts',
  path: '/blasts',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersPubkeyRoute = VolunteersPubkeyRouteImport.update({
  id: '/volunteers_/$pubkey',
  path: '/volunteers/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHubsRoute = AdminHubsRouteImport.update({
  id: '/admin/hubs',
  path: '/admin/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCaseManagementRoute = AdminCaseManagementRouteImport.update({
  id: '/admin/case-management',
  path: '/admin/case-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/volunteers/$pubkey': typeof VolunteersPubkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/volunteers/$pubkey': typeof VolunteersPubkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/volunteers_/$pubkey': typeof VolunteersPubkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/volunteers'
    | '/admin/case-management'
    | '/admin/hubs'
    | '/admin/settings'
    | '/admin/system'
    | '/volunteers/$pubkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/volunteers'
    | '/admin/case-management'
    | '/admin/hubs'
    | '/admin/settings'
    | '/admin/system'
    | '/volunteers/$pubkey'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/volunteers'
    | '/admin/case-management'
    | '/admin/hubs'
    | '/admin/settings'
    | '/admin/system'
    | '/volunteers_/$pubkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BansRoute: typeof BansRoute
  BlastsRoute: typeof BlastsRoute
  CallsRoute: typeof CallsRoute
  CasesRoute: typeof CasesRoute
  ContactsRoute: typeof ContactsRoute
  ContactsDirectoryRoute: typeof ContactsDirectoryRoute
  ConversationsRoute: typeof ConversationsRoute
  EventsRoute: typeof EventsRoute
  HelpRoute: typeof HelpRoute
  LinkDeviceRoute: typeof LinkDeviceRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShiftsRoute: typeof ShiftsRoute
  TriageRoute: typeof TriageRoute
  VolunteersRoute: typeof VolunteersRoute
  AdminCaseManagementRoute: typeof AdminCaseManagementRoute
  AdminHubsRoute: typeof AdminHubsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  VolunteersPubkeyRoute: typeof VolunteersPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-device': {
      id: '/link-device'
      path: '/link-device'
      fullPath: '/link-device'
      preLoaderRoute: typeof LinkDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts-directory': {
      id: '/contacts-directory'
      path: '/contacts-directory'
      fullPath: '/contacts-directory'
      preLoaderRoute: typeof ContactsDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blasts': {
      id: '/blasts'
      path: '/blasts'
      fullPath: '/blasts'
      preLoaderRoute: typeof BlastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers_/$pubkey': {
      id: '/volunteers_/$pubkey'
      path: '/volunteers/$pubkey'
      fullPath: '/volunteers/$pubkey'
      preLoaderRoute: typeof VolunteersPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hubs': {
      id: '/admin/hubs'
      path: '/admin/hubs'
      fullPath: '/admin/hubs'
      preLoaderRoute: typeof AdminHubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/case-management': {
      id: '/admin/case-management'
      path: '/admin/case-management'
      fullPath: '/admin/case-management'
      preLoaderRoute: typeof AdminCaseManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BansRoute: BansRoute,
  BlastsRoute: BlastsRoute,
  CallsRoute: CallsRoute,
  CasesRoute: CasesRoute,
  ContactsRoute: ContactsRoute,
  ContactsDirectoryRoute: ContactsDirectoryRoute,
  ConversationsRoute: ConversationsRoute,
  EventsRoute: EventsRoute,
  HelpRoute: HelpRoute,
  LinkDeviceRoute: LinkDeviceRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShiftsRoute: ShiftsRoute,
  TriageRoute: TriageRoute,
  VolunteersRoute: VolunteersRoute,
  AdminCaseManagementRoute: AdminCaseManagementRoute,
  AdminHubsRoute: AdminHubsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  VolunteersPubkeyRoute: VolunteersPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
