/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkDeviceRouteImport } from './routes/link-device'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ContactsDirectoryRouteImport } from './routes/contacts-directory'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as BlastsRouteImport } from './routes/blasts'
import { Route as BansRouteImport } from './routes/bans'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersPubkeyRouteImport } from './routes/users_.$pubkey'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminHubsRedirectRouteImport } from './routes/admin/hubs-redirect'
import { Route as AdminHubsRouteImport } from './routes/admin/hubs'
import { Route as AdminHubCommunicationsRouteImport } from './routes/admin/hub-communications'
import { Route as AdminFirehoseRedirectRouteImport } from './routes/admin/firehose-redirect'
import { Route as AdminFirehoseRouteImport } from './routes/admin/firehose'
import { Route as AdminCaseManagementRedirectRouteImport } from './routes/admin/case-management-redirect'
import { Route as AdminCaseManagementRouteImport } from './routes/admin/case-management'
import { Route as AdminSectionRouteImport } from './routes/admin/$section'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkDeviceRoute = LinkDeviceRouteImport.update({
  id: '/link-device',
  path: '/link-device',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsDirectoryRoute = ContactsDirectoryRouteImport.update({
  id: '/contacts-directory',
  path: '/contacts-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastsRoute = BlastsRouteImport.update({
  id: '/blasts',
  path: '/blasts',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsersPubkeyRoute = UsersPubkeyRouteImport.update({
  id: '/users_/$pubkey',
  path: '/users/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHubsRedirectRoute = AdminHubsRedirectRouteImport.update({
  id: '/hubs-redirect',
  path: '/hubs-redirect',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHubsRoute = AdminHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHubCommunicationsRoute = AdminHubCommunicationsRouteImport.update({
  id: '/hub-communications',
  path: '/hub-communications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFirehoseRedirectRoute = AdminFirehoseRedirectRouteImport.update({
  id: '/firehose-redirect',
  path: '/firehose-redirect',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFirehoseRoute = AdminFirehoseRouteImport.update({
  id: '/firehose',
  path: '/firehose',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCaseManagementRedirectRoute =
  AdminCaseManagementRedirectRouteImport.update({
    id: '/case-management-redirect',
    path: '/case-management-redirect',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCaseManagementRoute = AdminCaseManagementRouteImport.update({
  id: '/case-management',
  path: '/case-management',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/case-management-redirect': typeof AdminCaseManagementRedirectRoute
  '/admin/firehose': typeof AdminFirehoseRoute
  '/admin/firehose-redirect': typeof AdminFirehoseRedirectRoute
  '/admin/hub-communications': typeof AdminHubCommunicationsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/hubs-redirect': typeof AdminHubsRedirectRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/users/$pubkey': typeof UsersPubkeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/case-management-redirect': typeof AdminCaseManagementRedirectRoute
  '/admin/firehose': typeof AdminFirehoseRoute
  '/admin/firehose-redirect': typeof AdminFirehoseRedirectRoute
  '/admin/hub-communications': typeof AdminHubCommunicationsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/hubs-redirect': typeof AdminHubsRedirectRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/users/$pubkey': typeof UsersPubkeyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/contacts-directory': typeof ContactsDirectoryRoute
  '/conversations': typeof ConversationsRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/triage': typeof TriageRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/case-management': typeof AdminCaseManagementRoute
  '/admin/case-management-redirect': typeof AdminCaseManagementRedirectRoute
  '/admin/firehose': typeof AdminFirehoseRoute
  '/admin/firehose-redirect': typeof AdminFirehoseRedirectRoute
  '/admin/hub-communications': typeof AdminHubCommunicationsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/hubs-redirect': typeof AdminHubsRedirectRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/users_/$pubkey': typeof UsersPubkeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/users'
    | '/admin/$section'
    | '/admin/case-management'
    | '/admin/case-management-redirect'
    | '/admin/firehose'
    | '/admin/firehose-redirect'
    | '/admin/hub-communications'
    | '/admin/hubs'
    | '/admin/hubs-redirect'
    | '/admin/settings'
    | '/admin/system'
    | '/users/$pubkey'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/users'
    | '/admin/$section'
    | '/admin/case-management'
    | '/admin/case-management-redirect'
    | '/admin/firehose'
    | '/admin/firehose-redirect'
    | '/admin/hub-communications'
    | '/admin/hubs'
    | '/admin/hubs-redirect'
    | '/admin/settings'
    | '/admin/system'
    | '/users/$pubkey'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/cases'
    | '/contacts'
    | '/contacts-directory'
    | '/conversations'
    | '/events'
    | '/help'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/triage'
    | '/users'
    | '/admin/$section'
    | '/admin/case-management'
    | '/admin/case-management-redirect'
    | '/admin/firehose'
    | '/admin/firehose-redirect'
    | '/admin/hub-communications'
    | '/admin/hubs'
    | '/admin/hubs-redirect'
    | '/admin/settings'
    | '/admin/system'
    | '/users_/$pubkey'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuditRoute: typeof AuditRoute
  BansRoute: typeof BansRoute
  BlastsRoute: typeof BlastsRoute
  CallsRoute: typeof CallsRoute
  CasesRoute: typeof CasesRoute
  ContactsRoute: typeof ContactsRoute
  ContactsDirectoryRoute: typeof ContactsDirectoryRoute
  ConversationsRoute: typeof ConversationsRoute
  EventsRoute: typeof EventsRoute
  HelpRoute: typeof HelpRoute
  LinkDeviceRoute: typeof LinkDeviceRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShiftsRoute: typeof ShiftsRoute
  TriageRoute: typeof TriageRoute
  UsersRoute: typeof UsersRoute
  UsersPubkeyRoute: typeof UsersPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-device': {
      id: '/link-device'
      path: '/link-device'
      fullPath: '/link-device'
      preLoaderRoute: typeof LinkDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts-directory': {
      id: '/contacts-directory'
      path: '/contacts-directory'
      fullPath: '/contacts-directory'
      preLoaderRoute: typeof ContactsDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blasts': {
      id: '/blasts'
      path: '/blasts'
      fullPath: '/blasts'
      preLoaderRoute: typeof BlastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/users_/$pubkey': {
      id: '/users_/$pubkey'
      path: '/users/$pubkey'
      fullPath: '/users/$pubkey'
      preLoaderRoute: typeof UsersPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hubs-redirect': {
      id: '/admin/hubs-redirect'
      path: '/hubs-redirect'
      fullPath: '/admin/hubs-redirect'
      preLoaderRoute: typeof AdminHubsRedirectRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hubs': {
      id: '/admin/hubs'
      path: '/hubs'
      fullPath: '/admin/hubs'
      preLoaderRoute: typeof AdminHubsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hub-communications': {
      id: '/admin/hub-communications'
      path: '/hub-communications'
      fullPath: '/admin/hub-communications'
      preLoaderRoute: typeof AdminHubCommunicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/firehose-redirect': {
      id: '/admin/firehose-redirect'
      path: '/firehose-redirect'
      fullPath: '/admin/firehose-redirect'
      preLoaderRoute: typeof AdminFirehoseRedirectRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/firehose': {
      id: '/admin/firehose'
      path: '/firehose'
      fullPath: '/admin/firehose'
      preLoaderRoute: typeof AdminFirehoseRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/case-management-redirect': {
      id: '/admin/case-management-redirect'
      path: '/case-management-redirect'
      fullPath: '/admin/case-management-redirect'
      preLoaderRoute: typeof AdminCaseManagementRedirectRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/case-management': {
      id: '/admin/case-management'
      path: '/case-management'
      fullPath: '/admin/case-management'
      preLoaderRoute: typeof AdminCaseManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminCaseManagementRoute: typeof AdminCaseManagementRoute
  AdminCaseManagementRedirectRoute: typeof AdminCaseManagementRedirectRoute
  AdminFirehoseRoute: typeof AdminFirehoseRoute
  AdminFirehoseRedirectRoute: typeof AdminFirehoseRedirectRoute
  AdminHubCommunicationsRoute: typeof AdminHubCommunicationsRoute
  AdminHubsRoute: typeof AdminHubsRoute
  AdminHubsRedirectRoute: typeof AdminHubsRedirectRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminCaseManagementRoute: AdminCaseManagementRoute,
  AdminCaseManagementRedirectRoute: AdminCaseManagementRedirectRoute,
  AdminFirehoseRoute: AdminFirehoseRoute,
  AdminFirehoseRedirectRoute: AdminFirehoseRedirectRoute,
  AdminHubCommunicationsRoute: AdminHubCommunicationsRoute,
  AdminHubsRoute: AdminHubsRoute,
  AdminHubsRedirectRoute: AdminHubsRedirectRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuditRoute: AuditRoute,
  BansRoute: BansRoute,
  BlastsRoute: BlastsRoute,
  CallsRoute: CallsRoute,
  CasesRoute: CasesRoute,
  ContactsRoute: ContactsRoute,
  ContactsDirectoryRoute: ContactsDirectoryRoute,
  ConversationsRoute: ConversationsRoute,
  EventsRoute: EventsRoute,
  HelpRoute: HelpRoute,
  LinkDeviceRoute: LinkDeviceRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShiftsRoute: ShiftsRoute,
  TriageRoute: TriageRoute,
  UsersRoute: UsersRoute,
  UsersPubkeyRoute: UsersPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
