// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(LlamenosCoreFFI)
import LlamenosCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_llamenos_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_llamenos_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A signed authentication token.
 */
public struct AuthToken {
    public let pubkey: String
    public let timestamp: UInt64
    public let token: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkey: String, timestamp: UInt64, token: String) {
        self.pubkey = pubkey
        self.timestamp = timestamp
        self.token = token
    }
}



extension AuthToken: Equatable, Hashable {
    public static func ==(lhs: AuthToken, rhs: AuthToken) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.token != rhs.token {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(timestamp)
        hasher.combine(token)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthToken: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthToken {
        return
            try AuthToken(
                pubkey: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterUInt64.read(from: &buf), 
                token: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AuthToken, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterUInt64.write(value.timestamp, into: &buf)
        FfiConverterString.write(value.token, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthToken_lift(_ buf: RustBuffer) throws -> AuthToken {
    return try FfiConverterTypeAuthToken.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthToken_lower(_ value: AuthToken) -> RustBuffer {
    return FfiConverterTypeAuthToken.lower(value)
}


/**
 * Encrypted key data stored on disk (Stronghold on desktop, Keychain on mobile).
 */
public struct EncryptedKeyData {
    /**
     * hex, 16 bytes
     */
    public let salt: String
    /**
     * PBKDF2 iteration count (600,000)
     */
    public let iterations: UInt32
    /**
     * hex, 24 bytes (XChaCha20 nonce)
     */
    public let nonce: String
    /**
     * hex, encrypted nsec bech32 string
     */
    public let ciphertext: String
    /**
     * Truncated SHA-256 hash of pubkey (not plaintext) for identification
     */
    public let pubkey: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * hex, 16 bytes
         */salt: String, 
        /**
         * PBKDF2 iteration count (600,000)
         */iterations: UInt32, 
        /**
         * hex, 24 bytes (XChaCha20 nonce)
         */nonce: String, 
        /**
         * hex, encrypted nsec bech32 string
         */ciphertext: String, 
        /**
         * Truncated SHA-256 hash of pubkey (not plaintext) for identification
         */pubkey: String) {
        self.salt = salt
        self.iterations = iterations
        self.nonce = nonce
        self.ciphertext = ciphertext
        self.pubkey = pubkey
    }
}



extension EncryptedKeyData: Equatable, Hashable {
    public static func ==(lhs: EncryptedKeyData, rhs: EncryptedKeyData) -> Bool {
        if lhs.salt != rhs.salt {
            return false
        }
        if lhs.iterations != rhs.iterations {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        if lhs.ciphertext != rhs.ciphertext {
            return false
        }
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(salt)
        hasher.combine(iterations)
        hasher.combine(nonce)
        hasher.combine(ciphertext)
        hasher.combine(pubkey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedKeyData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedKeyData {
        return
            try EncryptedKeyData(
                salt: FfiConverterString.read(from: &buf), 
                iterations: FfiConverterUInt32.read(from: &buf), 
                nonce: FfiConverterString.read(from: &buf), 
                ciphertext: FfiConverterString.read(from: &buf), 
                pubkey: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedKeyData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.salt, into: &buf)
        FfiConverterUInt32.write(value.iterations, into: &buf)
        FfiConverterString.write(value.nonce, into: &buf)
        FfiConverterString.write(value.ciphertext, into: &buf)
        FfiConverterString.write(value.pubkey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedKeyData_lift(_ buf: RustBuffer) throws -> EncryptedKeyData {
    return try FfiConverterTypeEncryptedKeyData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedKeyData_lower(_ value: EncryptedKeyData) -> RustBuffer {
    return FfiConverterTypeEncryptedKeyData.lower(value)
}


/**
 * Encrypted message with per-message key wrapped for each reader.
 */
public struct EncryptedMessage {
    /**
     * hex: nonce(24) + ciphertext
     */
    public let encryptedContent: String
    /**
     * Message key wrapped for each reader (volunteer + admins)
     */
    public let readerEnvelopes: [RecipientKeyEnvelope]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * hex: nonce(24) + ciphertext
         */encryptedContent: String, 
        /**
         * Message key wrapped for each reader (volunteer + admins)
         */readerEnvelopes: [RecipientKeyEnvelope]) {
        self.encryptedContent = encryptedContent
        self.readerEnvelopes = readerEnvelopes
    }
}



extension EncryptedMessage: Equatable, Hashable {
    public static func ==(lhs: EncryptedMessage, rhs: EncryptedMessage) -> Bool {
        if lhs.encryptedContent != rhs.encryptedContent {
            return false
        }
        if lhs.readerEnvelopes != rhs.readerEnvelopes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(encryptedContent)
        hasher.combine(readerEnvelopes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedMessage {
        return
            try EncryptedMessage(
                encryptedContent: FfiConverterString.read(from: &buf), 
                readerEnvelopes: FfiConverterSequenceTypeRecipientKeyEnvelope.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.encryptedContent, into: &buf)
        FfiConverterSequenceTypeRecipientKeyEnvelope.write(value.readerEnvelopes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessage_lift(_ buf: RustBuffer) throws -> EncryptedMessage {
    return try FfiConverterTypeEncryptedMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMessage_lower(_ value: EncryptedMessage) -> RustBuffer {
    return FfiConverterTypeEncryptedMessage.lower(value)
}


/**
 * Encrypted note with per-note key wrapped for author + each admin.
 */
public struct EncryptedNote {
    /**
     * hex: nonce(24) + ciphertext
     */
    public let encryptedContent: String
    /**
     * Note key wrapped for the author
     */
    public let authorEnvelope: KeyEnvelope
    /**
     * Note key wrapped for each admin
     */
    public let adminEnvelopes: [RecipientKeyEnvelope]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * hex: nonce(24) + ciphertext
         */encryptedContent: String, 
        /**
         * Note key wrapped for the author
         */authorEnvelope: KeyEnvelope, 
        /**
         * Note key wrapped for each admin
         */adminEnvelopes: [RecipientKeyEnvelope]) {
        self.encryptedContent = encryptedContent
        self.authorEnvelope = authorEnvelope
        self.adminEnvelopes = adminEnvelopes
    }
}



extension EncryptedNote: Equatable, Hashable {
    public static func ==(lhs: EncryptedNote, rhs: EncryptedNote) -> Bool {
        if lhs.encryptedContent != rhs.encryptedContent {
            return false
        }
        if lhs.authorEnvelope != rhs.authorEnvelope {
            return false
        }
        if lhs.adminEnvelopes != rhs.adminEnvelopes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(encryptedContent)
        hasher.combine(authorEnvelope)
        hasher.combine(adminEnvelopes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedNote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedNote {
        return
            try EncryptedNote(
                encryptedContent: FfiConverterString.read(from: &buf), 
                authorEnvelope: FfiConverterTypeKeyEnvelope.read(from: &buf), 
                adminEnvelopes: FfiConverterSequenceTypeRecipientKeyEnvelope.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedNote, into buf: inout [UInt8]) {
        FfiConverterString.write(value.encryptedContent, into: &buf)
        FfiConverterTypeKeyEnvelope.write(value.authorEnvelope, into: &buf)
        FfiConverterSequenceTypeRecipientKeyEnvelope.write(value.adminEnvelopes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedNote_lift(_ buf: RustBuffer) throws -> EncryptedNote {
    return try FfiConverterTypeEncryptedNote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedNote_lower(_ value: EncryptedNote) -> RustBuffer {
    return FfiConverterTypeEncryptedNote.lower(value)
}


/**
 * A symmetric key wrapped via ECIES for a single recipient.
 */
public struct KeyEnvelope {
    /**
     * hex: nonce(24) + ciphertext(48 = 32 key + 16 tag)
     */
    public let wrappedKey: String
    /**
     * hex: compressed 33-byte ephemeral pubkey
     */
    public let ephemeralPubkey: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * hex: nonce(24) + ciphertext(48 = 32 key + 16 tag)
         */wrappedKey: String, 
        /**
         * hex: compressed 33-byte ephemeral pubkey
         */ephemeralPubkey: String) {
        self.wrappedKey = wrappedKey
        self.ephemeralPubkey = ephemeralPubkey
    }
}



extension KeyEnvelope: Equatable, Hashable {
    public static func ==(lhs: KeyEnvelope, rhs: KeyEnvelope) -> Bool {
        if lhs.wrappedKey != rhs.wrappedKey {
            return false
        }
        if lhs.ephemeralPubkey != rhs.ephemeralPubkey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(wrappedKey)
        hasher.combine(ephemeralPubkey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyEnvelope: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyEnvelope {
        return
            try KeyEnvelope(
                wrappedKey: FfiConverterString.read(from: &buf), 
                ephemeralPubkey: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: KeyEnvelope, into buf: inout [UInt8]) {
        FfiConverterString.write(value.wrappedKey, into: &buf)
        FfiConverterString.write(value.ephemeralPubkey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyEnvelope_lift(_ buf: RustBuffer) throws -> KeyEnvelope {
    return try FfiConverterTypeKeyEnvelope.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyEnvelope_lower(_ value: KeyEnvelope) -> RustBuffer {
    return FfiConverterTypeKeyEnvelope.lower(value)
}


/**
 * A secp256k1 keypair with Nostr bech32 encodings.
 */
public struct KeyPair {
    /**
     * hex-encoded 32-byte secret key
     */
    public let secretKeyHex: String
    /**
     * hex-encoded 32-byte x-only public key
     */
    public let publicKey: String
    /**
     * bech32-encoded secret key (nsec1...)
     */
    public let nsec: String
    /**
     * bech32-encoded public key (npub1...)
     */
    public let npub: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * hex-encoded 32-byte secret key
         */secretKeyHex: String, 
        /**
         * hex-encoded 32-byte x-only public key
         */publicKey: String, 
        /**
         * bech32-encoded secret key (nsec1...)
         */nsec: String, 
        /**
         * bech32-encoded public key (npub1...)
         */npub: String) {
        self.secretKeyHex = secretKeyHex
        self.publicKey = publicKey
        self.nsec = nsec
        self.npub = npub
    }
}



extension KeyPair: Equatable, Hashable {
    public static func ==(lhs: KeyPair, rhs: KeyPair) -> Bool {
        if lhs.secretKeyHex != rhs.secretKeyHex {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.nsec != rhs.nsec {
            return false
        }
        if lhs.npub != rhs.npub {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretKeyHex)
        hasher.combine(publicKey)
        hasher.combine(nsec)
        hasher.combine(npub)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyPair {
        return
            try KeyPair(
                secretKeyHex: FfiConverterString.read(from: &buf), 
                publicKey: FfiConverterString.read(from: &buf), 
                nsec: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: KeyPair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretKeyHex, into: &buf)
        FfiConverterString.write(value.publicKey, into: &buf)
        FfiConverterString.write(value.nsec, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPair_lift(_ buf: RustBuffer) throws -> KeyPair {
    return try FfiConverterTypeKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPair_lower(_ value: KeyPair) -> RustBuffer {
    return FfiConverterTypeKeyPair.lower(value)
}


/**
 * A KeyEnvelope tagged with the recipient's pubkey (for multi-recipient scenarios).
 */
public struct RecipientKeyEnvelope {
    /**
     * recipient's x-only pubkey (hex, 32 bytes / 64 hex chars)
     */
    public let pubkey: String
    /**
     * hex: nonce(24) + ciphertext(48)
     */
    public let wrappedKey: String
    /**
     * hex: compressed 33-byte ephemeral pubkey
     */
    public let ephemeralPubkey: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * recipient's x-only pubkey (hex, 32 bytes / 64 hex chars)
         */pubkey: String, 
        /**
         * hex: nonce(24) + ciphertext(48)
         */wrappedKey: String, 
        /**
         * hex: compressed 33-byte ephemeral pubkey
         */ephemeralPubkey: String) {
        self.pubkey = pubkey
        self.wrappedKey = wrappedKey
        self.ephemeralPubkey = ephemeralPubkey
    }
}



extension RecipientKeyEnvelope: Equatable, Hashable {
    public static func ==(lhs: RecipientKeyEnvelope, rhs: RecipientKeyEnvelope) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.wrappedKey != rhs.wrappedKey {
            return false
        }
        if lhs.ephemeralPubkey != rhs.ephemeralPubkey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(wrappedKey)
        hasher.combine(ephemeralPubkey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecipientKeyEnvelope: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecipientKeyEnvelope {
        return
            try RecipientKeyEnvelope(
                pubkey: FfiConverterString.read(from: &buf), 
                wrappedKey: FfiConverterString.read(from: &buf), 
                ephemeralPubkey: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RecipientKeyEnvelope, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterString.write(value.wrappedKey, into: &buf)
        FfiConverterString.write(value.ephemeralPubkey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecipientKeyEnvelope_lift(_ buf: RustBuffer) throws -> RecipientKeyEnvelope {
    return try FfiConverterTypeRecipientKeyEnvelope.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecipientKeyEnvelope_lower(_ value: RecipientKeyEnvelope) -> RustBuffer {
    return FfiConverterTypeRecipientKeyEnvelope.lower(value)
}


public enum CryptoError {

    
    
    case InvalidSecretKey(message: String)
    
    case InvalidPublicKey(message: String)
    
    case InvalidEphemeralKey(message: String)
    
    case EcdhFailed(message: String)
    
    case EncryptionFailed(message: String)
    
    case DecryptionFailed(message: String)
    
    case HexError(message: String)
    
    case InvalidNonce(message: String)
    
    case InvalidCiphertext(message: String)
    
    case KeyDerivationFailed(message: String)
    
    case SignatureVerificationFailed(message: String)
    
    case InvalidNsec(message: String)
    
    case InvalidNpub(message: String)
    
    case JsonError(message: String)
    
    case WrongPin(message: String)
    
    case InvalidPin(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidSecretKey(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidPublicKey(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidEphemeralKey(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .EcdhFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .EncryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .DecryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .HexError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .InvalidNonce(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .InvalidCiphertext(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .KeyDerivationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .SignatureVerificationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .InvalidNsec(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .InvalidNpub(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .JsonError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 15: return .WrongPin(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .InvalidPin(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidSecretKey(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidPublicKey(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidEphemeralKey(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .EcdhFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .EncryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .DecryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .HexError(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .InvalidNonce(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .InvalidCiphertext(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .KeyDerivationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .SignatureVerificationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))
        case .InvalidNsec(_ /* message is ignored*/):
            writeInt(&buf, Int32(12))
        case .InvalidNpub(_ /* message is ignored*/):
            writeInt(&buf, Int32(13))
        case .JsonError(_ /* message is ignored*/):
            writeInt(&buf, Int32(14))
        case .WrongPin(_ /* message is ignored*/):
            writeInt(&buf, Int32(15))
        case .InvalidPin(_ /* message is ignored*/):
            writeInt(&buf, Int32(16))

        
        }
    }
}


extension CryptoError: Equatable, Hashable {}

extension CryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRecipientKeyEnvelope: FfiConverterRustBuffer {
    typealias SwiftType = [RecipientKeyEnvelope]

    public static func write(_ value: [RecipientKeyEnvelope], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRecipientKeyEnvelope.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RecipientKeyEnvelope] {
        let len: Int32 = try readInt(&buf)
        var seq = [RecipientKeyEnvelope]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRecipientKeyEnvelope.read(from: &buf))
        }
        return seq
    }
}
/**
 * Create a Schnorr auth token for API authentication.
 *
 * The message is bound to the specific request method + path to prevent
 * cross-endpoint replay attacks.
 */
public func createAuthToken(secretKeyHex: String, timestamp: UInt64, method: String, path: String)throws  -> AuthToken {
    return try  FfiConverterTypeAuthToken.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_create_auth_token(
        FfiConverterString.lower(secretKeyHex),
        FfiConverterUInt64.lower(timestamp),
        FfiConverterString.lower(method),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Decrypt a call record's encrypted metadata using the admin's envelope.
 */
public func decryptCallRecordForReader(encryptedContent: String, adminEnvelopes: [RecipientKeyEnvelope], secretKeyHex: String, readerPubkey: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_decrypt_call_record_for_reader(
        FfiConverterString.lower(encryptedContent),
        FfiConverterSequenceTypeRecipientKeyEnvelope.lower(adminEnvelopes),
        FfiConverterString.lower(secretKeyHex),
        FfiConverterString.lower(readerPubkey),$0
    )
})
}
/**
 * Decrypt a draft.
 */
public func decryptDraft(packedHex: String, secretKeyHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_decrypt_draft(
        FfiConverterString.lower(packedHex),
        FfiConverterString.lower(secretKeyHex),$0
    )
})
}
/**
 * Decrypt a message using the reader's envelope from the list.
 */
public func decryptMessageForReader(encryptedContent: String, readerEnvelopes: [RecipientKeyEnvelope], secretKeyHex: String, readerPubkey: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_decrypt_message_for_reader(
        FfiConverterString.lower(encryptedContent),
        FfiConverterSequenceTypeRecipientKeyEnvelope.lower(readerEnvelopes),
        FfiConverterString.lower(secretKeyHex),
        FfiConverterString.lower(readerPubkey),$0
    )
})
}
/**
 * Decrypt a V2 note using the appropriate envelope for the current user.
 */
public func decryptNote(encryptedContent: String, envelope: KeyEnvelope, secretKeyHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_decrypt_note(
        FfiConverterString.lower(encryptedContent),
        FfiConverterTypeKeyEnvelope.lower(envelope),
        FfiConverterString.lower(secretKeyHex),$0
    )
})
}
/**
 * Decrypt a stored nsec using a PIN. Returns the nsec bech32 string or error.
 */
public func decryptWithPin(data: EncryptedKeyData, pin: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_decrypt_with_pin(
        FfiConverterTypeEncryptedKeyData.lower(data),
        FfiConverterString.lower(pin),$0
    )
})
}
/**
 * Derive a 32-byte KEK from a PIN using PBKDF2-SHA256, returned as hex.
 *
 * `salt_hex` is a hex-encoded salt (typically 16 bytes / 32 hex chars).
 */
public func deriveKekHex(pin: String, saltHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_derive_kek_hex(
        FfiConverterString.lower(pin),
        FfiConverterString.lower(saltHex),$0
    )
})
}
/**
 * Unwrap a 32-byte symmetric key from an ECIES envelope, returned as hex.
 */
public func eciesUnwrapKeyHex(envelope: KeyEnvelope, secretKeyHex: String, label: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_ecies_unwrap_key_hex(
        FfiConverterTypeKeyEnvelope.lower(envelope),
        FfiConverterString.lower(secretKeyHex),
        FfiConverterString.lower(label),$0
    )
})
}
/**
 * Wrap a 32-byte symmetric key (hex) for a recipient using ECIES.
 *
 * The `key_hex` parameter is a 64-char hex string encoding 32 bytes.
 */
public func eciesWrapKeyHex(keyHex: String, recipientPubkeyHex: String, label: String)throws  -> KeyEnvelope {
    return try  FfiConverterTypeKeyEnvelope.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_ecies_wrap_key_hex(
        FfiConverterString.lower(keyHex),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterString.lower(label),$0
    )
})
}
/**
 * Encrypt a draft (local auto-save) with HKDF-derived key.
 */
public func encryptDraft(plaintext: String, secretKeyHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_encrypt_draft(
        FfiConverterString.lower(plaintext),
        FfiConverterString.lower(secretKeyHex),$0
    )
})
}
/**
 * Encrypt a message for multiple readers using the envelope pattern.
 */
public func encryptMessageForReaders(plaintext: String, readerPubkeys: [String])throws  -> EncryptedMessage {
    return try  FfiConverterTypeEncryptedMessage.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_encrypt_message_for_readers(
        FfiConverterString.lower(plaintext),
        FfiConverterSequenceString.lower(readerPubkeys),$0
    )
})
}
/**
 * Encrypt a note with a random per-note key, wrapped for the author and all admins.
 */
public func encryptNoteForRecipients(payloadJson: String, authorPubkey: String, adminPubkeys: [String])throws  -> EncryptedNote {
    return try  FfiConverterTypeEncryptedNote.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_encrypt_note_for_recipients(
        FfiConverterString.lower(payloadJson),
        FfiConverterString.lower(authorPubkey),
        FfiConverterSequenceString.lower(adminPubkeys),$0
    )
})
}
/**
 * Encrypt an nsec bech32 string with a PIN.
 */
public func encryptWithPin(nsec: String, pin: String, pubkeyHex: String)throws  -> EncryptedKeyData {
    return try  FfiConverterTypeEncryptedKeyData.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_encrypt_with_pin(
        FfiConverterString.lower(nsec),
        FfiConverterString.lower(pin),
        FfiConverterString.lower(pubkeyHex),$0
    )
})
}
/**
 * Generate a new random secp256k1 keypair.
 */
public func generateKeypair() -> KeyPair {
    return try!  FfiConverterTypeKeyPair.lift(try! rustCall() {
    uniffi_llamenos_core_fn_func_generate_keypair($0
    )
})
}
/**
 * Get the x-only public key (hex) from a secret key (hex).
 */
public func getPublicKey(secretKeyHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_get_public_key(
        FfiConverterString.lower(secretKeyHex),$0
    )
})
}
/**
 * Validate an nsec bech32 string.
 */
public func isValidNsec(nsec: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_llamenos_core_fn_func_is_valid_nsec(
        FfiConverterString.lower(nsec),$0
    )
})
}
/**
 * Validate PIN format: 4-6 digits.
 */
public func isValidPin(pin: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_llamenos_core_fn_func_is_valid_pin(
        FfiConverterString.lower(pin),$0
    )
})
}
/**
 * Derive a keypair from an nsec bech32 string.
 */
public func keypairFromNsec(nsec: String)throws  -> KeyPair {
    return try  FfiConverterTypeKeyPair.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_keypair_from_nsec(
        FfiConverterString.lower(nsec),$0
    )
})
}
/**
 * Generate 32 random bytes, returned as a hex string.
 */
public func randomBytesHex() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_llamenos_core_fn_func_random_bytes_hex($0
    )
})
}
/**
 * Verify a Schnorr auth token.
 *
 * Returns true if the signature is valid for the given method + path.
 */
public func verifyAuthToken(token: AuthToken, method: String, path: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_verify_auth_token(
        FfiConverterTypeAuthToken.lower(token),
        FfiConverterString.lower(method),
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Verify a raw Schnorr signature over a message hash.
 */
public func verifySchnorr(messageHex: String, signatureHex: String, pubkeyHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCryptoError.lift) {
    uniffi_llamenos_core_fn_func_verify_schnorr(
        FfiConverterString.lower(messageHex),
        FfiConverterString.lower(signatureHex),
        FfiConverterString.lower(pubkeyHex),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_llamenos_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_llamenos_core_checksum_func_create_auth_token() != 62800) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_decrypt_call_record_for_reader() != 10926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_decrypt_draft() != 55174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_decrypt_message_for_reader() != 24819) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_decrypt_note() != 17791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_decrypt_with_pin() != 5372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_derive_kek_hex() != 32027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_ecies_unwrap_key_hex() != 45205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_ecies_wrap_key_hex() != 31485) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_encrypt_draft() != 50495) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_encrypt_message_for_readers() != 63610) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_encrypt_note_for_recipients() != 14883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_encrypt_with_pin() != 63866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_generate_keypair() != 4768) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_get_public_key() != 41631) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_is_valid_nsec() != 41860) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_is_valid_pin() != 65518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_keypair_from_nsec() != 313) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_random_bytes_hex() != 19039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_verify_auth_token() != 39412) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_llamenos_core_checksum_func_verify_schnorr() != 51139) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all